/***

    PlotKit.PlotKit 0.9.2 : PACKED VERSION

    THIS FILE IS AUTOMATICALLY GENERATED.  If creating patches, please
    diff against the source tree, not this file.

    For more information, <http://www.liquidx.net/plotkit/>.
    
    Copyright (c) 2006. Alastair Tse.

***/

try{
if(typeof (MochiKit.Base)=="undefined"||typeof (MochiKit.DOM)=="undefined"||typeof (MochiKit.Color)=="undefined"||typeof (MochiKit.Format)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit depends on MochiKit.{Base,Color,DOM,Format}";
}
MochiKit.Base.update(MochiKit.Color.Color.prototype,{asFillColor:function(){
return this.lighterColorWithLevel(0.3);
},asStrokeColor:function(){
return this.darkerColorWithLevel(0.1);
},asPointColor:function(){
return this.lighterColorWithLevel(0.1);
},asTransparent:function(){
return this.colorWithAlpha(0.1);
}});
if(typeof (PlotKit)=="undefined"){
PlotKit={};
}
PlotKit.NAME="PlotKit";
PlotKit.VERSION="0.9.2";
PlotKit.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.toString=function(){
return this.__repr__();
};
if(typeof (PlotKit.Base)=="undefined"){
PlotKit.Base={};
}
PlotKit.Base.NAME="PlotKit.Base";
PlotKit.Base.VERSION=PlotKit.VERSION;
PlotKit.Base.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.Base.toString=function(){
return this.__repr__();
};
PlotKit.Base.usingPrototype=function(){
try{
return (typeof (Object.extend)=="function");
}
catch(e){
return false;
}
};
MochiKit.Base.update(PlotKit.Base,{roundInterval:function(_1,_2,_3){
var _4=MochiKit.Format.roundToFixed;
var _5=_1/_2;
return parseFloat(_4(_5,_3));
},collapse:function(_6){
var m=MochiKit.Base;
var _8=new Array();
for(var i=0;i<_6.length;i++){
_8=m.concat(_8,_6[i]);
}
if(PlotKit.Base.usingPrototype()){
delete _8.extend;
delete _8.from;
delete _8.inspect;
}
return _8;
},uniq:function(_10){
var m=MochiKit.Base;
if(!m.isArrayLike(_10)||(_10.length<1)){
return new Array();
}
var _11=new Array();
var _12=_10[0];
_11.push(_10[0]);
for(var i=1;i<_10.length;i++){
if(m.compare(_10[i],_12)!=0){
_12=_10[i];
_11.push(_10[i]);
}
}
return _11;
},colorScheme:function(){
var mb=MochiKit.Base;
var mc=MochiKit.Color;
var _15=["red","orange","yellow","green","cyan","blue","purple","magenta"];
var _16=function(_17){
return mc.Color[_17+"Color"]();
};
return mb.map(_16,_15);
},baseDarkPrimaryColors:function(){
var _18=MochiKit.Color.Color.fromHexString;
return [_18("#ad3f40"),_18("#ddac2c"),_18("#dfdd0c"),_18("#5276c4"),_18("#739c5a")];
},basePrimaryColors:function(){
var _19=MochiKit.Color.Color.fromHexString;
return [_19("#d24c4d"),_19("#f2b32f"),_19("#ece90e"),_19("#5d83da"),_19("#78a15d")];
},baseBlueColors:function(){
var _20=MochiKit.Color.Color.fromHexString;
return [_20("#4b6b94"),_20("#5d81b4"),_20("#acbad2")];
},palette:function(_21,_22,_23,_24){
var _25=MochiKit.Base.isUndefinedOrNull;
var _26=new Array();
if(_25(_24)){
_24=0.1;
}
if(_25(_23)){
_23=0.4;
}
if(_25(_22)){
_22=-0.2;
}
var _27=_22;
while(_27<=_23){
_26.push(_27);
_27+=_24;
}
var _28=function(_29,_30){
return _29.lighterColorWithLevel(_30);
};
return MochiKit.Base.map(MochiKit.Base.partial(_28,_21),_26);
},excanvasSupported:function(){
if(/MSIE/.test(navigator.userAgent)&&!window.opera){
return true;
}
return false;
},findPosX:function(obj){
var _32=0;
if(obj.offsetParent){
while(obj.offsetParent){
_32+=obj.offsetLeft;
obj=obj.offsetParent;
}
}else{
if(obj.x){
_32+=obj.x;
}
}
return _32;
},findPosY:function(obj){
var _33=0;
if(obj.offsetParent){
while(obj.offsetParent){
_33+=obj.offsetTop;
obj=obj.offsetParent;
}
}else{
if(obj.y){
_33+=obj.y;
}
}
return _33;
},isFuncLike:function(obj){
return (typeof (obj)=="function");
}});
PlotKit.Base.map=function(fn,lst){
if(PlotKit.Base.usingPrototype()){
var _36=[];
for(var x in lst){
if(typeof (lst[x])=="function"){
continue;
}
_36.push(fn(lst[x]));
}
return _36;
}else{
return MochiKit.Base.map(fn,lst);
}
};
PlotKit.Base.items=function(lst){
if(PlotKit.Base.usingPrototype()){
var _38=[];
for(var x in lst){
if(typeof (lst[x])=="function"){
continue;
}
_38.push([x,lst[x]]);
}
return _38;
}else{
return MochiKit.Base.items(lst);
}
};
PlotKit.Base.keys=function(lst){
if(PlotKit.Base.usingPrototype()){
var _39=[];
for(var x in lst){
if(typeof (lst[x])=="function"){
continue;
}
_39.push(x);
}
return _39;
}else{
return MochiKit.Base.keys(lst);
}
};
PlotKit.Base.baseColors=function(){
var _40=MochiKit.Color.Color.fromHexString;
return [_40("#476fb2"),_40("#be2c2b"),_40("#85b730"),_40("#734a99"),_40("#26a1c5"),_40("#fb8707"),_40("#000000")];
};
PlotKit.Base.googleColors=function(){
var _41=MochiKit.Color.Color.fromHexString;
return [_41("#0066dd"),_41("#dc3912"),_41("#ff9900"),_41("#008000"),_41("#4942cc"),_41("#990099")];
};
PlotKit.Base.googleStyle=function(){
var r={"colorScheme":PlotKit.Base.googleColors(),"backgroundColor":MochiKit.Color.Color.whiteColor(),"strokeWidth":2,"axisLineWidth":2,"strokeColor":null,"strokeColorTransform":null,"fillColorTransform":"asTransparent","shouldFill":true};
return r;
};
PlotKit.Base.officeBaseStyle={"axisLineWidth":2,"axisLabelColor":MochiKit.Color.Color.grayColor(),"axisLineColor":MochiKit.Color.Color.whiteColor(),"padding":{top:5,bottom:10,left:30,right:30}};
MochiKit.Base.update(PlotKit.Base,{officeBlue:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[0]),"backgroundColor":PlotKit.Base.baseColors()[0].lighterColorWithLevel(0.45)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeRed:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[1]),"backgroundColor":PlotKit.Base.baseColors()[1].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeGreen:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[2]),"backgroundColor":PlotKit.Base.baseColors()[2].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officePurple:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[3]),"backgroundColor":PlotKit.Base.baseColors()[3].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeCyan:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[4]),"backgroundColor":PlotKit.Base.baseColors()[4].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeOrange:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[5]),"backgroundColor":PlotKit.Base.baseColors()[5].lighterColorWithLevel(0.4)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeBlack:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[6],0,0.6),"backgroundColor":PlotKit.Base.baseColors()[6].lighterColorWithLevel(0.9)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
}});
PlotKit.Base.EXPORT=["baseColors","collapse","colorScheme","findPosX","findPosY","officeBaseStyle","officeBlue","officeRed","officeGreen","officePurple","officeCyan","officeOrange","officeBlack","roundInterval","uniq","isFuncLike","excanvasSupported"];
PlotKit.Base.EXPORT_OK=[];
PlotKit.Base.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.Base.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.Base);
try{
if(typeof (PlotKit.Base)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit.Layout depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.Base";
}
if(typeof (PlotKit.Layout)=="undefined"){
PlotKit.Layout={};
}
PlotKit.Layout.NAME="PlotKit.Layout";
PlotKit.Layout.VERSION=PlotKit.VERSION;
PlotKit.Layout.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.Layout.toString=function(){
return this.__repr__();
};
PlotKit.Layout.valid_styles=["bar","line","pie","point"];
PlotKit.Layout=function(_43,_44){
this.options={"barWidthFillFraction":0.75,"barOrientation":"vertical","xOriginIsZero":true,"yOriginIsZero":true,"xAxis":null,"yAxis":null,"xTicks":null,"yTicks":null,"xNumberOfTicks":10,"yNumberOfTicks":5,"xTickPrecision":1,"yTickPrecision":1,"pieRadius":0.4};
this.style=_43;
MochiKit.Base.update(this.options,_44?_44:{});
if(!MochiKit.Base.isUndefinedOrNull(this.options.xAxis)){
this.minxval=this.options.xAxis[0];
this.maxxval=this.options.xAxis[1];
this.xscale=this.maxxval-this.minxval;
}else{
this.minxval=0;
this.maxxval=null;
this.xscale=null;
}
if(!MochiKit.Base.isUndefinedOrNull(this.options.yAxis)){
this.minyval=this.options.yAxis[0];
this.maxyval=this.options.yAxis[1];
this.yscale=this.maxyval-this.minyval;
}else{
this.minyval=0;
this.maxyval=null;
this.yscale=null;
}
this.bars=new Array();
this.points=new Array();
this.slices=new Array();
this.xticks=new Array();
this.yticks=new Array();
this.datasets=new Array();
this.minxdelta=0;
this.xrange=1;
this.yrange=1;
this.hitTestCache={x2maxy:null};
};
PlotKit.Layout.prototype.addDataset=function(_45,_46){
this.datasets[_45]=_46;
};
PlotKit.Layout.prototype.removeDataset=function(_47,_48){
delete this.datasets[_47];
};
PlotKit.Layout.prototype.addDatasetFromTable=function(_49,_50,_51,_52,_53){
var _54=MochiKit.Base.isUndefinedOrNull;
var _55=MochiKit.DOM.scrapeText;
var _56=MochiKit.Format.strip;
if(_54(_51)){
_51=0;
}
if(_54(_52)){
_52=1;
}
if(_54(_53)){
_53=-1;
}
var _57=_50.tBodies[0].rows;
var _58=new Array();
var _59=new Array();
if(!_54(_57)){
for(var i=0;i<_57.length;i++){
_58.push([parseFloat(_56(_55(_57[i].cells[_51]))),parseFloat(_56(_55(_57[i].cells[_52])))]);
if(_53>=0){
_59.push({v:parseFloat(_56(_55(_57[i].cells[_51]))),label:_56(_55(_57[i].cells[_53]))});
}
}
this.addDataset(_49,_58);
if(_53>=0){
this.options.xTicks=_59;
}
return true;
}
return false;
};
PlotKit.Layout.prototype.evaluate=function(){
this._evaluateLimits();
this._evaluateScales();
if(this.style=="bar"){
if(this.options.barOrientation=="horizontal"){
this._evaluateHorizBarCharts();
}else{
this._evaluateBarCharts();
}
this._evaluateBarTicks();
}else{
if(this.style=="line"||this.style=="point"){
this._evaluateLineCharts();
this._evaluateLineTicks();
}else{
if(this.style=="pie"){
this._evaluatePieCharts();
this._evaluatePieTicks();
}
}
}
};
PlotKit.Layout.prototype.hitTest=function(x,y){
var f=MochiKit.Format.twoDigitFloat;
if((this.style=="bar")&&this.bars&&(this.bars.length>0)){
for(var i=0;i<this.bars.length;i++){
var bar=this.bars[i];
if((x>=bar.x)&&(x<=bar.x+bar.w)&&(y>=bar.y)&&(y-bar.y<=bar.h)){
return bar;
}
}
}else{
if(this.style=="line"){
if(this.hitTestCache.x2maxy==null){
this._regenerateHitTestCache();
}
var _63=x/this.xscale;
var _64=this.hitTestCache.xvalues;
var _65=null;
var _66=null;
for(var i=1;i<_64.length;i++){
if(_64[i]>_63){
_65=_64[i-1];
_66=_64[i];
break;
}
}
if((_65!=null)){
var _67=this.hitTestCache.x2maxy[_65];
var _68=this.hitTestCache.x2maxy[_66];
var _69=(1-y)/this.yscale;
var _70=(_68-_67)/(_66-_65);
var _71=_67+_70*(_63-_65);
if(_71>=_69){
var obj={xval:_63,yval:_69,xafter:_66,yafter:_68,xbefore:_65,ybefore:_67,yprojected:_71};
return obj;
}
}
}else{
if(this.style=="pie"){
x=2*x-0.5;
var _72=Math.sqrt((y-0.5)*(y-0.5)+(x-0.5)*(x-0.5));
if(_72>this.options.pieRadius){
return null;
}
var _73=0;
if(y<0.5&&x<0.5){
_73=Math.atan2(y-0.5,x-0.5)+5*Math.PI/2;
}else{
_73=Math.atan2(y-0.5,x-0.5)+Math.PI/2;
}
for(var i=0;i<this.slices.length;i++){
var _74=this.slices[i];
if(_74.startAngle<_73&&_74.endAngle>=_73){
return _74;
}
}
}
}
}
return null;
};
PlotKit.Layout.prototype.rectForX=function(x){
return null;
};
PlotKit.Layout.prototype.angleRangeForX=function(x){
return null;
};
PlotKit.Layout.prototype._evaluateLimits=function(){
var map=PlotKit.Base.map;
var _76=PlotKit.Base.items;
var _77=MochiKit.Base.itemgetter;
var _78=PlotKit.Base.collapse;
var _79=MochiKit.Base.listMin;
var _80=MochiKit.Base.listMax;
var _81=MochiKit.Base.isUndefinedOrNull;
var all=_78(map(_77(1),_76(this.datasets)));
if(_81(this.options.xAxis)){
if(this.options.xOriginIsZero){
this.minxval=0;
}else{
this.minxval=_79(map(parseFloat,map(_77(0),all)));
}
this.maxxval=_80(map(parseFloat,map(_77(0),all)));
}else{
this.minxval=this.options.xAxis[0];
this.maxxval=this.options.xAxis[1];
this.xscale=this.maxval-this.minxval;
}
if(_81(this.options.yAxis)){
if(this.options.yOriginIsZero){
this.minyval=0;
}else{
this.minyval=_79(map(parseFloat,map(_77(1),all)));
}
this.maxyval=_80(map(parseFloat,map(_77(1),all)));
}else{
this.minyval=this.options.yAxis[0];
this.maxyval=this.options.yAxis[1];
this.yscale=this.maxyval-this.minyval;
}
};
PlotKit.Layout.prototype._evaluateScales=function(){
var _83=MochiKit.Base.isUndefinedOrNull;
this.xrange=this.maxxval-this.minxval;
if(this.xrange==0){
this.xscale=1;
}else{
this.xscale=1/this.xrange;
}
this.yrange=this.maxyval-this.minyval;
if(this.yrange==0){
this.yscale=1;
}else{
this.yscale=1/this.yrange;
}
};
PlotKit.Layout.prototype._uniqueXValues=function(){
var _84=PlotKit.Base.collapse;
var map=PlotKit.Base.map;
var _85=PlotKit.Base.uniq;
var _86=MochiKit.Base.itemgetter;
var _87=PlotKit.Base.items;
var _88=map(parseFloat,map(_86(0),_84(map(_86(1),_87(this.datasets)))));
_88.sort(MochiKit.Base.compare);
return _85(_88);
};
PlotKit.Layout.prototype._evaluateBarCharts=function(){
var _89=PlotKit.Base.items;
var _90=_89(this.datasets).length;
var _91=10000000;
var _92=this._uniqueXValues();
for(var i=1;i<_92.length;i++){
_91=Math.min(Math.abs(_92[i]-_92[i-1]),_91);
}
var _93=0;
var _94=0;
var _95=0;
if(_92.length==1){
_91=1;
this.xscale=1;
this.minxval=_92[0];
_93=1*this.options.barWidthFillFraction;
_94=_93/_90;
_95=(1-this.options.barWidthFillFraction)/2;
}else{
if(this.xrange==1){
this.xscale=0.5;
}else{
if(this.xrange==2){
this.xscale=1/3;
}else{
this.xscale=(1-_91/this.xrange)/this.xrange;
}
}
_93=_91*this.xscale*this.options.barWidthFillFraction;
_94=_93/_90;
_95=_91*this.xscale*(1-this.options.barWidthFillFraction)/2;
}
this.minxdelta=_91;
this.bars=new Array();
var i=0;
for(var _96 in this.datasets){
var _97=this.datasets[_96];
if(PlotKit.Base.isFuncLike(_97)){
continue;
}
for(var j=0;j<_97.length;j++){
var _99=_97[j];
var rect={x:((parseFloat(_99[0])-this.minxval)*this.xscale)+(i*_94)+_95,y:1-((parseFloat(_99[1])-this.minyval)*this.yscale),w:_94,h:((parseFloat(_99[1])-this.minyval)*this.yscale),xval:parseFloat(_99[0]),yval:parseFloat(_99[1]),name:_96};
if((rect.x>=0)&&(rect.x<=1)&&(rect.y>=0)&&(rect.y<=1)){
this.bars.push(rect);
}
}
i++;
}
};
PlotKit.Layout.prototype._evaluateHorizBarCharts=function(){
var _101=PlotKit.Base.items;
var _102=_101(this.datasets).length;
var _103=10000000;
var _104=this._uniqueXValues();
for(var i=1;i<_104.length;i++){
_103=Math.min(Math.abs(_104[i]-_104[i-1]),_103);
}
var _105=0;
var _106=0;
var _107=0;
if(_104.length==1){
_103=1;
this.xscale=1;
this.minxval=_104[0];
_105=1*this.options.barWidthFillFraction;
_106=_105/_102;
_107=(1-this.options.barWidthFillFraction)/2;
}else{
this.xscale=(1-_103/this.xrange)/this.xrange;
_105=_103*this.xscale*this.options.barWidthFillFraction;
_106=_105/_102;
_107=_103*this.xscale*(1-this.options.barWidthFillFraction)/2;
}
this.minxdelta=_103;
this.bars=new Array();
var i=0;
for(var _108 in this.datasets){
var _109=this.datasets[_108];
if(PlotKit.Base.isFuncLike(_109)){
continue;
}
for(var j=0;j<_109.length;j++){
var item=_109[j];
var rect={y:((parseFloat(item[0])-this.minxval)*this.xscale)+(i*_106)+_107,x:0,h:_106,w:((parseFloat(item[1])-this.minyval)*this.yscale),xval:parseFloat(item[0]),yval:parseFloat(item[1]),name:_108};
if(rect.y<=0){
rect.y=0;
}
if(rect.y>=1){
rect.y=1;
}
if((rect.x>=0)&&(rect.x<=1)){
this.bars.push(rect);
}
}
i++;
}
};
PlotKit.Layout.prototype._evaluateLineCharts=function(){
var _111=PlotKit.Base.items;
var _112=_111(this.datasets).length;
this.points=new Array();
var i=0;
for(var _113 in this.datasets){
var _114=this.datasets[_113];
if(PlotKit.Base.isFuncLike(_114)){
continue;
}
_114.sort(function(a,b){
return MochiKit.Base.compare(parseFloat(a[0]),parseFloat(b[0]));
});
for(var j=0;j<_114.length;j++){
var item=_114[j];
var _117={x:((parseFloat(item[0])-this.minxval)*this.xscale),y:1-((parseFloat(item[1])-this.minyval)*this.yscale),xval:parseFloat(item[0]),yval:parseFloat(item[1]),name:_113};
if(_117.y<=0){
_117.y=0;
}
if(_117.y>=1){
_117.y=1;
}
if((_117.x>=0)&&(_117.x<=1)){
this.points.push(_117);
}
}
i++;
}
};
PlotKit.Layout.prototype._evaluatePieCharts=function(){
var map=PlotKit.Base.map;
var _118=PlotKit.Base.items;
var sum=MochiKit.Iter.sum;
var _120=MochiKit.Base.itemgetter;
var _121=_118(this.datasets).length;
var _122=_118(this.datasets)[0][1];
var _123=sum(map(_120(1),_122));
this.slices=new Array();
var _124=0;
for(var i=0;i<_122.length;i++){
var _125=_122[i][1]/_123;
var _126=_124*Math.PI*2;
var _127=(_124+_125)*Math.PI*2;
var _128={fraction:_125,xval:_122[i][0],yval:_122[i][1],startAngle:_126,endAngle:_127};
if(_122[i][1]!=0){
this.slices.push(_128);
}
_124+=_125;
}
};
PlotKit.Layout.prototype._evaluateLineTicksForXAxis=function(){
var _129=MochiKit.Base.isUndefinedOrNull;
if(this.options.xTicks){
this.xticks=new Array();
var _130=function(tick){
var _132=tick.label;
if(_129(_132)){
_132=tick.v.toString();
}
var pos=this.xscale*(tick.v-this.minxval);
if((pos>=0)&&(pos<=1)){
this.xticks.push([pos,_132]);
}
};
MochiKit.Iter.forEach(this.options.xTicks,MochiKit.Base.bind(_130,this));
}else{
if(this.options.xNumberOfTicks){
var _134=this._uniqueXValues();
var _135=this.xrange/this.options.xNumberOfTicks;
var _136=0;
this.xticks=new Array();
for(var i=0;i<=_134.length;i++){
if((_134[i]-this.minxval)>=(_136*_135)){
var pos=this.xscale*(_134[i]-this.minxval);
if((pos>1)||(pos<0)){
continue;
}
this.xticks.push([pos,_134[i]]);
_136++;
}
if(_136>this.options.xNumberOfTicks){
break;
}
}
}
}
};
PlotKit.Layout.prototype._evaluateLineTicksForYAxis=function(){
var _137=MochiKit.Base.isUndefinedOrNull;
if(this.options.yTicks){
this.yticks=new Array();
var _138=function(tick){
var _139=tick.label;
if(_137(_139)){
_139=tick.v.toString();
}
var pos=1-(this.yscale*(tick.v-this.minyval));
if((pos>=0)&&(pos<=1)){
this.yticks.push([pos,_139]);
}
};
MochiKit.Iter.forEach(this.options.yTicks,MochiKit.Base.bind(_138,this));
}else{
if(this.options.yNumberOfTicks){
this.yticks=new Array();
var _140=PlotKit.Base.roundInterval;
var prec=this.options.yTickPrecision;
var _142=_140(this.yrange,this.options.yNumberOfTicks,prec);
for(var i=0;i<=this.options.yNumberOfTicks;i++){
var yval=this.minyval+(i*_142);
var pos=1-((yval-this.minyval)*this.yscale);
if((pos>1)||(pos<0)){
continue;
}
this.yticks.push([pos,MochiKit.Format.roundToFixed(yval,prec)]);
}
}
}
};
PlotKit.Layout.prototype._evaluateLineTicks=function(){
this._evaluateLineTicksForXAxis();
this._evaluateLineTicksForYAxis();
};
PlotKit.Layout.prototype._evaluateBarTicks=function(){
this._evaluateLineTicks();
var _144=function(tick){
return [tick[0]+(this.minxdelta*this.xscale)/2,tick[1]];
};
this.xticks=MochiKit.Base.map(MochiKit.Base.bind(_144,this),this.xticks);
if(this.options.barOrientation=="horizontal"){
var _145=this.xticks;
this.xticks=this.yticks;
this.yticks=_145;
var _146=function(tick){
return [1-tick[0],tick[1]];
};
this.xticks=MochiKit.Base.map(_146,this.xticks);
}
};
PlotKit.Layout.prototype._evaluatePieTicks=function(){
var _147=MochiKit.Base.isUndefinedOrNull;
var _148=MochiKit.Format.numberFormatter("#%");
this.xticks=new Array();
if(this.options.xTicks){
var _149=new Array();
for(var i=0;i<this.slices.length;i++){
_149[this.slices[i].xval]=this.slices[i];
}
for(var i=0;i<this.options.xTicks.length;i++){
var tick=this.options.xTicks[i];
var _150=_149[tick.v];
var _151=tick.label;
if(_150){
if(_147(_151)){
_151=tick.v.toString();
}
_151=MochiKit.DOM.SPAN(null,_151," ("+_148(_150.fraction)+")");
this.xticks.push([tick.v,_151]);
}
}
}else{
for(var i=0;i<this.slices.length;i++){
var _150=this.slices[i];
var _151=_150.xval+" ("+_148(_150.fraction)+")";
this.xticks.push([_150.xval,_151]);
}
}
};
PlotKit.Layout.prototype._regenerateHitTestCache=function(){
this.hitTestCache.xvalues=this._uniqueXValues();
this.hitTestCache.xlookup=new Array();
this.hitTestCache.x2maxy=new Array();
var _152=MochiKit.Base.listMax;
var _153=MochiKit.Base.itemgetter;
var map=MochiKit.Base.map;
var keys=MochiKit.Base.keys;
var _155=keys(this.datasets);
for(var i=0;i<_155.length;i++){
var _156=this.datasets[_155[i]];
for(var j=0;j<_156.length;j++){
var xval=_156[j][0];
var yval=_156[j][1];
if(this.hitTestCache.xlookup[xval]){
this.hitTestCache.xlookup[xval].push([yval,_155[i]]);
}else{
this.hitTestCache.xlookup[xval]=[[yval,_155[i]]];
}
}
}
for(var x in this.hitTestCache.xlookup){
var _158=this.hitTestCache.xlookup[x];
this.hitTestCache.x2maxy[x]=_152(map(_153(0),_158));
}
};
PlotKit.LayoutModule={};
PlotKit.LayoutModule.Layout=PlotKit.Layout;
PlotKit.LayoutModule.EXPORT=["Layout"];
PlotKit.LayoutModule.EXPORT_OK=[];
PlotKit.LayoutModule.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.LayoutModule.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.LayoutModule);
try{
if((typeof (PlotKit.Base)=="undefined")||(typeof (PlotKit.Layout)=="undefined")){
throw "";
}
}
catch(e){
throw "PlotKit.Layout depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.{Base,Layout}";
}
if(typeof (PlotKit.CanvasRenderer)=="undefined"){
PlotKit.CanvasRenderer={};
}
PlotKit.CanvasRenderer.NAME="PlotKit.CanvasRenderer";
PlotKit.CanvasRenderer.VERSION=PlotKit.VERSION;
PlotKit.CanvasRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.CanvasRenderer.toString=function(){
return this.__repr__();
};
PlotKit.CanvasRenderer=function(_159,_160,_161){
if(arguments.length>0){
this.__init__(_159,_160,_161);
}
};
PlotKit.CanvasRenderer.prototype.__init__=function(_162,_163,_164){
var _165=MochiKit.Base.isUndefinedOrNull;
var _166=MochiKit.Color.Color;
this.options={"drawBackground":true,"backgroundColor":_166.whiteColor(),"padding":{left:30,right:30,top:5,bottom:10},"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[0]),"strokeColor":_166.whiteColor(),"strokeColorTransform":"asStrokeColor","strokeWidth":0.5,"fillColorTransform":null,"shouldFill":true,"shouldStroke":true,"drawXAxis":true,"drawYAxis":true,"axisLineColor":_166.blackColor(),"axisLineWidth":0.5,"axisTickSize":3,"axisLabelColor":_166.blackColor(),"axisLabelFont":"Arial","axisLabelFontSize":9,"axisLabelWidth":50,"pieRadius":0.4,"enableEvents":true};
MochiKit.Base.update(this.options,_164?_164:{});
this.layout=_163;
this.element=MochiKit.DOM.getElement(_162);
this.container=this.element.parentNode;
this.isIE=PlotKit.Base.excanvasSupported();
if(this.isIE&&!_165(G_vmlCanvasManager)){
this.IEDelay=0.5;
this.maxTries=5;
this.renderDelay=null;
this.clearDelay=null;
this.element=G_vmlCanvasManager.initElement(this.element);
}
this.height=MochiKit.DOM.elementDimensions(this.element).h;
this.width=MochiKit.DOM.elementDimensions(this.element).w;
this.element.width=this.width;
this.element.height=this.height;
if(_165(this.element)){
throw "CanvasRenderer() - passed canvas is not found";
}
if(!this.isIE&&!(PlotKit.CanvasRenderer.isSupported(this.element))){
throw "CanvasRenderer() - Canvas is not supported.";
}
if(_165(this.container)||(this.container.nodeName.toLowerCase()!="div")){
throw "CanvasRenderer() - <canvas> needs to be enclosed in <div>";
}
this.xlabels=new Array();
this.ylabels=new Array();
this.isFirstRender=true;
this.area={x:this.options.padding.left,y:this.options.padding.top,w:this.width-this.options.padding.left-this.options.padding.right,h:this.height-this.options.padding.top-this.options.padding.bottom};
MochiKit.DOM.updateNodeAttributes(this.container,{"style":{"position":"relative","width":this.width+"px"}});
try{
this.event_isinside=null;
if(MochiKit.Signal&&this.options.enableEvents){
this._initialiseEvents();
}
}
catch(e){
}
};
PlotKit.CanvasRenderer.prototype.render=function(){
if(this.isIE){
try{
if(this.renderDelay){
this.renderDelay.cancel();
this.renderDelay=null;
}
var _167=this.element.getContext("2d");
}
catch(e){
this.isFirstRender=false;
if(this.maxTries-->0){
this.renderDelay=MochiKit.Async.wait(this.IEDelay);
this.renderDelay.addCallback(MochiKit.Base.bind(this.render,this));
}
return;
}
}
if(this.options.drawBackground){
this._renderBackground();
}
if(this.layout.style=="bar"){
this._renderBarChart();
this._renderBarAxis();
}else{
if(this.layout.style=="pie"){
this._renderPieChart();
this._renderPieAxis();
}else{
if(this.layout.style=="line"){
this._renderLineChart();
this._renderLineAxis();
}else{
if(this.layout.style=="point"){
this._renderLineAxis();
this._renderPointChart();
}
}
}
}
};
PlotKit.CanvasRenderer.prototype._renderBarChartWrap=function(data,_169){
var _170=this.element.getContext("2d");
var _171=this.options.colorScheme.length;
var _172=this.options.colorScheme;
var _173=MochiKit.Base.keys(this.layout.datasets);
var _174=_173.length;
for(var i=0;i<_174;i++){
var _175=_173[i];
var _176=_172[i%_171];
_170.save();
if(this.options.fillColorTransform&&_176[this.options.fillColorTransform]){
_170.fillStyle=_176[this.options.fillColorTransform]().toRGBString();
}else{
_170.fillStyle=_176.toRGBString();
}
if(this.options.strokeColor){
_170.strokeStyle=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_170.strokeStyle=_176[this.options.strokeColorTransform]().toRGBString();
}else{
_170.strokeStyle=_176.toRGBString();
}
}
_170.lineWidth=this.options.strokeWidth;
var _177=function(obj){
if(obj.name==_175){
_169(_170,obj);
}
};
MochiKit.Iter.forEach(data,MochiKit.Base.bind(_177,this));
_170.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _179=function(_180,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
if((w<1)||(h<1)){
return;
}
if(this.options.shouldFill){
_180.fillRect(x,y,w,h);
}
if(this.options.shouldStroke){
_180.strokeRect(x,y,w,h);
}
};
this._renderBarChartWrap(this.layout.bars,bind(_179,this));
};
PlotKit.CanvasRenderer.prototype._renderLineChart=function(){
var _183=this.element.getContext("2d");
var _184=this.options.colorScheme.length;
var _185=this.options.colorScheme;
var _186=MochiKit.Base.keys(this.layout.datasets);
var _187=_186.length;
var bind=MochiKit.Base.bind;
var _188=MochiKit.Base.partial;
for(var i=0;i<_187;i++){
var _189=_186[i];
var _190=_185[i%_184];
var _191=this.options.strokeColorTransform;
_183.save();
if(this.options.fillColorTransform&&_190[this.options.fillColorTransform]){
_183.fillStyle=_190[this.options.fillColorTransform]().toRGBString();
}else{
_183.fillStyle=_190.toRGBString();
}
if(this.options.strokeColor){
_183.strokeStyle=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_183.strokeStyle=_190[this.options.strokeColorTransform]().toRGBString();
}else{
_183.strokeStyle=_190.toRGBString();
}
}
_183.lineWidth=this.options.strokeWidth;
var _192=function(ctx){
ctx.beginPath();
ctx.moveTo(this.area.x,this.area.y+this.area.h);
var _194=function(ctx_,_196){
if(_196.name==_189){
ctx_.lineTo(this.area.w*_196.x+this.area.x,this.area.h*_196.y+this.area.y);
}
};
MochiKit.Iter.forEach(this.layout.points,_188(_194,ctx),this);
if(this.options.shouldFill){
ctx.lineTo(this.area.w+this.area.x,this.area.h+this.area.y);
ctx.lineTo(this.area.x,this.area.y+this.area.h);
ctx.closePath();
}
};
if(this.options.shouldFill){
bind(_192,this)(_183);
_183.fill();
}
if(this.options.shouldStroke){
bind(_192,this)(_183);
_183.stroke();
}
_183.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderPieChart=function(){
var _197=this.element.getContext("2d");
var _198=this.options.colorScheme.length;
var _199=this.layout.slices;
var _200=this.area.x+this.area.w*0.5;
var _201=this.area.y+this.area.h*0.5;
var _202=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
if(this.isIE){
_200=parseInt(_200);
_201=parseInt(_201);
_202=parseInt(_202);
}
for(var i=0;i<_199.length;i++){
var _203=this.options.colorScheme[i%_198];
_197.save();
if(this.options.fillColorTransform&&_203[this.options.fillColorTransform]){
_197.fillStyle=_203[this.options.fillColorTransform]().toRGBString();
}else{
_197.fillStyle=_203.toRGBString();
}
var _204=function(){
_197.beginPath();
_197.moveTo(_200,_201);
_197.arc(_200,_201,_202,_199[i].startAngle-Math.PI/2,_199[i].endAngle-Math.PI/2,false);
_197.lineTo(_200,_201);
_197.closePath();
};
if(Math.abs(_199[i].startAngle-_199[i].endAngle)>0.001){
if(this.options.shouldFill){
_204();
_197.fill();
}
if(this.options.shouldStroke){
_204();
_197.lineWidth=this.options.strokeWidth;
if(this.options.strokeColor){
_197.strokeStyle=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_197.strokeStyle=_203[this.options.strokeColorTransform]().toRGBString();
}else{
_197.strokeStyle=_203.toRGBString();
}
}
_197.stroke();
}
}
_197.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderPointChart=function(){
var _205=this.element.getContext("2d");
var _206=this.options.colorScheme.length;
var _207=this.options.colorScheme;
var _208=MochiKit.Base.keys(this.layout.datasets);
var _209=_208.length;
var bind=MochiKit.Base.bind;
var _210=MochiKit.Base.partial;
for(var i=0;i<_209;i++){
var _211=_208[i];
var _212=_207[i%_206];
var _213=this.options.strokeColorTransform;
_205.save();
if(this.options.fillColorTransform&&_212[this.options.fillColorTransform]){
_205.fillStyle=_212[this.options.fillColorTransform]().toRGBString();
}else{
_205.fillStyle=_212.toRGBString();
}
if(this.options.strokeColor){
_205.strokeStyle=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_205.strokeStyle=_212[this.options.strokeColorTransform]().toRGBString();
}else{
_205.strokeStyle=_212.toRGBString();
}
}
_205.lineWidth=this.options.strokeWidth;
var _214=function(ctx,_215){
if(_215.name==_211){
ctx.beginPath();
ctx.arc(this.area.w*_215.x+this.area.x,this.area.h*_215.y+this.area.y,this.area.h/50,0,2*Math.PI,false);
ctx.closePath();
if(this.options.shouldFill){
ctx.fill();
}
if(this.options.shouldStroke){
ctx.stroke();
}
}
};
MochiKit.Iter.forEach(this.layout.points,bind(_214,this,_205));
_205.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderBarAxis=function(){
this._renderAxis();
};
PlotKit.CanvasRenderer.prototype._renderLineAxis=function(){
this._renderAxis();
};
PlotKit.CanvasRenderer.prototype._renderAxis=function(){
if(!this.options.drawXAxis&&!this.options.drawYAxis){
return;
}
var DIV=MochiKit.DOM.DIV;
var _217=this.element.getContext("2d");
var _218={"style":{"position":"absolute","fontSize":this.options.axisLabelFontSize+"px","zIndex":10,"color":this.options.axisLabelColor.toRGBString(),"width":this.options.axisLabelWidth+"px","overflow":"hidden"}};
_217.save();
_217.strokeStyle=this.options.axisLineColor.toRGBString();
_217.lineWidth=this.options.axisLineWidth;
if(this.options.drawYAxis){
if(this.layout.yticks){
var _219=function(tick){
if(typeof (tick)=="function"){
return;
}
var x=this.area.x;
var y=this.area.y+tick[0]*this.area.h;
_217.beginPath();
_217.moveTo(x,y);
_217.lineTo(x-this.options.axisTickSize,y);
_217.closePath();
_217.stroke();
var _220=DIV(_218,tick[1]);
_220.style.top=(y-this.options.axisLabelFontSize)+"px";
_220.style.left=(x-this.options.padding.left-this.options.axisTickSize)+"px";
_220.style.textAlign="right";
_220.style.width=(this.options.padding.left-this.options.axisTickSize*2)+"px";
MochiKit.DOM.appendChildNodes(this.container,_220);
this.ylabels.push(_220);
};
MochiKit.Iter.forEach(this.layout.yticks,MochiKit.Base.bind(_219,this));
}
_217.beginPath();
_217.moveTo(this.area.x,this.area.y);
_217.lineTo(this.area.x,this.area.y+this.area.h);
_217.closePath();
_217.stroke();
}
if(this.options.drawXAxis){
if(this.layout.xticks){
var _219=function(tick){
if(typeof (dataset)=="function"){
return;
}
var x=this.area.x+tick[0]*this.area.w;
var y=this.area.y+this.area.h;
_217.beginPath();
_217.moveTo(x,y);
_217.lineTo(x,y+this.options.axisTickSize);
_217.closePath();
_217.stroke();
var _221=DIV(_218,tick[1]);
_221.style.top=(y+this.options.axisTickSize)+"px";
_221.style.left=(x-this.options.axisLabelWidth/2)+"px";
_221.style.textAlign="center";
_221.style.width=this.options.axisLabelWidth+"px";
MochiKit.DOM.appendChildNodes(this.container,_221);
this.xlabels.push(_221);
};
MochiKit.Iter.forEach(this.layout.xticks,MochiKit.Base.bind(_219,this));
}
_217.beginPath();
_217.moveTo(this.area.x,this.area.y+this.area.h);
_217.lineTo(this.area.x+this.area.w,this.area.y+this.area.h);
_217.closePath();
_217.stroke();
}
_217.restore();
};
PlotKit.CanvasRenderer.prototype._renderPieAxis=function(){
if(!this.options.drawXAxis){
return;
}
if(this.layout.xticks){
var _222=new Array();
for(var i=0;i<this.layout.slices.length;i++){
_222[this.layout.slices[i].xval]=this.layout.slices[i];
}
var _223=this.area.x+this.area.w*0.5;
var _224=this.area.y+this.area.h*0.5;
var _225=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
var _226=this.options.axisLabelWidth;
for(var i=0;i<this.layout.xticks.length;i++){
var _227=_222[this.layout.xticks[i][0]];
if(MochiKit.Base.isUndefinedOrNull(_227)){
continue;
}
var _228=(_227.startAngle+_227.endAngle)/2;
var _229=_228;
if(_229>Math.PI*2){
_229=_229-Math.PI*2;
}else{
if(_229<0){
_229=_229+Math.PI*2;
}
}
var _230=_223+Math.sin(_229)*(_225+10);
var _231=_224-Math.cos(_229)*(_225+10);
var _232={"position":"absolute","zIndex":11,"width":_226+"px","fontSize":this.options.axisLabelFontSize+"px","overflow":"hidden","color":this.options.axisLabelColor.toHexString()};
if(_229<=Math.PI*0.5){
_232["textAlign"]="left";
_232["verticalAlign"]="top";
_232["left"]=_230+"px";
_232["top"]=(_231-this.options.axisLabelFontSize)+"px";
}else{
if((_229>Math.PI*0.5)&&(_229<=Math.PI)){
_232["textAlign"]="left";
_232["verticalAlign"]="bottom";
_232["left"]=_230+"px";
_232["top"]=_231+"px";
}else{
if((_229>Math.PI)&&(_229<=Math.PI*1.5)){
_232["textAlign"]="right";
_232["verticalAlign"]="bottom";
_232["left"]=(_230-_226)+"px";
_232["top"]=_231+"px";
}else{
_232["textAlign"]="right";
_232["verticalAlign"]="bottom";
_232["left"]=(_230-_226)+"px";
_232["top"]=(_231-this.options.axisLabelFontSize)+"px";
}
}
}
var _233=MochiKit.DOM.DIV({"style":_232},this.layout.xticks[i][1]);
this.xlabels.push(_233);
MochiKit.DOM.appendChildNodes(this.container,_233);
}
}
};
PlotKit.CanvasRenderer.prototype._renderBackground=function(){
var _234=this.element.getContext("2d");
_234.save();
_234.fillStyle=this.options.backgroundColor.toRGBString();
_234.fillRect(0,0,this.width,this.height);
_234.restore();
};
PlotKit.CanvasRenderer.prototype.clear=function(){
if(this.isIE){
try{
if(this.clearDelay){
this.clearDelay.cancel();
this.clearDelay=null;
}
var _235=this.element.getContext("2d");
}
catch(e){
this.isFirstRender=false;
this.clearDelay=MochiKit.Async.wait(this.IEDelay);
this.clearDelay.addCallback(MochiKit.Base.bind(this.clear,this));
return;
}
}
var _235=this.element.getContext("2d");
_235.clearRect(0,0,this.width,this.height);
MochiKit.Iter.forEach(this.xlabels,MochiKit.DOM.removeElement);
MochiKit.Iter.forEach(this.ylabels,MochiKit.DOM.removeElement);
this.xlabels=new Array();
this.ylabels=new Array();
};
PlotKit.CanvasRenderer.prototype._initialiseEvents=function(){
var _236=MochiKit.Signal.connect;
var bind=MochiKit.Base.bind;
_236(this.element,"onclick",bind(this.onclick,this));
};
PlotKit.CanvasRenderer.prototype._resolveObject=function(e){
var x=(e.mouse().page.x-PlotKit.Base.findPosX(this.element)-this.area.x)/this.area.w;
var y=(e.mouse().page.y-PlotKit.Base.findPosY(this.element)-this.area.y)/this.area.h;
var _238=this.layout.hitTest(x,y);
if(_238){
return _238;
}
return null;
};
PlotKit.CanvasRenderer.prototype._createEventObject=function(_239,e){
if(_239==null){
return null;
}
e.chart=_239;
return e;
};
PlotKit.CanvasRenderer.prototype.onclick=function(e){
var _240=this._resolveObject(e);
var _241=this._createEventObject(_240,e);
if(_241!=null){
MochiKit.Signal.signal(this,"onclick",_241);
}
};
PlotKit.CanvasRenderer.prototype.onmouseover=function(e){
var _242=this._resolveObject(e);
var _243=this._createEventObject(_242,e);
if(_243!=null){
MochiKit.Signal.signal(this,"onmouseover",_243);
}
};
PlotKit.CanvasRenderer.prototype.onmouseout=function(e){
var _244=this._resolveObject(e);
var _245=this._createEventObject(_244,e);
if(_245==null){
MochiKit.Signal.signal(this,"onmouseout",e);
}else{
MochiKit.Signal.signal(this,"onmouseout",_245);
}
};
PlotKit.CanvasRenderer.prototype.onmousemove=function(e){
var _246=this._resolveObject(e);
var _247=this._createEventObject(_246,e);
if((_246==null)&&(this.event_isinside==null)){
return;
}
if((_246!=null)&&(this.event_isinside==null)){
MochiKit.Signal.signal(this,"onmouseover",_247);
}
if((_246==null)&&(this.event_isinside!=null)){
MochiKit.Signal.signal(this,"onmouseout",_247);
}
if((_246!=null)&&(this.event_isinside!=null)){
MochiKit.Signal.signal(this,"onmousemove",_247);
}
this.event_isinside=_246;
};
PlotKit.CanvasRenderer.isSupported=function(_248){
var _249=null;
try{
if(MochiKit.Base.isUndefinedOrNull(_248)){
_249=MochiKit.DOM.CANVAS({});
}else{
_249=MochiKit.DOM.getElement(_248);
}
var _250=_249.getContext("2d");
}
catch(e){
var ie=navigator.appVersion.match(/MSIE (\d\.\d)/);
var _252=(navigator.userAgent.toLowerCase().indexOf("opera")!=-1);
if((!ie)||(ie[1]<6)||(_252)){
return false;
}
return true;
}
return true;
};
PlotKit.Canvas={};
PlotKit.Canvas.CanvasRenderer=PlotKit.CanvasRenderer;
PlotKit.Canvas.EXPORT=["CanvasRenderer"];
PlotKit.Canvas.EXPORT_OK=["CanvasRenderer"];
PlotKit.Canvas.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.Canvas.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.Canvas);
try{
if(typeof (PlotKit.Layout)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.Layout";
}
PlotKit.SVGRenderer=function(_253,_254,_255){
if(arguments.length>0){
this.__init__(_253,_254,_255);
}
};
PlotKit.SVGRenderer.NAME="PlotKit.SVGRenderer";
PlotKit.SVGRenderer.VERSION=PlotKit.VERSION;
PlotKit.SVGRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.SVGRenderer.toString=function(){
return this.__repr__();
};
PlotKit.SVGRenderer.SVGNS="http://www.w3.org/2000/svg";
PlotKit.SVGRenderer.prototype.__init__=function(_256,_257,_258){
var _259=MochiKit.Base.isUndefinedOrNull;
this.options={"drawBackground":true,"backgroundColor":Color.whiteColor(),"padding":{left:30,right:30,top:5,bottom:10},"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[1]),"strokeColor":Color.whiteColor(),"strokeColorTransform":"asStrokeColor","strokeWidth":0.5,"shouldFill":true,"shouldStroke":true,"drawXAxis":true,"drawYAxis":true,"axisLineColor":Color.blackColor(),"axisLineWidth":0.5,"axisTickSize":3,"axisLabelColor":Color.blackColor(),"axisLabelFont":"Arial","axisLabelFontSize":9,"axisLabelWidth":50,"axisLabelUseDiv":true,"pieRadius":0.4,"enableEvents":true};
MochiKit.Base.update(this.options,_258?_258:{});
this.layout=_257;
this.element=MochiKit.DOM.getElement(_256);
this.container=this.element.parentNode;
this.height=parseInt(this.element.getAttribute("height"));
this.width=parseInt(this.element.getAttribute("width"));
this.document=document;
this.root=this.element;
try{
this.document=this.element.getSVGDocument();
this.root=_259(this.document.documentElement)?this.element:this.document.documentElement;
}
catch(e){
}
this.element.style.zIndex=1;
if(_259(this.element)){
throw "SVGRenderer() - passed SVG object is not found";
}
if(_259(this.container)||this.container.nodeName.toLowerCase()!="div"){
throw "SVGRenderer() - No DIV's around the SVG.";
}
this.xlabels=new Array();
this.ylabels=new Array();
this.defs=this.createSVGElement("defs");
this.area={x:this.options.padding.left,y:this.options.padding.top,w:this.width-this.options.padding.left-this.options.padding.right,h:this.height-this.options.padding.top-this.options.padding.bottom};
MochiKit.DOM.updateNodeAttributes(this.container,{"style":{"position":"relative","width":this.width+"px"}});
};
PlotKit.SVGRenderer.prototype.render=function(){
if(this.options.drawBackground){
this._renderBackground();
}
if(this.layout.style=="bar"){
this._renderBarChart();
this._renderBarAxis();
}else{
if(this.layout.style=="pie"){
this._renderPieChart();
this._renderPieAxis();
}else{
if(this.layout.style=="line"){
this._renderLineChart();
this._renderLineAxis();
}
}
}
};
PlotKit.SVGRenderer.prototype._renderBarOrLine=function(data,_260,_261,_262){
var _263=this.options.colorScheme.length;
var _264=this.options.colorScheme;
var _265=MochiKit.Base.keys(this.layout.datasets);
var _266=_265.length;
for(var i=0;i<_266;i++){
var _267=_265[i];
var _268=new Array();
var _269=_264[i%_263];
if(this.options.shouldFill){
_268["fill"]=_269.toRGBString();
}else{
_268["fill"]="none";
}
if(this.options.shouldStroke&&(this.options.strokeColor||this.options.strokeColorTransform)){
if(this.options.strokeColor){
_268["stroke"]=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_268["stroke"]=_269[this.options.strokeColorTransform]().toRGBString();
}
}
_268["strokeWidth"]=this.options.strokeWidth;
}
if(_261){
_261(_268);
}
var _270=function(obj){
if(obj.name==_267){
_260(_268,obj);
}
};
MochiKit.Iter.forEach(data,MochiKit.Base.bind(_270,this));
if(_262){
_262(_268);
}
}
};
PlotKit.SVGRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _271=function(_272,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
this._drawRect(x,y,w,h,_272);
};
this._renderBarOrLine(this.layout.bars,bind(_271,this));
};
PlotKit.SVGRenderer.prototype._renderLineChart=function(){
var bind=MochiKit.Base.bind;
var _273=function(_274,_275){
this._tempPointsBuffer+=(this.area.w*_275.x+this.area.x)+","+(this.area.h*_275.y+this.area.y)+" ";
};
var _276=function(_277){
this._tempPointsBuffer="";
this._tempPointsBuffer+=(this.area.x)+","+(this.area.y+this.area.h)+" ";
};
var _278=function(_279){
this._tempPointsBuffer+=(this.area.w+this.area.x)+","+(this.area.h+this.area.y);
_279["points"]=this._tempPointsBuffer;
var elem=this.createSVGElement("polygon",_279);
this.root.appendChild(elem);
};
this._renderBarOrLine(this.layout.points,bind(_273,this),bind(_276,this),bind(_278,this));
};
PlotKit.SVGRenderer.prototype._renderPieChart=function(){
var _281=this.options.colorScheme.length;
var _282=this.layout.slices;
var _283=this.area.x+this.area.w*0.5;
var _284=this.area.y+this.area.h*0.5;
var _285=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
if(_282.length==1&&(Math.abs(_282[0].startAngle)-Math.abs(_282[0].endAngle)<0.1)){
var _286={"cx":_283,"cy":_284,"r":_285};
var _287=this.options.colorScheme[0];
if(this.options.shouldFill){
_286["fill"]=_287.toRGBString();
}else{
_286["fill"]="none";
}
if(this.options.shouldStroke&&(this.options.strokeColor||this.options.strokeColorTransform)){
if(this.options.strokeColor){
_286["stroke"]=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_286["stroke"]=_287[this.options.strokeColorTransform]().toRGBString();
}
}
_286["style"]="stroke-width: "+this.options.strokeWidth;
}
this.root.appendChild(this.createSVGElement("circle",_286));
return;
}
for(var i=0;i<_282.length;i++){
var _286=new Array();
var _287=this.options.colorScheme[i%_281];
if(this.options.shouldFill){
_286["fill"]=_287.toRGBString();
}else{
_286["fill"]="none";
}
if(this.options.shouldStroke&&(this.options.strokeColor||this.options.strokeColorTransform)){
if(this.options.strokeColor){
_286["stroke"]=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_286["stroke"]=_287[this.options.strokeColorTransform]().toRGBString();
}
}
_286["style"]="stroke-width:"+this.options.strokeWidth;
}
var _288=0;
if(Math.abs(_282[i].endAngle-_282[i].startAngle)>Math.PI){
_288=1;
}
var x1=Math.cos(_282[i].startAngle-Math.PI/2)*_285;
var y1=Math.sin(_282[i].startAngle-Math.PI/2)*_285;
var x2=Math.cos(_282[i].endAngle-Math.PI/2)*_285;
var y2=Math.sin(_282[i].endAngle-Math.PI/2)*_285;
var rx=x2-x1;
var ry=y2-y1;
var _295="M"+_283+","+_284+" ";
_295+="l"+x1+","+y1+" ";
_295+="a"+_285+","+_285+" 0 "+_288+",1 "+rx+","+ry+" z";
_286["d"]=_295;
var elem=this.createSVGElement("path",_286);
this.root.appendChild(elem);
}
};
PlotKit.SVGRenderer.prototype._renderBarAxis=function(){
this._renderAxis();
};
PlotKit.SVGRenderer.prototype._renderLineAxis=function(){
this._renderAxis();
};
PlotKit.SVGRenderer.prototype._renderAxis=function(){
if(!this.options.drawXAxis&&!this.options.drawYAxis){
return;
}
var _296={"style":{"position":"absolute","textAlign":"center","fontSize":this.options.axisLabelFontSize+"px","zIndex":10,"color":this.options.axisLabelColor.toRGBString(),"width":this.options.axisLabelWidth+"px","overflow":"hidden"}};
var _297={"stroke":this.options.axisLineColor.toRGBString(),"strokeWidth":this.options.axisLineWidth};
if(this.options.drawYAxis){
if(this.layout.yticks){
var _298=function(tick){
var x=this.area.x;
var y=this.area.y+tick[0]*this.area.h;
this._drawLine(x,y,x-3,y,_297);
if(this.options.axisLabelUseDiv){
var _299=MochiKit.DOM.DIV(_296,tick[1]);
_299.style.top=(y-this.options.axisLabelFontSize)+"px";
_299.style.left=(x-this.options.padding.left+this.options.axisTickSize)+"px";
_299.style.textAlign="left";
_299.style.width=(this.options.padding.left-3)+"px";
MochiKit.DOM.appendChildNodes(this.container,_299);
this.ylabels.push(_299);
}else{
var _300={y:y+3,x:(x-this.options.padding.left+3),width:(this.options.padding.left-this.options.axisTickSize)+"px",height:(this.options.axisLabelFontSize+3)+"px",fontFamily:"Arial",fontSize:this.options.axisLabelFontSize+"px",fill:this.options.axisLabelColor.toRGBString()};
var _299=this.createSVGElement("text",_300);
_299.appendChild(this.document.createTextNode(tick[1]));
this.root.appendChild(_299);
}
};
MochiKit.Iter.forEach(this.layout.yticks,MochiKit.Base.bind(_298,this));
}
this._drawLine(this.area.x,this.area.y,this.area.x,this.area.y+this.area.h,_297);
}
if(this.options.drawXAxis){
if(this.layout.xticks){
var _298=function(tick){
var x=this.area.x+tick[0]*this.area.w;
var y=this.area.y+this.area.h;
this._drawLine(x,y,x,y+this.options.axisTickSize,_297);
if(this.options.axisLabelUseDiv){
var _301=MochiKit.DOM.DIV(_296,tick[1]);
_301.style.top=(y+this.options.axisTickSize)+"px";
_301.style.left=(x-this.options.axisLabelWidth/2)+"px";
_301.style.textAlign="center";
_301.style.width=this.options.axisLabelWidth+"px";
MochiKit.DOM.appendChildNodes(this.container,_301);
this.xlabels.push(_301);
}else{
var _302={y:(y+this.options.axisTickSize+this.options.axisLabelFontSize),x:x-3,width:this.options.axisLabelWidth+"px",height:(this.options.axisLabelFontSize+3)+"px",fontFamily:"Arial",fontSize:this.options.axisLabelFontSize+"px",fill:this.options.axisLabelColor.toRGBString(),textAnchor:"middle"};
var _301=this.createSVGElement("text",_302);
_301.appendChild(this.document.createTextNode(tick[1]));
this.root.appendChild(_301);
}
};
MochiKit.Iter.forEach(this.layout.xticks,MochiKit.Base.bind(_298,this));
}
this._drawLine(this.area.x,this.area.y+this.area.h,this.area.x+this.area.w,this.area.y+this.area.h,_297);
}
};
PlotKit.SVGRenderer.prototype._renderPieAxis=function(){
if(this.layout.xticks){
var _303=new Array();
for(var i=0;i<this.layout.slices.length;i++){
_303[this.layout.slices[i].xval]=this.layout.slices[i];
}
var _304=this.area.x+this.area.w*0.5;
var _305=this.area.y+this.area.h*0.5;
var _306=Math.min(this.area.w*this.options.pieRadius+10,this.area.h*this.options.pieRadius+10);
var _307=this.options.axisLabelWidth;
for(var i=0;i<this.layout.xticks.length;i++){
var _308=_303[this.layout.xticks[i][0]];
if(MochiKit.Base.isUndefinedOrNull(_308)){
continue;
}
var _309=(_308.startAngle+_308.endAngle)/2;
var _310=_309;
if(_310>Math.PI*2){
_310=_310-Math.PI*2;
}else{
if(_310<0){
_310=_310+Math.PI*2;
}
}
var _311=_304+Math.sin(_310)*(_306+10);
var _312=_305-Math.cos(_310)*(_306+10);
var _313={"position":"absolute","zIndex":11,"width":_307+"px","fontSize":this.options.axisLabelFontSize+"px","overflow":"hidden","color":this.options.axisLabelColor.toHexString()};
var _314={"width":_307+"px","fontSize":this.options.axisLabelFontSize+"px","height":(this.options.axisLabelFontSize+3)+"px","fill":this.options.axisLabelColor.toRGBString()};
if(_310<=Math.PI*0.5){
MochiKit.Base.update(_313,{"textAlign":"left","verticalAlign":"top","left":_311+"px","top":(_312-this.options.axisLabelFontSize)+"px"});
MochiKit.Base.update(_314,{"x":_311,"y":(_312-this.options.axisLabelFontSize),"textAnchor":"left"});
}else{
if((_310>Math.PI*0.5)&&(_310<=Math.PI)){
MochiKit.Base.update(_313,{"textAlign":"left","verticalAlign":"bottom","left":_311+"px","top":_312+"px"});
MochiKit.Base.update(_314,{"textAnchor":"left","x":_311,"y":_312});
}else{
if((_310>Math.PI)&&(_310<=Math.PI*1.5)){
MochiKit.Base.update(_313,{"textAlign":"right","verticalAlign":"bottom","left":_311+"px","top":_312+"px"});
MochiKit.Base.update(_314,{"textAnchor":"right","x":_311-_307,"y":_312});
}else{
MochiKit.Base.update(_313,{"textAlign":"left","verticalAlign":"bottom","left":_311+"px","top":_312+"px"});
MochiKit.Base.update(_314,{"textAnchor":"left","x":_311-_307,"y":_312-this.options.axisLabelFontSize});
}
}
}
if(this.options.axisLabelUseDiv){
var _315=MochiKit.DOM.DIV({"style":_313},this.layout.xticks[i][1]);
this.xlabels.push(_315);
MochiKit.DOM.appendChildNodes(this.container,_315);
}else{
var _315=this.createSVGElement("text",_314);
_315.appendChild(this.document.createTextNode(this.layout.xticks[i][1]));
this.root.appendChild(_315);
}
}
}
};
PlotKit.SVGRenderer.prototype._renderBackground=function(){
var opts={"stroke":"none","fill":this.options.backgroundColor.toRGBString()};
this._drawRect(0,0,this.width,this.height,opts);
};
PlotKit.SVGRenderer.prototype._drawRect=function(x,y,w,h,_317){
var _318={x:x+"px",y:y+"px",width:w+"px",height:h+"px"};
if(_317){
MochiKit.Base.update(_318,_317);
}
var elem=this.createSVGElement("rect",_318);
this.root.appendChild(elem);
};
PlotKit.SVGRenderer.prototype._drawLine=function(x1,y1,x2,y2,_319){
var _320={x1:x1+"px",y1:y1+"px",x2:x2+"px",y2:y2+"px"};
if(_319){
MochiKit.Base.update(_320,_319);
}
var elem=this.createSVGElement("line",_320);
this.root.appendChild(elem);
};
PlotKit.SVGRenderer.prototype.clear=function(){
while(this.element.firstChild){
this.element.removeChild(this.element.firstChild);
}
if(this.options.axisLabelUseDiv){
for(var i=0;i<this.xlabels.length;i++){
MochiKit.DOM.removeElement(this.xlabels[i]);
}
for(var i=0;i<this.ylabels.length;i++){
MochiKit.DOM.removeElement(this.ylabels[i]);
}
}
this.xlabels=new Array();
this.ylabels=new Array();
};
PlotKit.SVGRenderer.prototype.createSVGElement=function(name,_322){
var _323=MochiKit.Base.isUndefinedOrNull;
var elem;
var doc=_323(this.document)?document:this.document;
try{
elem=doc.createElementNS(PlotKit.SVGRenderer.SVGNS,name);
}
catch(e){
elem=doc.createElement(name);
elem.setAttribute("xmlns",PlotKit.SVGRenderer.SVGNS);
}
if(_322){
MochiKit.DOM.updateNodeAttributes(elem,_322);
}
return elem;
};
PlotKit.SVGRenderer.SVG=function(_325){
var ie=navigator.appVersion.match(/MSIE (\d\.\d)/);
var _326=(navigator.userAgent.toLowerCase().indexOf("opera")!=-1);
if(ie&&(ie[1]>=6)&&(!_326)){
var _327=_325["width"]?_325["width"]:"100";
var _328=_325["height"]?_325["height"]:"100";
var eid=_325["id"]?_325["id"]:"notunique";
var html="<svg:svg width=\""+_327+"\" height=\""+_328+"\" ";
html+="id=\""+eid+"\" version=\"1.1\" baseProfile=\"full\" />";
var _331=document.createElement(html);
var _332=_331.getSVGDocument().createElementNS(PlotKit.SVGRenderer.SVGNS,"svg");
_332.setAttribute("width",_327);
_332.setAttribute("height",_328);
_331.getSVGDocument().appendChild(_332);
return _331;
}else{
return PlotKit.SVGRenderer.prototype.createSVGElement("svg",_325);
}
};
PlotKit.SVGRenderer.isSupported=function(){
var _333=(navigator.userAgent.toLowerCase().indexOf("opera")!=-1);
var _334=navigator.appVersion.match(/MSIE (\d\.\d)/);
var _335=navigator.userAgent.match(/AppleWebKit\/(\d+)/);
var _336=navigator.userAgent.match(/Opera\/(\d*\.\d*)/);
var _337=navigator.userAgent.match(/rv:(\d*\.\d*).*Gecko/);
var _338="http://www.w3.org/TR/SVG11/feature#SVG";
if(_334&&(_334[1]>=6)&&!_333){
return document.implementation.hasFeature(_338,"1.1");
}
if(_336&&(_336[1]>8.9)){
return true;
}
if(_337&&(_337>1.7)){
return true;
}
return false;
};
PlotKit.SVG={};
PlotKit.SVG.SVGRenderer=PlotKit.SVGRenderer;
PlotKit.SVG.EXPORT=["SVGRenderer"];
PlotKit.SVG.EXPORT_OK=["SVGRenderer"];
PlotKit.SVG.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.SVG.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.SVG);
try{
if(typeof (PlotKit.CanvasRenderer)=="undefined"){
throw "";
}
}
catch(e){
throw "SweetCanvas depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.{Layout, Canvas}";
}
if(typeof (PlotKit.SweetCanvasRenderer)=="undefined"){
PlotKit.SweetCanvasRenderer={};
}
PlotKit.SweetCanvasRenderer=function(_339,_340,_341){
if(arguments.length>0){
this.__init__(_339,_340,_341);
}
};
PlotKit.SweetCanvasRenderer.NAME="PlotKit.SweetCanvasRenderer";
PlotKit.SweetCanvasRenderer.VERSION=PlotKit.VERSION;
PlotKit.SweetCanvasRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.SweetCanvasRenderer.toString=function(){
return this.__repr__();
};
PlotKit.SweetCanvasRenderer.prototype=new PlotKit.CanvasRenderer();
PlotKit.SweetCanvasRenderer.prototype.constructor=PlotKit.SweetCanvasRenderer;
PlotKit.SweetCanvasRenderer.__super__=PlotKit.CanvasRenderer.prototype;
PlotKit.SweetCanvasRenderer.prototype.__init__=function(el,_343,opts){
var _344=PlotKit.Base.officeBlue();
MochiKit.Base.update(_344,opts);
PlotKit.SweetCanvasRenderer.__super__.__init__.call(this,el,_343,_344);
};
PlotKit.SweetCanvasRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _345=MochiKit.Color.Color.blackColor().colorWithAlpha(0.1).toRGBString();
var _346=function(_347,x,y,w,h){
_347.fillStyle=_345;
_347.fillRect(x-2,y-2,w+4,h+2);
_347.fillStyle=_345;
_347.fillRect(x-1,y-1,w+2,h+1);
};
var _348=this.options.colorScheme.length;
var _349=this.options.colorScheme;
var _350=PlotKit.Base.keys(this.layout.datasets);
var _351=_350.length;
var _352=function(name){
for(var i=0;i<_351;i++){
if(name==_350[i]){
return _349[i%_348];
}
}
return _349[0];
};
var _353=function(_354,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
if((w<1)||(h<1)){
return;
}
_354.save();
_354.shadowBlur=5;
_354.shadowColor=MochiKit.Color.Color.fromHexString("#888888").toRGBString();
if(this.isIE){
_354.save();
_354.fillStyle="#cccccc";
_354.fillRect(x-2,y-2,w+4,h+2);
_354.restore();
}else{
_346(_354,x,y,w,h);
}
if(this.options.shouldFill){
_354.fillStyle=_352(bar.name).toRGBString();
_354.fillRect(x,y,w,h);
}
_354.shadowBlur=0;
_354.strokeStyle=MochiKit.Color.Color.whiteColor().toRGBString();
_354.lineWidth=2;
if(this.options.shouldStroke){
_354.strokeRect(x,y,w,h);
}
_354.restore();
};
this._renderBarChartWrap(this.layout.bars,bind(_353,this));
};
PlotKit.SweetCanvasRenderer.prototype._renderLineChart=function(){
var _355=this.element.getContext("2d");
var _356=this.options.colorScheme.length;
var _357=this.options.colorScheme;
var _358=PlotKit.Base.keys(this.layout.datasets);
var _359=_358.length;
var bind=MochiKit.Base.bind;
var _360=MochiKit.Base.partial;
for(var i=0;i<_359;i++){
var _361=_358[i];
var _362=_357[i%_356];
var _363=this.options.strokeColorTransform;
_355.save();
var _364=function(ctx){
ctx.beginPath();
ctx.moveTo(this.area.x,this.area.y+this.area.h);
var _365=function(ctx_,_366){
if(_366.name==_361){
ctx_.lineTo(this.area.w*_366.x+this.area.x,this.area.h*_366.y+this.area.y);
}
};
MochiKit.Iter.forEach(this.layout.points,_360(_365,ctx),this);
ctx.lineTo(this.area.w+this.area.x,this.area.h+this.area.y);
ctx.lineTo(this.area.x,this.area.y+this.area.h);
ctx.closePath();
};
if(this.options.shouldFill){
_355.save();
if(this.isIE){
_355.fillStyle="#cccccc";
}else{
_355.fillStyle=MochiKit.Color.Color.blackColor().colorWithAlpha(0.2).toRGBString();
}
_355.translate(-1,-2);
bind(_364,this)(_355);
if(this.options.shouldFill){
_355.fill();
}
_355.restore();
}
_355.shadowBlur=5;
_355.shadowColor=MochiKit.Color.Color.fromHexString("#888888").toRGBString();
_355.fillStyle=_362.toRGBString();
_355.lineWidth=2;
_355.strokeStyle=MochiKit.Color.Color.whiteColor().toRGBString();
if(this.options.shouldFill){
bind(_364,this)(_355);
_355.fill();
}
if(this.options.shouldStroke){
bind(_364,this)(_355);
_355.stroke();
}
_355.restore();
}
};
PlotKit.SweetCanvasRenderer.prototype._renderPieChart=function(){
var _367=this.element.getContext("2d");
var _368=this.options.colorScheme.length;
var _369=this.layout.slices;
var _370=this.area.x+this.area.w*0.5;
var _371=this.area.y+this.area.h*0.5;
var _372=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
if(this.isIE){
_370=parseInt(_370);
_371=parseInt(_371);
_372=parseInt(_372);
}
if(!this.isIE){
_367.save();
var _373=MochiKit.Color.Color.blackColor().colorWithAlpha(0.2);
_367.fillStyle=_373.toRGBString();
_367.shadowBlur=5;
_367.shadowColor=MochiKit.Color.Color.fromHexString("#888888").toRGBString();
_367.translate(1,1);
_367.beginPath();
_367.moveTo(_370,_371);
_367.arc(_370,_371,_372+2,0,Math.PI*2,false);
_367.closePath();
_367.fill();
_367.restore();
}
_367.save();
_367.strokeStyle=MochiKit.Color.Color.whiteColor().toRGBString();
_367.lineWidth=2;
for(var i=0;i<_369.length;i++){
var _374=this.options.colorScheme[i%_368];
_367.fillStyle=_374.toRGBString();
var _375=function(){
_367.beginPath();
_367.moveTo(_370,_371);
_367.arc(_370,_371,_372,_369[i].startAngle-Math.PI/2,_369[i].endAngle-Math.PI/2,_369[i].fraction==1);
_367.lineTo(_370,_371);
_367.closePath();
};
if(Math.abs(_369[i].startAngle-_369[i].endAngle)>0.0001){
if(this.options.shouldFill){
_375();
_367.fill();
}
if(this.options.shouldStroke){
_375();
_367.stroke();
}
}
}
_367.restore();
};
PlotKit.CanvasRenderer.prototype._renderPointChart=function(){
var _376=this.element.getContext("2d");
var _377=this.options.colorScheme.length;
var _378=this.options.colorScheme;
var _379=MochiKit.Base.keys(this.layout.datasets);
var _380=_379.length;
var bind=MochiKit.Base.bind;
var _381=MochiKit.Base.partial;
for(var i=0;i<_380;i++){
var _382=_379[i];
var _383=_378[i%_377];
var _384=this.options.strokeColorTransform;
_376.save();
if(this.options.fillColorTransform&&_383[this.options.fillColorTransform]){
_376.fillStyle=_383[this.options.fillColorTransform]().toRGBString();
}else{
_376.fillStyle=_383.toRGBString();
}
if(this.options.strokeColor){
_376.strokeStyle=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_376.strokeStyle=_383[this.options.strokeColorTransform]().toRGBString();
}else{
_376.strokeStyle=_383.toRGBString();
}
}
_376.lineWidth=this.options.strokeWidth;
var _385=function(ctx,_386){
if(_386.name==_382){
ctx.beginPath();
ctx.arc(this.area.w*_386.x+this.area.x,this.area.h*_386.y+this.area.y,this.area.h/75,0,2*Math.PI,false);
ctx.closePath();
if(this.options.shouldFill){
ctx.fill();
}
if(this.options.shouldStroke){
ctx.stroke();
}
}
};
if(this.options.shouldFill){
_376.save();
if(this.isIE){
_376.fillStyle="#cccccc";
}else{
_376.fillStyle=MochiKit.Color.Color.blackColor().colorWithAlpha(0.2).toRGBString();
}
_376.translate(3,4);
MochiKit.Iter.forEach(this.layout.points,bind(_385,this,_376));
_376.restore();
}
_376.shadowBlur=5;
_376.shadowColor=MochiKit.Color.Color.fromHexString("#888888").toRGBString();
_376.fillStyle=_383.toRGBString();
_376.lineWidth=2;
_376.strokeStyle=MochiKit.Color.Color.whiteColor().toRGBString();
MochiKit.Iter.forEach(this.layout.points,bind(_385,this,_376));
_376.restore();
}
};
PlotKit.SweetCanvasRenderer.prototype._renderBackground=function(){
var _387=this.element.getContext("2d");
if(this.layout.style=="bar"||this.layout.style=="line"||this.layout.style=="point"){
_387.save();
_387.fillStyle=this.options.backgroundColor.toRGBString();
_387.fillRect(this.area.x,this.area.y,this.area.w,this.area.h);
_387.strokeStyle=this.options.axisLineColor.toRGBString();
_387.lineWidth=1;
var _388=this.layout.yticks;
var _389=false;
if(this.layout.style=="bar"&&this.layout.options.barOrientation=="horizontal"){
_388=this.layout.xticks;
_389=true;
}
for(var i=0;i<_388.length;i++){
var x1=0;
var y1=0;
var x2=0;
var y2=0;
if(_389){
x1=_388[i][0]*this.area.w+this.area.x;
y1=this.area.y;
x2=x1;
y2=y1+this.area.h;
}else{
x1=this.area.x;
y1=_388[i][0]*this.area.h+this.area.y;
x2=x1+this.area.w;
y2=y1;
}
_387.beginPath();
_387.moveTo(x1,y1);
_387.lineTo(x2,y2);
_387.closePath();
_387.stroke();
}
_387.restore();
}else{
PlotKit.SweetCanvasRenderer.__super__._renderBackground.call(this);
}
};
PlotKit.SweetCanvas={};
PlotKit.SweetCanvas.SweetCanvasRenderer=PlotKit.SweetCanvasRenderer;
PlotKit.SweetCanvas.EXPORT=["SweetCanvasRenderer"];
PlotKit.SweetCanvas.EXPORT_OK=["SweetCanvasRenderer"];
PlotKit.SweetCanvas.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.SweetCanvas.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.SweetCanvas);
try{
if(typeof (PlotKit.SVGRenderer)=="undefined"){
throw "";
}
}
catch(e){
throw "SweetSVG depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.{Layout, SVG}";
}
if(typeof (PlotKit.SweetSVGRenderer)=="undefined"){
PlotKit.SweetSVGRenderer={};
}
PlotKit.SweetSVGRenderer=function(_390,_391,_392){
if(arguments.length>0){
this.__init__(_390,_391,_392);
}
};
PlotKit.SweetSVGRenderer.NAME="PlotKit.SweetSVGRenderer";
PlotKit.SweetSVGRenderer.VERSION=PlotKit.VERSION;
PlotKit.SweetSVGRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.SweetSVGRenderer.toString=function(){
return this.__repr__();
};
PlotKit.SweetSVGRenderer.prototype=new PlotKit.SVGRenderer();
PlotKit.SweetSVGRenderer.prototype.constructor=PlotKit.SweetSVGRenderer;
PlotKit.SweetSVGRenderer.__super__=PlotKit.SVGRenderer.prototype;
PlotKit.SweetSVGRenderer.prototype.__init__=function(_393,_394,_395){
var _396=PlotKit.Base.officeBlue();
MochiKit.Base.update(_396,_395);
PlotKit.SweetSVGRenderer.__super__.__init__.call(this,_393,_394,_396);
};
PlotKit.SweetSVGRenderer.prototype._addDropShadowFilter=function(){
var _397=this.createSVGElement("filter",{x:0,y:0,"id":"dropShadow"});
var _398=this.createSVGElement("feOffset",{"in":"SourceGraphic","dx":0,"dy":0,"result":"topCopy"});
var blur=this.createSVGElement("feGaussianBlur",{"in":"SourceAlpha","StdDeviation":2,"result":"shadow"});
var _400=this.createSVGElement("feOffset",{"in":"shadow","dx":-1,"dy":-2,"result":"movedShadow"});
var _401=this.createSVGElement("feMerge");
var _402=this.createSVGElement("feMergeNode",{"in":"topCopy"});
var _403=this.createSVGElement("feMergeNode",{"in":"movedShadow"});
_401.appendChild(_402);
_401.appendChild(_403);
_397.appendChild(_398);
_397.appendChild(blur);
_397.appendChild(_400);
_397.appendChild(_401);
this.defs.appendChild(_397);
};
PlotKit.SweetSVGRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _404=Color.blackColor().toRGBString();
var _405="fill:"+_404+";fill-opacity:0.15";
var _406="stroke-width: 2.0; stroke:"+Color.whiteColor().toRGBString();
var _407=function(_408,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
if((w<1)||(h<1)){
return;
}
_408["style"]=_406;
this._drawRect(x-2,y-1,w+4,h+2,{"style":_405});
this._drawRect(x,y,w,h,_408);
};
this._renderBarOrLine(this.layout.bars,bind(_407,this));
};
PlotKit.SweetSVGRenderer.prototype._renderLineChart=function(){
var bind=MochiKit.Base.bind;
var _409=Color.blackColor().toRGBString();
var _410="fill:"+_409+";fill-opacity:0.15";
var _411="stroke-width: 2.0; stroke:"+Color.whiteColor().toRGBString();
var _412=function(_413,_414){
this._tempPointsBuffer+=(this.area.w*_414.x+this.area.x)+","+(this.area.h*_414.y+this.area.y)+" ";
};
var _415=function(_416){
this._tempPointsBuffer="";
this._tempPointsBuffer+=(this.area.x)+","+(this.area.y+this.area.h)+" ";
};
var _417=function(_418){
this._tempPointsBuffer+=(this.area.w+this.area.x)+","+(this.area.h+this.area.y);
_418["points"]=this._tempPointsBuffer;
_418["stroke"]="none";
_418["transform"]="translate(-2, -1)";
_418["style"]=_410;
var _419=this.createSVGElement("polygon",_418);
this.root.appendChild(_419);
_418["transform"]="";
_418["style"]=_411;
var elem=this.createSVGElement("polygon",_418);
this.root.appendChild(elem);
};
this._renderBarOrLine(this.layout.points,bind(_412,this),bind(_415,this),bind(_417,this));
};
PlotKit.SweetSVGRenderer.prototype._renderPieChart=function(){
var _420=this.area.x+this.area.w*0.5;
var _421=this.area.y+this.area.h*0.5;
var _422=Color.blackColor().toRGBString();
var _423=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
var _424="fill:"+_422+";fill-opacity:0.15";
var _425=this.createSVGElement("circle",{"style":_424,"cx":_420+1,"cy":_421+1,"r":_423+1});
this.root.appendChild(_425);
PlotKit.SweetSVGRenderer.__super__._renderPieChart.call(this);
};
PlotKit.SweetSVGRenderer.prototype._renderBackground=function(){
var _426={"fill":this.options.backgroundColor.toRGBString(),"stroke":"none"};
if(this.layout.style=="bar"||this.layout.style=="line"){
this._drawRect(this.area.x,this.area.y,this.area.w,this.area.h,_426);
var _427=this.layout.yticks;
var _428=false;
if(this.layout.style=="bar"&&this.layout.options.barOrientation=="horizontal"){
_427=this.layout.xticks;
_428=true;
}
for(var i=0;i<_427.length;i++){
var x=0;
var y=0;
var w=0;
var h=0;
if(_428){
x=_427[i][0]*this.area.w+this.area.x;
y=this.area.y;
w=1;
h=this.area.w;
}else{
x=this.area.x;
y=_427[i][0]*this.area.h+this.area.y;
w=this.area.w;
h=1;
}
this._drawRect(x,y,w,h,{"fill":this.options.axisLineColor.toRGBString()});
}
}else{
PlotKit.SweetSVGRenderer.__super__._renderBackground.call(this);
}
};
PlotKit.SweetSVG={};
PlotKit.SweetSVG.SweetSVGRenderer=PlotKit.SweetSVGRenderer;
PlotKit.SweetSVG.EXPORT=["SweetSVGRenderer"];
PlotKit.SweetSVG.EXPORT_OK=["SweetSVGRenderer"];
PlotKit.SweetSVG.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.SweetSVG.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.SweetSVG);
try{
if(typeof (PlotKit.CanvasRenderer)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit.EasyPlot depends on all of PlotKit's components";
}
if(typeof (PlotKit.EasyPlot)=="undefined"){
PlotKit.EasyPlot={};
}
PlotKit.EasyPlot.NAME="PlotKit.EasyPlot";
PlotKit.EasyPlot.VERSION=PlotKit.VERSION;
PlotKit.EasyPlot.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.EasyPlot.toString=function(){
return this.__repr__();
};
PlotKit.EasyPlot=function(_429,_430,_431,_432){
this.layout=new PlotKit.Layout(_429,_430);
this.divElem=_431;
this.width=parseInt(_431.getAttribute("width"));
this.height=parseInt(_431.getAttribute("height"));
this.deferredCount=0;
if(this.width<1){
this.width=this.divElem.width?this.divElem.width:300;
}
if(this.height<1){
this.height=this.divElem.height?this.divElem.height:300;
}
if(MochiKit.Base.isArrayLike(_432)){
for(var i=0;i<_432.length;i++){
if(typeof (_432[i])=="string"){
this.deferredCount++;
var d=MochiKit.Async.doSimpleXMLHttpRequest(_432[i]);
d.addCallback(MochiKit.Base.bind(PlotKit.EasyPlot.onDataLoaded,this));
}else{
if(MochiKit.Base.isArrayLike(_432[i])){
this.layout.addDataset("data-"+i,_432[i]);
}
}
}
}else{
if(!MochiKit.Base.isUndefinedOrNull(_432)){
throw "Passed datasources are not Array like";
}
}
if(CanvasRenderer.isSupported()){
this.element=MochiKit.DOM.CANVAS({"id":this.divElem.getAttribute("id")+"-canvas","width":this.width,"height":this.height},"");
this.divElem.appendChild(this.element);
this.renderer=new SweetCanvasRenderer(this.element,this.layout,_430);
}else{
if(SVGRenderer.isSupported()){
this.element=SVGRenderer.SVG({"id":this.divElem.getAttribute("id")+"-svg","width":this.width,"height":this.height,"version":"1.1","baseProfile":"full"},"");
this.divElem.appendChild(this.element);
this.renderer=new SweetSVGRenderer(this.element,this.layout,_430);
}
}
if((this.deferredCount==0)&&(PlotKit.Base.keys(this.layout.datasets).length>0)){
this.layout.evaluate();
this.renderer.clear();
this.renderer.render();
}
};
PlotKit.EasyPlot.onDataLoaded=function(_434){
var _435=new Array();
var _436=_434.responseText.split("\n");
for(var i=0;i<_436.length;i++){
var _437=MochiKit.Format.strip(_436[i]);
if((_437.length>1)&&(_437.charAt(0)!="#")){
_435.push(_437.split(","));
}
}
this.layout.addDataset("data-ajax-"+this.deferredCount,_435);
this.deferredCount--;
if((this.deferredCount==0)&&(PlotKit.Base.keys(this.layout.datasets).length>0)){
this.layout.evaluate();
this.renderer.clear();
this.renderer.render();
}
};
PlotKit.EasyPlot.prototype.reload=function(){
this.layout.evaluate();
this.renderer.clear();
this.renderer.render();
};
PlotKit.EasyPlotModule={};
PlotKit.EasyPlotModule.EasyPlot=PlotKit.EasyPlot;
PlotKit.EasyPlotModule.EXPORT=["EasyPlot"];
PlotKit.EasyPlotModule.EXPORT_OK=[];
PlotKit.EasyPlotModule.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.EasyPlotModule.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.EasyPlotModule);


