/***

    PlotKit.PlotKit 0.9 : PACKED VERSION

    THIS FILE IS AUTOMATICALLY GENERATED.  If creating patches, please
    diff against the source tree, not this file.

    For more information, <http://www.liquidx.net/plotkit/>.
    
    Copyright (c) 2006. Alastair Tse.

***/

try{
if(typeof (MochiKit.Base)=="undefined"||typeof (MochiKit.DOM)=="undefined"||typeof (MochiKit.Color)=="undefined"||typeof (MochiKit.Format)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit depends on MochiKit.{Base,Color,DOM,Format}";
}
MochiKit.Base.update(MochiKit.Color.Color.prototype,{asFillColor:function(){
return this.lighterColorWithLevel(0.3);
},asStrokeColor:function(){
return this.darkerColorWithLevel(0.1);
},asPointColor:function(){
return this.lighterColorWithLevel(0.1);
}});
if(typeof (PlotKit)=="undefined"){
PlotKit={};
}
PlotKit.NAME="PlotKit";
PlotKit.VERSION="0.8";
PlotKit.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.toString=function(){
return this.__repr__();
};
if(typeof (PlotKit.Base)=="undefined"){
PlotKit.Base={};
}
PlotKit.Base.NAME="PlotKit.Base";
PlotKit.Base.VERSION=PlotKit.VERSION;
PlotKit.Base.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.Base.toString=function(){
return this.__repr__();
};
MochiKit.Base.update(PlotKit.Base,{roundInterval:function(_1,_2,_3){
var _4=MochiKit.Format.roundToFixed;
var _5=_1/_2;
return parseFloat(_4(_5,_3));
},collapse:function(_6){
var m=MochiKit.Base;
var _8=new Array();
for(var i=0;i<_6.length;i++){
_8=m.concat(_8,_6[i]);
}
return _8;
},uniq:function(_10){
var m=MochiKit.Base;
if(!m.isArrayLike(_10)||(_10.length<1)){
return new Array();
}
var _11=new Array();
var _12=_10[0];
_11.push(_10[0]);
for(var i=1;i<_10.length;i++){
if(m.compare(_10[i],_12)!=0){
_12=_10[i];
_11.push(_10[i]);
}
}
return _11;
},colorScheme:function(){
var mb=MochiKit.Base;
var mc=MochiKit.Color;
var _15=["red","orange","yellow","green","cyan","blue","purple","magenta"];
var _16=function(_17){
return mc.Color[_17+"Color"]();
};
return mb.map(_16,_15);
},baseDarkPrimaryColors:function(){
var _18=MochiKit.Color.Color.fromHexString;
return [_18("#ad3f40"),_18("#ddac2c"),_18("#dfdd0c"),_18("#5276c4"),_18("#739c5a")];
},basePrimaryColors:function(){
var _19=MochiKit.Color.Color.fromHexString;
return [_19("#d24c4d"),_19("#f2b32f"),_19("#ece90e"),_19("#5d83da"),_19("#78a15d")];
},baseBlueColors:function(){
var _20=MochiKit.Color.Color.fromHexString;
return [_20("#4b6b94"),_20("#5d81b4"),_20("#acbad2")];
},palette:function(_21,_22,_23,_24){
var _25=MochiKit.Base.isUndefinedOrNull;
var _26=new Array();
if(_25(_24)){
_24=0.1;
}
if(_25(_23)){
_23=0.4;
}
if(_25(_22)){
_22=-0.2;
}
var _27=_22;
while(_27<=_23){
_26.push(_27);
_27+=_24;
}
var _28=function(_29,_30){
return _29.lighterColorWithLevel(_30);
};
return MochiKit.Base.map(partial(_28,_21),_26);
},excanvasSupported:function(){
if(/MSIE/.test(navigator.userAgent)&&!window.opera){
return true;
}
return false;
},findPosX:function(obj){
var _32=0;
if(obj.offsetParent){
while(obj.offsetParent){
_32+=obj.offsetLeft;
obj=obj.offsetParent;
}
}else{
if(obj.x){
_32+=obj.x;
}
}
return _32;
},findPosY:function(obj){
var _33=0;
if(obj.offsetParent){
while(obj.offsetParent){
_33+=obj.offsetTop;
obj=obj.offsetParent;
}
}else{
if(obj.y){
_33+=obj.y;
}
}
return _33;
}});
PlotKit.Base.baseColors=function(){
var _34=MochiKit.Color.Color.fromHexString;
return [_34("#476fb2"),_34("#be2c2b"),_34("#85b730"),_34("#734a99"),_34("#26a1c5"),_34("#fb8707"),_34("#000000")];
};
PlotKit.Base.officeBaseStyle={"axisLineWidth":2,"axisLabelColor":Color.grayColor(),"axisLineColor":Color.whiteColor(),"padding":{top:5,bottom:10,left:30,right:30}};
MochiKit.Base.update(PlotKit.Base,{officeBlue:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[0]),"backgroundColor":PlotKit.Base.baseColors()[0].lighterColorWithLevel(0.45)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeRed:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[1]),"backgroundColor":PlotKit.Base.baseColors()[1].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeGreen:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[2]),"backgroundColor":PlotKit.Base.baseColors()[2].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officePurple:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[3]),"backgroundColor":PlotKit.Base.baseColors()[3].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeCyan:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[4]),"backgroundColor":PlotKit.Base.baseColors()[4].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeOrange:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[5]),"backgroundColor":PlotKit.Base.baseColors()[5].lighterColorWithLevel(0.4)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeBlack:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[6],0,0.6),"backgroundColor":PlotKit.Base.baseColors()[6].lighterColorWithLevel(0.9)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
}});
PlotKit.Base.EXPORT=["baseColors","collapse","colorScheme","findPosX","findPosY","officeBaseStyle","officeBlue","officeRed","officeGreen","officePurple","officeCyan","officeOrange","officeBlack","roundInterval","uniq","excanvasSupported"];
PlotKit.Base.EXPORT_OK=[];
PlotKit.Base.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.Base.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.Base);
try{
if(typeof (PlotKit.Base)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit.Layout depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.Base";
}
if(typeof (PlotKit.Layout)=="undefined"){
PlotKit.Layout={};
}
PlotKit.Layout.NAME="PlotKit.Layout";
PlotKit.Layout.VERSION=PlotKit.VERSION;
PlotKit.Layout.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.Layout.toString=function(){
return this.__repr__();
};
PlotKit.Layout.valid_styles=["bar","line","pie","point"];
PlotKit.Layout=function(_36,_37){
this.options={"barWidthFillFraction":0.75,"xOriginIsZero":true,"yOriginIsZero":true,"xAxis":null,"yAxis":null,"xTicks":null,"yTicks":null,"xNumberOfTicks":10,"yNumberOfTicks":5,"xTickPrecision":1,"yTickPrecision":3,"pieRadius":0.4};
this.style=_36;
MochiKit.Base.update(this.options,_37?_37:{});
if(!MochiKit.Base.isUndefinedOrNull(this.options.xAxis)){
this.minxval=this.options.xAxis[0];
this.maxxval=this.options.xAxis[1];
this.xscale=this.maxxval-this.minxval;
}else{
this.minxval=0;
this.maxxval=null;
this.xscale=null;
}
if(!MochiKit.Base.isUndefinedOrNull(this.options.yAxis)){
this.minyval=this.options.yAxis[0];
this.maxyval=this.options.yAxis[1];
this.yscale=this.maxyval-this.maxymin;
}else{
this.minyval=0;
this.maxyval=null;
this.yscale=null;
}
this.bars=new Array();
this.points=new Array();
this.slices=new Array();
this.xticks=new Array();
this.yticks=new Array();
this.datasets=new Array();
this.minxdelta=0;
this.xrange=1;
this.yrange=1;
this.hitTestCache={x2maxy:null};
};
PlotKit.Layout.prototype.addDataset=function(_38,_39){
this.datasets[_38]=_39;
};
PlotKit.Layout.prototype.removeDataset=function(_40,_41){
this.datasets[_40]=null;
};
PlotKit.Layout.prototype.addDatasetFromTable=function(_42,_43,_44,_45){
var _46=MochiKit.Base.isUndefinedOrNull;
var _47=MochiKit.DOM.scrapeText;
var _48=MochiKit.Format.strip;
if(_46(_44)){
_44=0;
}
if(_46(_45)){
_45=1;
}
var _49=_43.tBodies[0].rows;
var _50=new Array();
if(!_46(_49)){
for(var i=0;i<_49.length;i++){
_50.push([parseFloat(_48(_47(_49[i].cells[_44]))),parseFloat(_48(_47(_49[i].cells[_45])))]);
}
this.addDataset(_42,_50);
return true;
}
return false;
};
PlotKit.Layout.prototype.evaluate=function(){
this._evaluateLimits();
this._evaluateScales();
if(this.style=="bar"){
this._evaluateBarCharts();
this._evaluateBarTicks();
}else{
if(this.style=="line"){
this._evaluateLineCharts();
this._evaluateLineTicks();
}else{
if(this.style=="pie"){
this._evaluatePieCharts();
this._evaluatePieTicks();
}
}
}
};
PlotKit.Layout.prototype.hitTest=function(x,y){
var f=MochiKit.Format.twoDigitFloat;
if((this.style=="bar")&&this.bars&&(this.bars.length>0)){
for(var i=0;i<this.bars.length;i++){
var bar=this.bars[i];
if((x>=bar.x)&&(x<=bar.x+bar.w)&&(y>=bar.y)&&(y-bar.y<=bar.h)){
return bar;
}
}
}else{
if(this.style=="line"){
if(this.hitTestCache.x2maxy==null){
this._regenerateHitTestCache();
}
var _55=x/this.xscale;
var _56=this.hitTestCache.xvalues;
var _57=null;
var _58=null;
for(var i=1;i<_56.length;i++){
if(_56[i]>_55){
_57=_56[i-1];
_58=_56[i];
break;
}
}
if((_57!=null)){
var _59=this.hitTestCache.x2maxy[_57];
var _60=this.hitTestCache.x2maxy[_58];
var _61=(1-y)/this.yscale;
var _62=(_60-_59)/(_58-_57);
var _63=_59+_62*(_55-_57);
if(_63>=_61){
var obj={xval:_55,yval:_61,xafter:_58,yafter:_60,xbefore:_57,ybefore:_59,yprojected:_63};
return obj;
}
}
}else{
if(this.style=="pie"){
var _64=Math.sqrt((y-0.5)*(y-0.5)+(x-0.5)*(x-0.5));
if(_64>this.options.pieRadius){
return null;
}
var _65=Math.atan2(y-0.5,x-0.5)-Math.PI/2;
for(var i=0;i<this.slices.length;i++){
var _66=this.slices[i];
if(_66.startAngle<_65&&_66.endAngle>=_65){
return _66;
}
}
}
}
}
return null;
};
PlotKit.Layout.prototype.rectForX=function(x){
return null;
};
PlotKit.Layout.prototype.angleRangeForX=function(x){
return null;
};
PlotKit.Layout.prototype._evaluateLimits=function(){
var map=MochiKit.Base.map;
var _68=MochiKit.Base.items;
var _69=MochiKit.Base.itemgetter;
var _70=PlotKit.Base.collapse;
var _71=MochiKit.Base.listMin;
var _72=MochiKit.Base.listMax;
var _73=MochiKit.Base.isUndefinedOrNull;
var all=_70(map(_69(1),_68(this.datasets)));
if(_73(this.options.xAxis)){
if(this.options.xOriginIsZero){
this.minxval=0;
}else{
this.minxval=_71(map(parseFloat,map(_69(0),all)));
}
}
if(_73(this.options.yAxis)){
if(this.options.yOriginIsZero){
this.minyval=0;
}else{
this.minyval=_71(map(parseFloat,map(_69(1),all)));
}
}
this.maxxval=_72(map(parseFloat,map(_69(0),all)));
this.maxyval=_72(map(parseFloat,map(_69(1),all)));
};
PlotKit.Layout.prototype._evaluateScales=function(){
var _75=MochiKit.Base.isUndefinedOrNull;
this.xrange=this.maxxval-this.minxval;
if(this.xrange==0){
this.xscale=1;
}else{
this.xscale=1/this.xrange;
}
this.yrange=this.maxyval-this.minyval;
if(this.yrange==0){
this.yscale=1;
}else{
this.yscale=1/this.yrange;
}
};
PlotKit.Layout.prototype._uniqueXValues=function(){
var _76=PlotKit.Base.collapse;
var map=MochiKit.Base.map;
var _77=PlotKit.Base.uniq;
var _78=MochiKit.Base.itemgetter;
var _79=map(parseFloat,map(_78(0),_76(map(_78(1),items(this.datasets)))));
_79.sort(MochiKit.Base.compare);
return _77(_79);
};
PlotKit.Layout.prototype._evaluateBarCharts=function(){
var _80=MochiKit.Base.keys;
var _81=MochiKit.Base.items;
var _82=_80(this.datasets).length;
var _83=10000000;
var _84=this._uniqueXValues();
for(var i=1;i<_84.length;i++){
_83=Math.min(Math.abs(_84[i]-_84[i-1]),_83);
}
var _85=0;
var _86=0;
var _87=0;
if(_84.length==1){
_83=1;
this.xscale=1;
this.minxval=_84[0];
_85=1*this.options.barWidthFillFraction;
_86=_85/_82;
_87=(1-this.options.barWidthFillFraction)/2;
}else{
this.xscale=(1-_83/this.xrange)/this.xrange;
_85=_83*this.xscale*this.options.barWidthFillFraction;
_86=_85/_82;
_87=_83*this.xscale*(1-this.options.barWidthFillFraction)/2;
}
this.minxdelta=_83;
this.bars=new Array();
var i=0;
for(var _88 in this.datasets){
var _89=this.datasets[_88];
for(var j=0;j<_89.length;j++){
var _91=_89[j];
var _92={x:((parseFloat(_91[0])-this.minxval)*this.xscale)+(i*_86)+_87,y:1-((parseFloat(_91[1])-this.minyval)*this.yscale),w:_86,h:((parseFloat(_91[1])-this.minyval)*this.yscale),xval:parseFloat(_91[0]),yval:parseFloat(_91[1]),name:_88};
this.bars.push(_92);
}
i++;
}
};
PlotKit.Layout.prototype._evaluateLineCharts=function(){
var _93=MochiKit.Base.keys;
var _94=MochiKit.Base.items;
var _95=_93(this.datasets).length;
this.points=new Array();
var i=0;
for(var _96 in this.datasets){
var _97=this.datasets[_96];
_97.sort(function(a,b){
return compare(parseFloat(a[0]),parseFloat(b[0]));
});
for(var j=0;j<_97.length;j++){
var item=_97[j];
var _101={x:((parseFloat(item[0])-this.minxval)*this.xscale),y:1-((parseFloat(item[1])-this.minyval)*this.yscale),xval:parseFloat(item[0]),yval:parseFloat(item[1]),name:_96};
this.points.push(_101);
}
i++;
}
};
PlotKit.Layout.prototype._evaluatePieCharts=function(){
var _102=MochiKit.Base.items;
var sum=MochiKit.Iter.sum;
var _104=MochiKit.Base.itemgetter;
var _105=keys(this.datasets).length;
var _106=_102(this.datasets)[0][1];
var _107=sum(map(_104(1),_106));
this.slices=new Array();
var _108=0;
for(var i=0;i<_106.length;i++){
var _109=_106[i][1]/_107;
var _110=_108*Math.PI*2;
var _111=(_108+_109)*Math.PI*2;
var _112={fraction:_109,xval:_106[i][0],yval:_106[i][1],startAngle:_110,endAngle:_111};
this.slices.push(_112);
_108+=_109;
}
};
PlotKit.Layout.prototype._evaluateLineTicksForXAxis=function(){
var _113=MochiKit.Base.isUndefinedOrNull;
if(this.options.xTicks){
this.xticks=new Array();
var _114=function(tick){
var _116=tick.label;
if(_113(_116)){
_116=tick.v.toString();
}
var pos=this.xscale*(tick.v-this.minxval);
this.xticks.push([pos,_116]);
};
MochiKit.Iter.forEach(this.options.xTicks,bind(_114,this));
}else{
if(this.options.xNumberOfTicks){
var _118=this._uniqueXValues();
var _119=this.xrange/this.options.xNumberOfTicks;
var _120=0;
this.xticks=new Array();
for(var i=0;i<=_118.length;i++){
if(_118[i]>=(_120)*_119){
var pos=this.xscale*(_118[i]-this.minxval);
if((pos>1)||(pos<0)){
return;
}
this.xticks.push([pos,_118[i]]);
_120++;
}
if(_120>this.options.xNumberOfTicks){
break;
}
}
}
}
};
PlotKit.Layout.prototype._evaluateLineTicksForYAxis=function(){
var _121=MochiKit.Base.isUndefinedOrNull;
if(this.options.yTicks){
this.yticks=new Array();
var _122=function(tick){
var _123=tick.label;
if(_121(_123)){
_123=tick.v.toString();
}
var pos=1-(this.yscale*(tick.v+this.minxval));
if((pos<0)||(pos>1)){
return;
}
this.yticks.push([pos,_123]);
};
MochiKit.Iter.forEach(this.options.yTicks,bind(_122,this));
}else{
if(this.options.yNumberOfTicks){
this.yticks=new Array();
var _124=PlotKit.Base.roundInterval;
var prec=this.options.yTickPrecision;
var _126=_124(this.yrange,this.options.yNumberOfTicks,this.options.yTickPrecision);
for(var i=0;i<=this.options.yNumberOfTicks;i++){
var yval=this.minyval+(i*_126);
var pos=1-((yval-this.minyval)*this.yscale);
this.yticks.push([pos,MochiKit.Format.roundToFixed(yval,1)]);
}
}
}
};
PlotKit.Layout.prototype._evaluateLineTicks=function(){
this._evaluateLineTicksForXAxis();
this._evaluateLineTicksForYAxis();
};
PlotKit.Layout.prototype._evaluateBarTicks=function(){
this._evaluateLineTicks();
var _128=function(tick){
return [tick[0]+(this.minxdelta*this.xscale)/2,tick[1]];
};
this.xticks=MochiKit.Base.map(bind(_128,this),this.xticks);
};
PlotKit.Layout.prototype._evaluatePieTicks=function(){
var _129=MochiKit.Base.isUndefinedOrNull;
var _130=MochiKit.Format.numberFormatter("#%");
this.xticks=new Array();
if(this.options.xTicks){
var _131=new Array();
for(var i=0;i<this.slices.length;i++){
_131[this.slices[i].xval]=this.slices[i];
}
for(var i=0;i<this.options.xTicks.length;i++){
var tick=this.options.xTicks[i];
var _132=_131[tick.v];
var _133=tick.label;
if(_132){
if(_129(_133)){
_133=tick.v.toString();
}
_133+=" ("+_130(_132.fraction)+")";
this.xticks.push([tick.v,_133]);
}
}
}else{
for(var i=0;i<this.slices.length;i++){
var _132=this.slices[i];
var _133=_132.xval+" ("+_130(_132.fraction)+")";
this.xticks.push([_132.xval,_133]);
}
}
};
PlotKit.Layout.prototype._regenerateHitTestCache=function(){
this.hitTestCache.xvalues=this._uniqueXValues();
this.hitTestCache.xlookup=new Array();
this.hitTestCache.x2maxy=new Array();
var _134=MochiKit.Base.listMax;
var _135=MochiKit.Base.itemgetter;
var map=MochiKit.Base.map;
var _136=keys(this.datasets);
for(var i=0;i<_136.length;i++){
var _137=this.datasets[_136[i]];
for(var j=0;j<_137.length;j++){
var xval=_137[j][0];
var yval=_137[j][1];
if(this.hitTestCache.xlookup[xval]){
this.hitTestCache.xlookup[xval].push([yval,_136[i]]);
}else{
this.hitTestCache.xlookup[xval]=[[yval,_136[i]]];
}
}
}
for(var x in this.hitTestCache.xlookup){
var _139=this.hitTestCache.xlookup[x];
this.hitTestCache.x2maxy[x]=_134(map(_135(0),_139));
}
};
PlotKit.LayoutModule={};
PlotKit.LayoutModule.Layout=PlotKit.Layout;
PlotKit.LayoutModule.EXPORT=["Layout"];
PlotKit.LayoutModule.EXPORT_OK=[];
PlotKit.LayoutModule.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.LayoutModule.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.LayoutModule);
try{
if((typeof (PlotKit.Base)=="undefined")||(typeof (PlotKit.Layout)=="undefined")){
throw "";
}
}
catch(e){
throw "PlotKit.Layout depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.{Base,Layout}";
}
if(typeof (PlotKit.CanvasRenderer)=="undefined"){
PlotKit.CanvasRenderer={};
}
PlotKit.CanvasRenderer.NAME="PlotKit.CanvasRenderer";
PlotKit.CanvasRenderer.VERSION=PlotKit.VERSION;
PlotKit.CanvasRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.CanvasRenderer.toString=function(){
return this.__repr__();
};
PlotKit.CanvasRenderer=function(_140,_141,_142){
if(arguments.length>0){
this.__init__(_140,_141,_142);
}
};
PlotKit.CanvasRenderer.prototype.__init__=function(_143,_144,_145){
var _146=MochiKit.Base.isUndefinedOrNull;
var _147=MochiKit.Color.Color;
this.options={"drawBackground":true,"backgroundColor":_147.whiteColor(),"padding":{left:30,right:30,top:5,bottom:10},"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[0]),"strokeColor":_147.whiteColor(),"strokeColorTransform":"asStrokeColor","strokeWidth":0.5,"shouldFill":true,"shouldStroke":true,"drawXAxis":true,"drawYAxis":true,"axisLineColor":_147.blackColor(),"axisLineWidth":0.5,"axisTickSize":3,"axisLabelColor":_147.blackColor(),"axisLabelFont":"Arial","axisLabelFontSize":9,"axisLabelWidth":50,"pieRadius":0.4,"enableEvents":true};
MochiKit.Base.update(this.options,_145?_145:{});
this.layout=_144;
this.style=_144.style;
this.element=_143;
this.container=this.element.parentNode;
this.isIE=PlotKit.Base.excanvasSupported();
if(this.isIE&&!_146(G_vmlCanvasManager)){
this.IEDelay=0.5;
this.maxTries=5;
this.renderDelay=null;
this.clearDelay=null;
this.element=G_vmlCanvasManager.initElement(this.element);
}
this.height=this.element.height;
this.width=this.element.width;
if(_146(this.element)){
throw "CanvasRenderer() - passed canvas is not found";
}
if(!this.isIE&&!(PlotKit.CanvasRenderer.isSupported(this.element))){
throw "CanvasRenderer() - Canvas is not supported.";
}
if(_146(this.container)||(this.container.nodeName.toLowerCase()!="div")){
throw "CanvasRenderer() - <canvas> needs to be enclosed in <div>";
}
this.xlabels=new Array();
this.ylabels=new Array();
this.isFirstRender=true;
this.area={x:this.options.padding.left,y:this.options.padding.top,w:this.width-this.options.padding.left-this.options.padding.right,h:this.height-this.options.padding.top-this.options.padding.bottom};
MochiKit.DOM.updateNodeAttributes(this.container,{"style":{"position":"relative","width":this.width+"px"}});
try{
this.event_isinside=null;
if(MochiKit.Signal&&this.options.enableEvents){
this._initialiseEvents();
}
}
catch(e){
}
};
PlotKit.CanvasRenderer.prototype.render=function(){
if(this.isIE){
try{
if(this.renderDelay){
this.renderDelay.cancel();
this.renderDelay=null;
}
var _148=this.element.getContext("2d");
}
catch(e){
this.isFirstRender=false;
if(this.maxTries-->0){
this.renderDelay=MochiKit.Async.wait(this.IEDelay);
this.renderDelay.addCallback(bind(this.render,this));
}
return;
}
}
if(this.options.drawBackground){
this._renderBackground();
}
if(this.style=="bar"){
this._renderBarChart();
this._renderBarAxis();
}else{
if(this.style=="pie"){
this._renderPieChart();
this._renderPieAxis();
}else{
if(this.style=="line"){
this._renderLineChart();
this._renderLineAxis();
}
}
}
};
PlotKit.CanvasRenderer.prototype._renderBarChartWrap=function(data,_150){
var _151=this.element.getContext("2d");
var _152=this.options.colorScheme.length;
var _153=this.options.colorScheme;
var _154=MochiKit.Base.keys(this.layout.datasets);
var _155=_154.length;
for(var i=0;i<_155;i++){
var _156=_154[i];
var _157=_153[i%_152];
_151.save();
_151.fillStyle=_157.toRGBString();
if(this.options.strokeColor){
_151.strokeStyle=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_151.strokeStyle=_157[this.options.strokeColorTransform]().toRGBString();
}
}
_151.lineWidth=this.options.strokeWidth;
var _158=function(obj){
if(obj.name==_156){
_150(_151,obj);
}
};
MochiKit.Iter.forEach(data,bind(_158,this));
_151.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _160=function(_161,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
if((w<1)||(h<1)){
return;
}
if(this.options.shouldFill){
_161.fillRect(x,y,w,h);
}
if(this.options.shouldStroke){
_161.strokeRect(x,y,w,h);
}
};
this._renderBarChartWrap(this.layout.bars,bind(_160,this));
};
PlotKit.CanvasRenderer.prototype._renderLineChart=function(){
var _164=this.element.getContext("2d");
var _165=this.options.colorScheme.length;
var _166=this.options.colorScheme;
var _167=MochiKit.Base.keys(this.layout.datasets);
var _168=_167.length;
var bind=MochiKit.Base.bind;
var _169=MochiKit.Base.partial;
for(var i=0;i<_168;i++){
var _170=_167[i];
var _171=_166[i%_165];
var _172=this.options.strokeColorTransform;
_164.save();
_164.fillStyle=_171.toRGBString();
if(this.options.strokeColor){
_164.strokeStyle=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_164.strokeStyle=_171[_172]().toRGBString();
}
}
_164.lineWidth=this.options.strokeWidth;
var _173=function(){
_164.beginPath();
_164.moveTo(this.area.x,this.area.y+this.area.h);
var _174=function(_164,_175){
if(_175.name==_170){
_164.lineTo(this.area.w*_175.x+this.area.x,this.area.h*_175.y+this.area.y);
}
};
MochiKit.Iter.forEach(this.layout.points,_169(_174,context),this);
context.lineTo(this.area.w+this.area.x,this.area.h+this.area.y);
context.lineTo(this.area.x,this.area.y+this.area.h);
context.closePath();
};
if(this.options.shouldFill){
bind(_173,this)();
context.fill();
}
if(this.options.shouldStroke){
bind(_173,this)();
context.stroke();
}
context.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderPieChart=function(){
var _176=this.element.getContext("2d");
var _177=this.options.colorScheme.length;
var _178=this.layout.slices;
var _179=this.area.x+this.area.w*0.5;
var _180=this.area.y+this.area.h*0.5;
var _181=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
if(this.isIE){
_179=parseInt(_179);
_180=parseInt(_180);
_181=parseInt(_181);
}
for(var i=0;i<_178.length;i++){
var _182=this.options.colorScheme[i%_177];
_176.save();
_176.fillStyle=_182.toRGBString();
var _183=function(){
_176.beginPath();
_176.moveTo(_179,_180);
_176.arc(_179,_180,_181,_178[i].startAngle-Math.PI/2,_178[i].endAngle-Math.PI/2,false);
_176.lineTo(_179,_180);
_176.closePath();
};
if(Math.abs(_178[i].startAngle-_178[i].endAngle)>0.001){
if(this.options.shouldFill){
_183();
_176.fill();
}
if(this.options.shouldStroke){
_183();
_176.lineWidth=this.options.strokeWidth;
if(this.options.strokeColor){
_176.strokeStyle=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_176.strokeStyle=_182[this.options.strokeColorTransform]().toRGBString();
}
}
_176.stroke();
}
}
_176.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderBarAxis=function(){
this._renderAxis();
};
PlotKit.CanvasRenderer.prototype._renderLineAxis=function(){
this._renderAxis();
};
PlotKit.CanvasRenderer.prototype._renderAxis=function(){
if(!this.options.drawXAxis&&!this.options.drawYAxis){
return;
}
var _184=this.element.getContext("2d");
var _185={"style":{"position":"absolute","fontSize":this.options.axisLabelFontSize+"px","zIndex":10,"color":this.options.axisLabelColor.toRGBString(),"width":this.options.axisLabelWidth+"px","overflow":"hidden"}};
_184.save();
_184.strokeStyle=this.options.axisLineColor.toRGBString();
_184.lineWidth=this.options.axisLineWidth;
if(this.options.drawYAxis){
if(this.layout.yticks){
var _186=function(tick){
var x=this.area.x;
var y=this.area.y+tick[0]*this.area.h;
_184.beginPath();
_184.moveTo(x,y);
_184.lineTo(x-this.options.axisTickSize,y);
_184.closePath();
_184.stroke();
var _187=DIV(_185,tick[1]);
_187.style.top=(y-this.options.axisLabelFontSize)+"px";
_187.style.left=(x-this.options.padding.left-this.options.axisTickSize)+"px";
_187.style.textAlign="right";
_187.style.width=(this.options.padding.left-this.options.axisTickSize*2)+"px";
MochiKit.DOM.appendChildNodes(this.container,_187);
this.ylabels.push(_187);
};
MochiKit.Iter.forEach(this.layout.yticks,bind(_186,this));
}
_184.beginPath();
_184.moveTo(this.area.x,this.area.y);
_184.lineTo(this.area.x,this.area.y+this.area.h);
_184.closePath();
_184.stroke();
}
if(this.options.drawXAxis){
if(this.layout.xticks){
var _186=function(tick){
var x=this.area.x+tick[0]*this.area.w;
var y=this.area.y+this.area.h;
_184.beginPath();
_184.moveTo(x,y);
_184.lineTo(x,y+this.options.axisTickSize);
_184.closePath();
_184.stroke();
var _188=DIV(_185,tick[1]);
_188.style.top=(y+this.options.axisTickSize)+"px";
_188.style.left=(x-this.options.axisLabelWidth/2)+"px";
_188.style.textAlign="center";
_188.style.width=this.options.axisLabelWidth+"px";
MochiKit.DOM.appendChildNodes(this.container,_188);
this.xlabels.push(_188);
};
MochiKit.Iter.forEach(this.layout.xticks,bind(_186,this));
}
_184.beginPath();
_184.moveTo(this.area.x,this.area.y+this.area.h);
_184.lineTo(this.area.x+this.area.w,this.area.y+this.area.h);
_184.closePath();
_184.stroke();
}
_184.restore();
};
PlotKit.CanvasRenderer.prototype._renderPieAxis=function(){
if(!this.options.drawXAxis){
return;
}
if(this.layout.xticks){
var _189=new Array();
for(var i=0;i<this.layout.slices.length;i++){
_189[this.layout.slices[i].xval]=this.layout.slices[i];
}
var _190=this.area.x+this.area.w*0.5;
var _191=this.area.y+this.area.h*0.5;
var _192=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
var _193=this.options.axisLabelWidth;
for(var i=0;i<this.layout.xticks.length;i++){
var _194=_189[this.layout.xticks[i][0]];
if(MochiKit.Base.isUndefinedOrNull(_194)){
continue;
}
var _195=(_194.startAngle+_194.endAngle)/2;
var _196=_195;
if(_196>Math.PI*2){
_196=_196-Math.PI*2;
}else{
if(_196<0){
_196=_196+Math.PI*2;
}
}
var _197=_190+Math.sin(_196)*(_192+10);
var _198=_191-Math.cos(_196)*(_192+10);
var _199={"position":"absolute","zIndex":11,"width":_193+"px","fontSize":this.options.axisLabelFontSize+"px","overflow":"hidden","color":this.options.axisLabelColor.toHexString()};
if(_196<=Math.PI*0.5){
_199["textAlign"]="left";
_199["verticalAlign"]="top";
_199["left"]=_197+"px";
_199["top"]=(_198-this.options.axisLabelFontSize)+"px";
}else{
if((_196>Math.PI*0.5)&&(_196<=Math.PI)){
_199["textAlign"]="left";
_199["verticalAlign"]="bottom";
_199["left"]=_197+"px";
_199["top"]=_198+"px";
}else{
if((_196>Math.PI)&&(_196<=Math.PI*1.5)){
_199["textAlign"]="right";
_199["verticalAlign"]="bottom";
_199["left"]=(_197-_193)+"px";
_199["top"]=_198+"px";
}else{
_199["textAlign"]="right";
_199["verticalAlign"]="bottom";
_199["left"]=(_197-_193)+"px";
_199["top"]=(_198-this.options.axisLabelFontSize)+"px";
}
}
}
var _200=DIV({"style":_199},this.layout.xticks[i][1]);
this.xlabels.push(_200);
MochiKit.DOM.appendChildNodes(this.container,_200);
}
}
};
PlotKit.CanvasRenderer.prototype._renderBackground=function(){
var _201=this.element.getContext("2d");
_201.save();
_201.fillStyle=this.options.backgroundColor.toRGBString();
_201.fillRect(0,0,this.width,this.height);
_201.restore();
};
PlotKit.CanvasRenderer.prototype.clear=function(){
if(this.isIE){
try{
if(this.clearDelay){
this.clearDelay.cancel();
this.clearDelay=null;
}
var _202=this.element.getContext("2d");
}
catch(e){
this.isFirstRender=false;
this.clearDelay=MochiKit.Async.wait(this.IEDelay);
this.clearDelay.addCallback(bind(this.clear,this));
return;
}
}
var _202=this.element.getContext("2d");
_202.clearRect(0,0,this.width,this.height);
MochiKit.Iter.forEach(this.xlabels,MochiKit.DOM.removeElement);
MochiKit.Iter.forEach(this.ylabels,MochiKit.DOM.removeElement);
this.xlabels=new Array();
this.ylabels=new Array();
};
PlotKit.CanvasRenderer.prototype._initialiseEvents=function(){
var _203=MochiKit.Signal.connect;
var bind=MochiKit.Base.bind;
MochiKit.Signal.registerSignals(this,["onmouseover","onclick","onmouseout","onmousemove"]);
_203(this.element,"onclick",bind(this.onclick,this));
};
PlotKit.CanvasRenderer.prototype._resolveObject=function(e){
var x=(e.mouse().page.x-PlotKit.Base.findPosX(this.element)-this.area.x)/this.area.w;
var y=(e.mouse().page.y-PlotKit.Base.findPosY(this.element)-this.area.y)/this.area.h;
var _205=this.layout.hitTest(x,y);
if(_205){
return _205;
}
return null;
};
PlotKit.CanvasRenderer.prototype._createEventObject=function(_206,e){
if(_206==null){
return null;
}
e.chart=_206;
return e;
};
PlotKit.CanvasRenderer.prototype.onclick=function(e){
var _207=this._resolveObject(e);
var _208=this._createEventObject(_207,e);
if(_208!=null){
MochiKit.Signal.signal(this,"onclick",_208);
}
};
PlotKit.CanvasRenderer.prototype.onmouseover=function(e){
var _209=this._resolveObject(e);
var _210=this._createEventObject(_209,e);
if(_210!=null){
signal(this,"onmouseover",_210);
}
};
PlotKit.CanvasRenderer.prototype.onmouseout=function(e){
var _211=this._resolveObject(e);
var _212=this._createEventObject(_211,e);
if(_212==null){
signal(this,"onmouseout",e);
}else{
signal(this,"onmouseout",_212);
}
};
PlotKit.CanvasRenderer.prototype.onmousemove=function(e){
var _213=this._resolveObject(e);
var _214=this._createEventObject(_213,e);
if((_213==null)&&(this.event_isinside==null)){
return;
}
if((_213!=null)&&(this.event_isinside==null)){
signal(this,"onmouseover",_214);
}
if((_213==null)&&(this.event_isinside!=null)){
signal(this,"onmouseout",_214);
}
if((_213!=null)&&(this.event_isinside!=null)){
signal(this,"onmousemove",_214);
}
this.event_isinside=_213;
};
PlotKit.CanvasRenderer.isSupported=function(_215){
var _216=null;
try{
if(MochiKit.Base.isUndefinedOrNull(_215)){
_216=MochiKit.DOM.CANVAS({});
}else{
_216=MochiKit.DOM.getElement(_215);
}
var _217=_216.getContext("2d");
}
catch(e){
var ie=navigator.appVersion.match(/MSIE (\d\.\d)/);
var _219=(navigator.userAgent.toLowerCase().indexOf("opera")!=-1);
if((!ie)||(ie[1]<6)||(_219)){
return false;
}
return true;
}
return true;
};
PlotKit.Canvas={};
PlotKit.Canvas.CanvasRenderer=PlotKit.CanvasRenderer;
PlotKit.Canvas.EXPORT=["CanvasRenderer"];
PlotKit.Canvas.EXPORT_OK=["CanvasRenderer"];
PlotKit.Canvas.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.Canvas.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.Canvas);
try{
if(typeof (PlotKit.Layout)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.Layout";
}
PlotKit.SVGRenderer=function(_220,_221,_222){
if(arguments.length>0){
this.__init__(_220,_221,_222);
}
};
PlotKit.SVGRenderer.NAME="PlotKit.SVGRenderer";
PlotKit.SVGRenderer.VERSION=PlotKit.VERSION;
PlotKit.SVGRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.SVGRenderer.toString=function(){
return this.__repr__();
};
PlotKit.SVGRenderer.prototype.__init__=function(_223,_224,_225){
var _226=MochiKit.Base.isUndefinedOrNull;
this.options={"drawBackground":true,"backgroundColor":Color.whiteColor(),"padding":{left:30,right:30,top:5,bottom:10},"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[1]),"strokeColor":Color.whiteColor(),"strokeColorTransform":"asStrokeColor","strokeWidth":0.5,"shouldFill":true,"shouldStroke":true,"drawXAxis":true,"drawYAxis":true,"axisLineColor":Color.blackColor(),"axisLineWidth":0.5,"axisTickSize":3,"axisLabelColor":Color.blackColor(),"axisLabelFont":"Arial","axisLabelFontSize":9,"axisLabelWidth":50,"axisLabelUseDiv":true,"pieRadius":0.4,"enableEvents":true};
MochiKit.Base.update(this.options,_225?_225:{});
this.layout=_224;
this.style=_224.style;
this.element=MochiKit.DOM.getElement(_223);
this.container=this.element.parentNode;
this.height=parseInt(this.element.getAttribute("height"));
this.width=parseInt(this.element.getAttribute("width"));
this.document=document;
this.root=this.element;
try{
this.document=this.element.getSVGDocument();
this.root=_226(this.document.documentElement)?this.element:this.document.documentElement;
}
catch(e){
}
this.element.style.zIndex=1;
if(_226(this.element)){
throw "SVGRenderer() - passed SVG object is not found";
}
if(_226(this.container)||this.container.nodeName.toLowerCase()!="div"){
throw "SVGRenderer() - No DIV's around the SVG.";
}
this.xlabels=new Array();
this.ylabels=new Array();
this.defs=this.createSVGElement("defs");
this.area={x:this.options.padding.left,y:this.options.padding.top,w:this.width-this.options.padding.left-this.options.padding.right,h:this.height-this.options.padding.top-this.options.padding.bottom};
MochiKit.DOM.updateNodeAttributes(this.container,{"style":{"position":"relative","width":this.width+"px"}});
};
PlotKit.SVGRenderer.prototype.render=function(){
if(this.options.drawBackground){
this._renderBackground();
}
if(this.style=="bar"){
this._renderBarChart();
this._renderBarAxis();
}else{
if(this.style=="pie"){
this._renderPieChart();
this._renderPieAxis();
}else{
if(this.style=="line"){
this._renderLineChart();
this._renderLineAxis();
}
}
}
};
PlotKit.SVGRenderer.prototype._renderBarOrLine=function(data,_227,_228,_229){
var _230=this.options.colorScheme.length;
var _231=this.options.colorScheme;
var _232=MochiKit.Base.keys(this.layout.datasets);
var _233=_232.length;
for(var i=0;i<_233;i++){
var _234=_232[i];
var _235=new Array();
var _236=_231[i%_230];
if(this.options.shouldFill){
_235["fill"]=_236.toRGBString();
}else{
_235["fill"]="none";
}
if(this.options.shouldStroke&&(this.options.strokeColor||this.options.strokeColorTransform)){
if(this.options.strokeColor){
_235["stroke"]=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_235["stroke"]=_236[this.options.strokeColorTransform]().toRGBString();
}
}
_235["strokeWidth"]=this.options.strokeWidth;
}
if(_228){
_228(_235);
}
var _237=function(obj){
if(obj.name==_234){
_227(_235,obj);
}
};
MochiKit.Iter.forEach(data,bind(_237,this));
if(_229){
_229(_235);
}
}
};
PlotKit.SVGRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _238=function(_239,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
this._drawRect(x,y,w,h,_239);
};
this._renderBarOrLine(this.layout.bars,bind(_238,this));
};
PlotKit.SVGRenderer.prototype._renderLineChart=function(){
var bind=MochiKit.Base.bind;
var _240=function(_241,_242){
this._tempPointsBuffer+=(this.area.w*_242.x+this.area.x)+","+(this.area.h*_242.y+this.area.y)+" ";
};
var _243=function(_244){
this._tempPointsBuffer="";
this._tempPointsBuffer+=(this.area.x)+","+(this.area.y+this.area.h)+" ";
};
var _245=function(_246){
this._tempPointsBuffer+=(this.area.w+this.area.x)+","+(this.area.h+this.area.y);
_246["points"]=this._tempPointsBuffer;
var elem=this.createSVGElement("polygon",_246);
this.root.appendChild(elem);
};
this._renderBarOrLine(this.layout.points,bind(_240,this),bind(_243,this),bind(_245,this));
};
PlotKit.SVGRenderer.prototype._renderPieChart=function(){
var _248=this.options.colorScheme.length;
var _249=this.layout.slices;
var _250=this.area.x+this.area.w*0.5;
var _251=this.area.y+this.area.h*0.5;
var _252=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
if(_249.length==1&&(Math.abs(_249[0].startAngle)-Math.abs(_249[0].endAngle)<0.1)){
var _253={"cx":_250,"cy":_251,"r":_252};
var _254=this.options.colorScheme[0];
if(this.options.shouldFill){
_253["fill"]=_254.toRGBString();
}else{
_253["fill"]="none";
}
if(this.options.shouldStroke&&(this.options.strokeColor||this.options.strokeColorTransform)){
if(this.options.strokeColor){
_253["stroke"]=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_253["stroke"]=_254[this.options.strokeColorTransform]().toRGBString();
}
}
_253["style"]="stroke-width: "+this.options.strokeWidth;
}
this.root.appendChild(this.createSVGElement("circle",_253));
return;
}
for(var i=0;i<_249.length;i++){
var _253=new Array();
var _254=this.options.colorScheme[i%_248];
if(this.options.shouldFill){
_253["fill"]=_254.toRGBString();
}else{
_253["fill"]="none";
}
if(this.options.shouldStroke&&(this.options.strokeColor||this.options.strokeColorTransform)){
if(this.options.strokeColor){
_253["stroke"]=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_253["stroke"]=_254[this.options.strokeColorTransform]().toRGBString();
}
}
_253["style"]="stroke-width:"+this.options.strokeWidth;
}
var _255=0;
if(Math.abs(_249[i].endAngle-_249[i].startAngle)>Math.PI){
_255=1;
}
var x1=Math.cos(_249[i].startAngle-Math.PI/2)*_252;
var y1=Math.sin(_249[i].startAngle-Math.PI/2)*_252;
var x2=Math.cos(_249[i].endAngle-Math.PI/2)*_252;
var y2=Math.sin(_249[i].endAngle-Math.PI/2)*_252;
var rx=x2-x1;
var ry=y2-y1;
var _262="M"+_250+","+_251+" ";
_262+="l"+x1+","+y1+" ";
_262+="a"+_252+","+_252+" 0 "+_255+",1 "+rx+","+ry+" z";
_253["d"]=_262;
var elem=this.createSVGElement("path",_253);
this.root.appendChild(elem);
}
};
PlotKit.SVGRenderer.prototype._renderBarAxis=function(){
this._renderAxis();
};
PlotKit.SVGRenderer.prototype._renderLineAxis=function(){
this._renderAxis();
};
PlotKit.SVGRenderer.prototype._renderAxis=function(){
if(!this.options.drawXAxis&&!this.options.drawYAxis){
return;
}
var _263={"style":{"position":"absolute","textAlign":"center","fontSize":this.options.axisLabelFontSize+"px","zIndex":10,"color":this.options.axisLabelColor.toRGBString(),"width":this.options.axisLabelWidth+"px","overflow":"hidden"}};
var _264={"stroke":this.options.axisLineColor.toRGBString(),"strokeWidth":this.options.axisLineWidth};
if(this.options.drawYAxis){
if(this.layout.yticks){
var _265=function(tick){
var x=this.area.x;
var y=this.area.y+tick[0]*this.area.h;
this._drawLine(x,y,x-3,y,_264);
if(this.options.axisLabelUseDiv){
var _266=DIV(_263,tick[1]);
_266.style.top=(y-this.options.axisLabelFontSize)+"px";
_266.style.left=(x-this.options.padding.left+this.options.axisTickSize)+"px";
_266.style.textAlign="left";
_266.style.width=(this.options.padding.left-3)+"px";
MochiKit.DOM.appendChildNodes(this.container,_266);
this.ylabels.push(_266);
}else{
var _267={y:y+3,x:(x-this.options.padding.left+3),width:(this.options.padding.left-this.options.axisTickSize)+"px",height:(this.options.axisLabelFontSize+3)+"px",fontFamily:"Arial",fontSize:this.options.axisLabelFontSize+"px",fill:this.options.axisLabelColor.toRGBString()};
var _266=this.createSVGElement("text",_267);
_266.appendChild(this.document.createTextNode(tick[1]));
this.root.appendChild(_266);
}
};
MochiKit.Iter.forEach(this.layout.yticks,bind(_265,this));
}
this._drawLine(this.area.x,this.area.y,this.area.x,this.area.y+this.area.h,_264);
}
if(this.options.drawXAxis){
if(this.layout.xticks){
var _265=function(tick){
var x=this.area.x+tick[0]*this.area.w;
var y=this.area.y+this.area.h;
this._drawLine(x,y,x,y+this.options.axisTickSize,_264);
if(this.options.axisLabelUseDiv){
var _268=DIV(_263,tick[1]);
_268.style.top=(y+this.options.axisTickSize)+"px";
_268.style.left=(x-this.options.axisLabelWidth/2)+"px";
_268.style.textAlign="center";
_268.style.width=this.options.axisLabelWidth+"px";
MochiKit.DOM.appendChildNodes(this.container,_268);
this.xlabels.push(_268);
}else{
var _269={y:(y+this.options.axisTickSize+this.options.axisLabelFontSize),x:x-3,width:this.options.axisLabelWidth+"px",height:(this.options.axisLabelFontSize+3)+"px",fontFamily:"Arial",fontSize:this.options.axisLabelFontSize+"px",fill:this.options.axisLabelColor.toRGBString(),textAnchor:"middle"};
var _268=this.createSVGElement("text",_269);
_268.appendChild(this.document.createTextNode(tick[1]));
this.root.appendChild(_268);
}
};
MochiKit.Iter.forEach(this.layout.xticks,bind(_265,this));
}
this._drawLine(this.area.x,this.area.y+this.area.h,this.area.x+this.area.w,this.area.y+this.area.h,_264);
}
};
PlotKit.SVGRenderer.prototype._renderPieAxis=function(){
if(this.layout.xticks){
var _270=new Array();
for(var i=0;i<this.layout.slices.length;i++){
_270[this.layout.slices[i].xval]=this.layout.slices[i];
}
var _271=this.area.x+this.area.w*0.5;
var _272=this.area.y+this.area.h*0.5;
var _273=Math.min(this.area.w*this.options.pieRadius+10,this.area.h*this.options.pieRadius+10);
var _274=this.options.axisLabelWidth;
for(var i=0;i<this.layout.xticks.length;i++){
var _275=_270[this.layout.xticks[i][0]];
if(MochiKit.Base.isUndefinedOrNull(_275)){
continue;
}
var _276=(_275.startAngle+_275.endAngle)/2;
var _277=_276;
if(_277>Math.PI*2){
_277=_277-Math.PI*2;
}else{
if(_277<0){
_277=_277+Math.PI*2;
}
}
var _278=_271+Math.sin(_277)*(_273+10);
var _279=_272-Math.cos(_277)*(_273+10);
var _280={"position":"absolute","zIndex":11,"width":_274+"px","fontSize":this.options.axisLabelFontSize+"px","overflow":"hidden","color":this.options.axisLabelColor.toHexString()};
var _281={"width":_274+"px","fontSize":this.options.axisLabelFontSize+"px","height":(this.options.axisLabelFontSize+3)+"px","fill":this.options.axisLabelColor.toRGBString()};
if(_277<=Math.PI*0.5){
MochiKit.Base.update(_280,{"textAlign":"left","verticalAlign":"top","left":_278+"px","top":(_279-this.options.axisLabelFontSize)+"px"});
MochiKit.Base.update(_281,{"x":_278,"y":(_279-this.options.axisLabelFontSize),"textAnchor":"left"});
}else{
if((_277>Math.PI*0.5)&&(_277<=Math.PI)){
MochiKit.Base.update(_280,{"textAlign":"left","verticalAlign":"bottom","left":_278+"px","top":_279+"px"});
MochiKit.Base.update(_281,{"textAnchor":"left","x":_278,"y":_279});
}else{
if((_277>Math.PI)&&(_277<=Math.PI*1.5)){
MochiKit.Base.update(_280,{"textAlign":"right","verticalAlign":"bottom","left":_278+"px","top":_279+"px"});
MochiKit.Base.update(_281,{"textAnchor":"right","x":_278-_274,"y":_279});
}else{
MochiKit.Base.update(_280,{"textAlign":"left","verticalAlign":"bottom","left":_278+"px","top":_279+"px"});
MochiKit.Base.update(_281,{"textAnchor":"left","x":_278-_274,"y":_279-this.options.axisLabelFontSize});
}
}
}
if(this.options.axisLabelUseDiv){
var _282=DIV({"style":_280},this.layout.xticks[i][1]);
this.xlabels.push(_282);
MochiKit.DOM.appendChildNodes(this.container,_282);
}else{
var _282=this.createSVGElement("text",_281);
_282.appendChild(this.document.createTextNode(this.layout.xticks[i][1]));
this.root.appendChild(_282);
}
}
}
};
PlotKit.SVGRenderer.prototype._renderBackground=function(){
var opts={"stroke":"none","fill":this.options.backgroundColor.toRGBString()};
this._drawRect(0,0,this.width,this.height,opts);
};
PlotKit.SVGRenderer.prototype._drawRect=function(x,y,w,h,_284){
var _285={x:x+"px",y:y+"px",width:w+"px",height:h+"px"};
if(_284){
MochiKit.Base.update(_285,_284);
}
var elem=this.createSVGElement("rect",_285);
this.root.appendChild(elem);
};
PlotKit.SVGRenderer.prototype._drawLine=function(x1,y1,x2,y2,_286){
var _287={x1:x1+"px",y1:y1+"px",x2:x2+"px",y2:y2+"px"};
if(_286){
MochiKit.Base.update(_287,_286);
}
var elem=this.createSVGElement("line",_287);
this.root.appendChild(elem);
};
PlotKit.SVGRenderer.prototype.clear=function(){
while(this.element.firstChild){
this.element.removeChild(this.element.firstChild);
}
if(this.options.axisLabelUseDiv){
for(var i=0;i<this.xlabels.length;i++){
MochiKit.DOM.removeElement(this.xlabels[i]);
}
for(var i=0;i<this.ylabels.length;i++){
MochiKit.DOM.removeElement(this.ylabels[i]);
}
}
this.xlabels=new Array();
this.ylabels=new Array();
};
PlotKit.SVGRenderer.prototype.createSVGElement=function(name,_289){
var _290=MochiKit.Base.isUndefinedOrNull;
var elem;
var doc=_290(this.document)?document:this.document;
try{
elem=doc.createElementNS("http://www.w3.org/2000/svg",name);
}
catch(e){
elem=doc.createElement(name);
elem.setAttribute("xmlns","http://www.w3.org/2000/svg");
}
if(_289){
MochiKit.DOM.updateNodeAttributes(elem,_289);
}
return elem;
};
PlotKit.SVGRenderer.SVGNS="http://www.w3.org/2000/svg";
PlotKit.SVGRenderer.SVG=function(_292){
var ie=navigator.appVersion.match(/MSIE (\d\.\d)/);
var _293=(navigator.userAgent.toLowerCase().indexOf("opera")!=-1);
if(ie&&(ie[1]>=6)&&(!_293)){
var _294=_292["width"]?_292["width"]:"100";
var _295=_292["height"]?_292["height"]:"100";
var eid=_292["id"]?_292["id"]:"notunique";
var html="<svg:svg width=\""+_294+"\" height=\""+_295+"\" ";
html+="id=\""+eid+"\" version=\"1.1\" baseProfile=\"full\" />";
var _298=document.createElement(html);
var _299=_298.getSVGDocument().createElementNS(PlotKit.SVGRenderer.SVGNS,"svg");
_299.setAttribute("width",_294);
_299.setAttribute("height",_295);
_298.getSVGDocument().appendChild(_299);
return _298;
}else{
return PlotKit.SVGRenderer.prototype.createSVGElement("svg",_292);
}
};
PlotKit.SVGRenderer.isSupported=function(){
var _300=(navigator.userAgent.toLowerCase().indexOf("opera")!=-1);
var _301=navigator.appVersion.match(/MSIE (\d\.\d)/);
var _302=navigator.userAgent.match(/AppleWebKit\/(\d+)/);
var _303=navigator.userAgent.match(/Opera\/(\d*\.\d*)/);
var _304=navigator.userAgent.match(/rv:(\d*\.\d*).*Gecko/);
if(_301&&(_301[1]>=6)&&!_300){
var _305=document.createElement("<svg:svg width=\"1\" height=\"1\" baseProfile=\"full\" version=\"1.1\" id=\"dummy\">");
try{
_305.getSVGDocument();
_305=null;
return true;
}
catch(e){
return false;
}
}
if(_303&&(_303[1]>8.9)){
return true;
}
if(_304&&(_304>1.7)){
return true;
}
return false;
};
PlotKit.SVG={};
PlotKit.SVG.SVGRenderer=PlotKit.SVGRenderer;
PlotKit.SVG.EXPORT=["SVGRenderer"];
PlotKit.SVG.EXPORT_OK=["SVGRenderer"];
PlotKit.SVG.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.SVG.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.SVG);
try{
if(typeof (PlotKit.CanvasRenderer)=="undefined"){
throw "";
}
}
catch(e){
throw "SweetCanvas depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.{Layout, Canvas}";
}
if(typeof (PlotKit.SweetCanvasRenderer)=="undefined"){
PlotKit.SweetCanvasRenderer={};
}
PlotKit.SweetCanvasRenderer=function(_306,_307,_308){
if(arguments.length>0){
this.__init__(_306,_307,_308);
}
};
PlotKit.SweetCanvasRenderer.NAME="PlotKit.SweetCanvasRenderer";
PlotKit.SweetCanvasRenderer.VERSION=PlotKit.VERSION;
PlotKit.SweetCanvasRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.SweetCanvasRenderer.toString=function(){
return this.__repr__();
};
PlotKit.SweetCanvasRenderer.prototype=new PlotKit.CanvasRenderer();
PlotKit.SweetCanvasRenderer.prototype.constructor=PlotKit.SweetCanvasRenderer;
PlotKit.SweetCanvasRenderer.__super__=PlotKit.CanvasRenderer.prototype;
PlotKit.SweetCanvasRenderer.prototype.__init__=function(el,_310,opts){
var _311=PlotKit.Base.officeBlue();
MochiKit.Base.update(_311,opts);
PlotKit.SweetCanvasRenderer.__super__.__init__.call(this,el,_310,_311);
};
PlotKit.SweetCanvasRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _312=Color.blackColor().colorWithAlpha(0.1).toRGBString();
var _313=function(_314,x,y,w,h){
_314.fillStyle=_312;
_314.fillRect(x-2,y-2,w+4,h+2);
_314.fillStyle=_312;
_314.fillRect(x-1,y-1,w+2,h+1);
};
var _315=this.options.colorScheme.length;
var _316=this.options.colorScheme;
var _317=MochiKit.Base.keys(this.layout.datasets);
var _318=_317.length;
var _319=function(name){
for(var i=0;i<_318;i++){
if(name==_317[i]){
return _316[i%_315];
}
}
return _316[0];
};
var _320=function(_321,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
if((w<1)||(h<1)){
return;
}
_321.save();
_321.shadowBlur=5;
_321.shadowColor=Color.fromHexString("#888888").toRGBString();
if(this.isIE){
_321.save();
_321.fillStyle="#cccccc";
_321.fillRect(x-2,y-2,w+4,h+2);
_321.restore();
}else{
_313(_321,x,y,w,h);
}
_321.fillStyle=_319(bar.name).toRGBString();
_321.fillRect(x,y,w,h);
_321.shadowBlur=0;
_321.strokeStyle=Color.whiteColor().toRGBString();
_321.lineWidth=2;
_321.strokeRect(x,y,w,h);
_321.restore();
};
this._renderBarChartWrap(this.layout.bars,bind(_320,this));
};
PlotKit.CanvasRenderer.prototype._renderLineChart=function(){
var _322=this.element.getContext("2d");
var _323=this.options.colorScheme.length;
var _324=this.options.colorScheme;
var _325=MochiKit.Base.keys(this.layout.datasets);
var _326=_325.length;
var bind=MochiKit.Base.bind;
for(var i=0;i<_326;i++){
var _327=_325[i];
var _328=_324[i%_323];
var _329=this.options.strokeColorTransform;
_322.save();
var _330=function(){
_322.beginPath();
_322.moveTo(this.area.x,this.area.y+this.area.h);
var _331=function(_322,_332){
if(_332.name==_327){
_322.lineTo(this.area.w*_332.x+this.area.x,this.area.h*_332.y+this.area.y);
}
};
MochiKit.Iter.forEach(this.layout.points,partial(_331,context),this);
context.lineTo(this.area.w+this.area.x,this.area.h+this.area.y);
context.lineTo(this.area.x,this.area.y+this.area.h);
context.closePath();
};
if(this.options.shouldFill){
context.save();
if(this.isIE){
context.fillStyle="#cccccc";
}else{
context.fillStyle=Color.blackColor().colorWithAlpha(0.2).toRGBString();
}
context.translate(-1,-2);
bind(_330,this)();
context.fill();
}
context.restore();
context.shadowBlur=5;
context.shadowColor=Color.fromHexString("#888888").toRGBString();
context.fillStyle=_328.toRGBString();
context.lineWidth=2;
context.strokeStyle=Color.whiteColor().toRGBString();
if(this.options.shouldFill){
bind(_330,this)();
context.fill();
}
if(this.options.shouldStroke){
bind(_330,this)();
context.stroke();
}
context.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderPieChart=function(){
var _333=this.element.getContext("2d");
var _334=this.options.colorScheme.length;
var _335=this.layout.slices;
var _336=this.area.x+this.area.w*0.5;
var _337=this.area.y+this.area.h*0.5;
var _338=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
if(this.isIE){
_336=parseInt(_336);
_337=parseInt(_337);
_338=parseInt(_338);
}
if(!this.isIE){
_333.save();
var _339=Color.blackColor().colorWithAlpha(0.2);
_333.fillStyle=_339.toRGBString();
_333.shadowBlur=5;
_333.shadowColor=Color.fromHexString("#888888").toRGBString();
_333.translate(1,1);
_333.beginPath();
_333.moveTo(_336,_337);
_333.arc(_336,_337,_338+2,0,Math.PI*2,false);
_333.closePath();
_333.fill();
_333.restore();
}
_333.save();
_333.strokeStyle=Color.whiteColor().toRGBString();
_333.lineWidth=2;
for(var i=0;i<_335.length;i++){
var _340=this.options.colorScheme[i%_334];
_333.fillStyle=_340.toRGBString();
var _341=function(){
_333.beginPath();
_333.moveTo(_336,_337);
_333.arc(_336,_337,_338,_335[i].startAngle-Math.PI/2,_335[i].endAngle-Math.PI/2,false);
_333.lineTo(_336,_337);
_333.closePath();
};
if(Math.abs(_335[i].startAngle-_335[i].endAngle)>0.0001){
_341();
_333.fill();
_341();
_333.stroke();
}
}
_333.restore();
};
PlotKit.SweetCanvasRenderer.prototype._renderBackground=function(){
var _342=this.element.getContext("2d");
if(this.layout.style=="bar"||this.layout.style=="line"){
_342.save();
_342.fillStyle=this.options.backgroundColor.toRGBString();
_342.fillRect(this.area.x,this.area.y,this.area.w,this.area.h);
_342.strokeStyle=Color.whiteColor().toRGBString();
_342.lineWidth=1;
for(var i=0;i<this.layout.yticks.length;i++){
var y=this.layout.yticks[i][0]*this.area.h+this.area.y;
var x=this.area.x;
_342.beginPath();
_342.moveTo(x,y);
_342.lineTo(x+this.area.w,y);
_342.closePath();
_342.stroke();
}
_342.restore();
}else{
PlotKit.SweetCanvasRenderer.__super__._renderBackground.call(this);
}
};
PlotKit.SweetCanvas={};
PlotKit.SweetCanvas.SweetCanvasRenderer=PlotKit.SweetCanvasRenderer;
PlotKit.SweetCanvas.EXPORT=["SweetCanvasRenderer"];
PlotKit.SweetCanvas.EXPORT_OK=["SweetCanvasRenderer"];
PlotKit.SweetCanvas.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.SweetCanvas.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.SweetCanvas);
try{
if(typeof (PlotKit.SVGRenderer)=="undefined"){
throw "";
}
}
catch(e){
throw "SweetSVG depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.{Layout, SVG}";
}
if(typeof (PlotKit.SweetSVGRenderer)=="undefined"){
PlotKit.SweetSVGRenderer={};
}
PlotKit.SweetSVGRenderer=function(_343,_344,_345){
if(arguments.length>0){
this.__init__(_343,_344,_345);
}
};
PlotKit.SweetSVGRenderer.NAME="PlotKit.SweetSVGRenderer";
PlotKit.SweetSVGRenderer.VERSION=PlotKit.VERSION;
PlotKit.SweetSVGRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.SweetSVGRenderer.toString=function(){
return this.__repr__();
};
PlotKit.SweetSVGRenderer.prototype=new PlotKit.SVGRenderer();
PlotKit.SweetSVGRenderer.prototype.constructor=PlotKit.SweetSVGRenderer;
PlotKit.SweetSVGRenderer.__super__=PlotKit.SVGRenderer.prototype;
PlotKit.SweetSVGRenderer.prototype.__init__=function(_346,_347,_348){
var _349=PlotKit.Base.officeBlue();
MochiKit.Base.update(_349,_348);
PlotKit.SweetSVGRenderer.__super__.__init__.call(this,_346,_347,_349);
};
PlotKit.SweetSVGRenderer.prototype._addDropShadowFilter=function(){
var _350=this.createSVGElement("filter",{x:0,y:0,"id":"dropShadow"});
var _351=this.createSVGElement("feOffset",{"in":"SourceGraphic","dx":0,"dy":0,"result":"topCopy"});
var blur=this.createSVGElement("feGaussianBlur",{"in":"SourceAlpha","StdDeviation":2,"result":"shadow"});
var _353=this.createSVGElement("feOffset",{"in":"shadow","dx":-1,"dy":-2,"result":"movedShadow"});
var _354=this.createSVGElement("feMerge");
var _355=this.createSVGElement("feMergeNode",{"in":"topCopy"});
var _356=this.createSVGElement("feMergeNode",{"in":"movedShadow"});
_354.appendChild(_355);
_354.appendChild(_356);
_350.appendChild(_351);
_350.appendChild(blur);
_350.appendChild(_353);
_350.appendChild(_354);
this.defs.appendChild(_350);
};
PlotKit.SweetSVGRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _357=Color.blackColor().toRGBString();
var _358="fill:"+_357+";fill-opacity:0.15";
var _359="stroke-width: 2.0; stroke:"+Color.whiteColor().toRGBString();
var _360=function(_361,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
if((w<1)||(h<1)){
return;
}
_361["style"]=_359;
this._drawRect(x-2,y-1,w+4,h+2,{"style":_358});
this._drawRect(x,y,w,h,_361);
};
this._renderBarOrLine(this.layout.bars,bind(_360,this));
};
PlotKit.SweetSVGRenderer.prototype._renderLineChart=function(){
var bind=MochiKit.Base.bind;
var _362=Color.blackColor().toRGBString();
var _363="fill:"+_362+";fill-opacity:0.15";
var _364="stroke-width: 2.0; stroke:"+Color.whiteColor().toRGBString();
var _365=function(_366,_367){
this._tempPointsBuffer+=(this.area.w*_367.x+this.area.x)+","+(this.area.h*_367.y+this.area.y)+" ";
};
var _368=function(_369){
this._tempPointsBuffer="";
this._tempPointsBuffer+=(this.area.x)+","+(this.area.y+this.area.h)+" ";
};
var _370=function(_371){
this._tempPointsBuffer+=(this.area.w+this.area.x)+","+(this.area.h+this.area.y);
_371["points"]=this._tempPointsBuffer;
_371["stroke"]="none";
_371["transform"]="translate(-2, -1)";
_371["style"]=_363;
var _372=this.createSVGElement("polygon",_371);
this.root.appendChild(_372);
_371["transform"]="";
_371["style"]=_364;
var elem=this.createSVGElement("polygon",_371);
this.root.appendChild(elem);
};
this._renderBarOrLine(this.layout.points,bind(_365,this),bind(_368,this),bind(_370,this));
};
PlotKit.SweetSVGRenderer.prototype._renderPieChart=function(){
var _373=this.area.x+this.area.w*0.5;
var _374=this.area.y+this.area.h*0.5;
var _375=Color.blackColor().toRGBString();
var _376=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
var _377="fill:"+_375+";fill-opacity:0.15";
var _378=this.createSVGElement("circle",{"style":_377,"cx":_373+1,"cy":_374+1,"r":_376+1});
this.root.appendChild(_378);
PlotKit.SweetSVGRenderer.__super__._renderPieChart.call(this);
};
PlotKit.SweetSVGRenderer.prototype._renderBackground=function(){
var _379={"fill":this.options.backgroundColor.toRGBString(),"stroke":"none"};
if(this.layout.style=="bar"||this.layout.style=="line"){
this._drawRect(this.area.x,this.area.y,this.area.w,this.area.h,_379);
for(var i=0;i<this.layout.yticks.length;i++){
this._drawRect(this.area.x,this.layout.yticks[i][0]*this.area.h+this.area.y,this.area.w,1,{"fill":Color.whiteColor().toRGBString()});
}
}else{
PlotKit.SweetSVGRenderer.__super__._renderBackground.call(this);
}
};
PlotKit.SweetSVG={};
PlotKit.SweetSVG.SweetSVGRenderer=PlotKit.SweetSVGRenderer;
PlotKit.SweetSVG.EXPORT=["SweetSVGRenderer"];
PlotKit.SweetSVG.EXPORT_OK=["SweetSVGRenderer"];
PlotKit.SweetSVG.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.SweetSVG.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.SweetSVG);


