/***

    PlotKit.PlotKit 0.9.2 : PACKED VERSION

    THIS FILE IS AUTOMATICALLY GENERATED.  If creating patches, please
    diff against the source tree, not this file.

    For more information, <http://www.liquidx.net/plotkit/>.
    
    Copyright (c) 2006. Alastair Tse.

***/

try{
if(typeof (MochiKit.Base)=="undefined"||typeof (MochiKit.DOM)=="undefined"||typeof (MochiKit.Color)=="undefined"||typeof (MochiKit.Format)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit depends on MochiKit.{Base,Color,DOM,Format}";
}
MochiKit.Base.update(MochiKit.Color.Color.prototype,{asFillColor:function(){
return this.lighterColorWithLevel(0.3);
},asStrokeColor:function(){
return this.darkerColorWithLevel(0.1);
},asPointColor:function(){
return this.lighterColorWithLevel(0.1);
},asTransparent:function(){
return this.colorWithAlpha(0.1);
}});
if(typeof (PlotKit)=="undefined"){
PlotKit={};
}
PlotKit.NAME="PlotKit";
PlotKit.VERSION="0.9.2";
PlotKit.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.toString=function(){
return this.__repr__();
};
if(typeof (PlotKit.Base)=="undefined"){
PlotKit.Base={};
}
PlotKit.Base.NAME="PlotKit.Base";
PlotKit.Base.VERSION=PlotKit.VERSION;
PlotKit.Base.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.Base.toString=function(){
return this.__repr__();
};
PlotKit.Base.usingPrototype=function(){
try{
return (typeof (Object.extend)=="function");
}
catch(e){
return false;
}
};
MochiKit.Base.update(PlotKit.Base,{roundInterval:function(_1,_2,_3){
var _4=MochiKit.Format.roundToFixed;
var _5=_1/_2;
return parseFloat(_4(_5,_3));
},collapse:function(_6){
var m=MochiKit.Base;
var _8=new Array();
for(var i=0;i<_6.length;i++){
_8=m.concat(_8,_6[i]);
}
if(PlotKit.Base.usingPrototype()){
delete _8.extend;
delete _8.from;
delete _8.inspect;
}
return _8;
},uniq:function(_10){
var m=MochiKit.Base;
if(!m.isArrayLike(_10)||(_10.length<1)){
return new Array();
}
var _11=new Array();
var _12=_10[0];
_11.push(_10[0]);
for(var i=1;i<_10.length;i++){
if(m.compare(_10[i],_12)!=0){
_12=_10[i];
_11.push(_10[i]);
}
}
return _11;
},colorScheme:function(){
var mb=MochiKit.Base;
var mc=MochiKit.Color;
var _15=["red","orange","yellow","green","cyan","blue","purple","magenta"];
var _16=function(_17){
return mc.Color[_17+"Color"]();
};
return mb.map(_16,_15);
},baseDarkPrimaryColors:function(){
var _18=MochiKit.Color.Color.fromHexString;
return [_18("#ad3f40"),_18("#ddac2c"),_18("#dfdd0c"),_18("#5276c4"),_18("#739c5a")];
},basePrimaryColors:function(){
var _19=MochiKit.Color.Color.fromHexString;
return [_19("#d24c4d"),_19("#f2b32f"),_19("#ece90e"),_19("#5d83da"),_19("#78a15d")];
},baseBlueColors:function(){
var _20=MochiKit.Color.Color.fromHexString;
return [_20("#4b6b94"),_20("#5d81b4"),_20("#acbad2")];
},palette:function(_21,_22,_23,_24){
var _25=MochiKit.Base.isUndefinedOrNull;
var _26=new Array();
if(_25(_24)){
_24=0.1;
}
if(_25(_23)){
_23=0.4;
}
if(_25(_22)){
_22=-0.2;
}
var _27=_22;
while(_27<=_23){
_26.push(_27);
_27+=_24;
}
var _28=function(_29,_30){
return _29.lighterColorWithLevel(_30);
};
return MochiKit.Base.map(MochiKit.Base.partial(_28,_21),_26);
},excanvasSupported:function(){
if(/MSIE/.test(navigator.userAgent)&&!window.opera){
return true;
}
return false;
},findPosX:function(obj){
var _32=0;
if(obj.offsetParent){
while(obj.offsetParent){
_32+=obj.offsetLeft;
obj=obj.offsetParent;
}
}else{
if(obj.x){
_32+=obj.x;
}
}
return _32;
},findPosY:function(obj){
var _33=0;
if(obj.offsetParent){
while(obj.offsetParent){
_33+=obj.offsetTop;
obj=obj.offsetParent;
}
}else{
if(obj.y){
_33+=obj.y;
}
}
return _33;
},isFuncLike:function(obj){
return (typeof (obj)=="function");
}});
PlotKit.Base.map=function(fn,lst){
if(PlotKit.Base.usingPrototype()){
var _36=[];
for(var x in lst){
if(typeof (lst[x])=="function"){
continue;
}
_36.push(fn(lst[x]));
}
return _36;
}else{
return MochiKit.Base.map(fn,lst);
}
};
PlotKit.Base.items=function(lst){
if(PlotKit.Base.usingPrototype()){
var _38=[];
for(var x in lst){
if(typeof (lst[x])=="function"){
continue;
}
_38.push([x,lst[x]]);
}
return _38;
}else{
return MochiKit.Base.items(lst);
}
};
PlotKit.Base.keys=function(lst){
if(PlotKit.Base.usingPrototype()){
var _39=[];
for(var x in lst){
if(typeof (lst[x])=="function"){
continue;
}
_39.push(x);
}
return _39;
}else{
return MochiKit.Base.keys(lst);
}
};
PlotKit.Base.baseColors=function(){
var _40=MochiKit.Color.Color.fromHexString;
return [_40("#476fb2"),_40("#be2c2b"),_40("#85b730"),_40("#734a99"),_40("#26a1c5"),_40("#fb8707"),_40("#000000")];
};
PlotKit.Base.googleColors=function(){
var _41=MochiKit.Color.Color.fromHexString;
return [_41("#0066dd"),_41("#dc3912"),_41("#ff9900"),_41("#008000"),_41("#4942cc"),_41("#990099")];
};
PlotKit.Base.googleStyle=function(){
var r={"colorScheme":PlotKit.Base.googleColors(),"backgroundColor":MochiKit.Color.Color.whiteColor(),"strokeWidth":2,"axisLineWidth":2,"strokeColor":null,"strokeColorTransform":null,"fillColorTransform":"asTransparent","shouldFill":true};
return r;
};
PlotKit.Base.officeBaseStyle={"axisLineWidth":2,"axisLabelColor":MochiKit.Color.Color.grayColor(),"axisLineColor":MochiKit.Color.Color.whiteColor(),"padding":{top:5,bottom:10,left:30,right:30}};
MochiKit.Base.update(PlotKit.Base,{officeBlue:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[0]),"backgroundColor":PlotKit.Base.baseColors()[0].lighterColorWithLevel(0.45)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeRed:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[1]),"backgroundColor":PlotKit.Base.baseColors()[1].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeGreen:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[2]),"backgroundColor":PlotKit.Base.baseColors()[2].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officePurple:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[3]),"backgroundColor":PlotKit.Base.baseColors()[3].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeCyan:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[4]),"backgroundColor":PlotKit.Base.baseColors()[4].lighterColorWithLevel(0.5)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeOrange:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[5]),"backgroundColor":PlotKit.Base.baseColors()[5].lighterColorWithLevel(0.4)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
},officeBlack:function(){
var r={"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[6],0,0.6),"backgroundColor":PlotKit.Base.baseColors()[6].lighterColorWithLevel(0.9)};
MochiKit.Base.update(r,PlotKit.Base.officeBaseStyle);
return r;
}});
PlotKit.Base.EXPORT=["baseColors","collapse","colorScheme","findPosX","findPosY","officeBaseStyle","officeBlue","officeRed","officeGreen","officePurple","officeCyan","officeOrange","officeBlack","roundInterval","uniq","isFuncLike","excanvasSupported"];
PlotKit.Base.EXPORT_OK=[];
PlotKit.Base.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.Base.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.Base);
try{
if(typeof (PlotKit.Base)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit.Layout depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.Base";
}
PlotKit.Layout=function(_43,_44){
this.options={"barWidthFillFraction":0.75,"barOrientation":"vertical","xOriginIsZero":true,"yOriginIsZero":true,"xAxis":null,"yAxis":null,"xTicks":null,"yTicks":null,"xNumberOfTicks":[8,12],"yNumberOfTicks":[5,8],"xTickPrecision":1,"yTickPrecision":1,"pieRadius":0.4,"piePercentages":true};
this.style=_43;
MochiKit.Base.update(this.options,_44?_44:{});
if(!MochiKit.Base.isUndefinedOrNull(this.options.xAxis)){
this.minxval=this.options.xAxis[0];
this.maxxval=this.options.xAxis[1];
this.xscale=this.maxxval-this.minxval;
}else{
this.minxval=0;
this.maxxval=null;
this.xscale=null;
}
if(!MochiKit.Base.isUndefinedOrNull(this.options.yAxis)){
this.minyval=this.options.yAxis[0];
this.maxyval=this.options.yAxis[1];
this.yscale=this.maxyval-this.minyval;
}else{
this.minyval=0;
this.maxyval=null;
this.yscale=null;
}
this.bars=new Array();
this.points=new Array();
this.slices=new Array();
this.xticks=new Array();
this.yticks=new Array();
this.datasets=new Array();
this.datasetNames=new Array();
this.minxdelta=0;
this.xrange=1;
this.yrange=1;
this.hitTestCache={x2maxy:null};
};
PlotKit.Layout.NAME="PlotKit.Layout";
PlotKit.Layout.VERSION=PlotKit.VERSION;
PlotKit.Layout.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.Layout.toString=function(){
return this.__repr__();
};
PlotKit.Layout.valid_styles=["bar","line","pie","point"];
PlotKit.Layout.prototype.addDataset=function(_45,_46){
this.datasets[_45]=_46;
if(MochiKit.Base.findValue(this.datasetNames,_45)<0){
this.datasetNames.push(_45);
}
};
PlotKit.Layout.prototype.removeDataset=function(_47,_48){
delete this.datasets[_47];
this.datasetNames=MochiKit.Base.filter(function(_49){
return _49!=_47;
},this.datasetNames);
};
PlotKit.Layout.prototype.addDatasetFromTable=function(_50,_51,_52,_53,_54){
var _55=MochiKit.Base.isUndefinedOrNull;
var _56=MochiKit.DOM.scrapeText;
var _57=MochiKit.Format.strip;
if(_55(_52)){
_52=0;
}
if(_55(_53)){
_53=1;
}
if(_55(_54)){
_54=-1;
}
var _58=_51.tBodies[0].rows;
var _59=new Array();
var _60=new Array();
if(!_55(_58)){
for(var i=0;i<_58.length;i++){
_59.push([parseFloat(_57(_56(_58[i].cells[_52]))),parseFloat(_57(_56(_58[i].cells[_53])))]);
if(_54>=0){
_60.push({v:parseFloat(_57(_56(_58[i].cells[_52]))),label:_57(_56(_58[i].cells[_54]))});
}
}
this.addDataset(_50,_59);
if(_54>=0){
this.options.xTicks=_60;
}
return true;
}
return false;
};
PlotKit.Layout.prototype.evaluate=function(){
this._evaluateLimits();
this._evaluateScales();
if(this.style=="bar"){
this._evaluateBarTicks();
if(this.options.barOrientation=="horizontal"){
this._evaluateHorizBarCharts();
}else{
this._evaluateBarCharts();
}
}else{
if(this.style=="pie"){
this._evaluatePieTicks();
this._evaluatePieCharts();
}else{
this._evaluateLineTicks();
this._evaluateLineCharts();
}
}
};
PlotKit.Layout.prototype.hitTest=function(x,y){
var f=MochiKit.Format.twoDigitFloat;
if((this.style=="bar")&&this.bars&&(this.bars.length>0)){
for(var i=0;i<this.bars.length;i++){
var bar=this.bars[i];
if((x>=bar.x)&&(x<=bar.x+bar.w)&&(y>=bar.y)&&(y-bar.y<=bar.h)){
return bar;
}
}
}else{
if(this.style=="line"){
if(this.hitTestCache.x2maxy==null){
this._regenerateHitTestCache();
}
var _64=x/this.xscale;
var _65=this.hitTestCache.xvalues;
var _66=null;
var _67=null;
for(var i=1;i<_65.length;i++){
if(_65[i]>_64){
_66=_65[i-1];
_67=_65[i];
break;
}
}
if((_66!=null)){
var _68=this.hitTestCache.x2maxy[_66];
var _69=this.hitTestCache.x2maxy[_67];
var _70=(1-y)/this.yscale;
var _71=(_69-_68)/(_67-_66);
var _72=_68+_71*(_64-_66);
if(_72>=_70){
var obj={xval:_64,yval:_70,xafter:_67,yafter:_69,xbefore:_66,ybefore:_68,yprojected:_72};
return obj;
}
}
}else{
if(this.style=="pie"){
var _73=Math.sqrt((y-0.5)*(y-0.5)+(x-0.5)*(x-0.5));
if(_73>this.options.pieRadius){
return null;
}
var _74=0;
if(y<0.5&&x<0.5){
_74=Math.atan2(y-0.5,x-0.5)+5*Math.PI/2;
}else{
_74=Math.atan2(y-0.5,x-0.5)+Math.PI/2;
}
for(var i=0;i<this.slices.length;i++){
var _75=this.slices[i];
if(_75.startAngle<_74&&_75.endAngle>=_74){
return _75;
}
}
}
}
}
return null;
};
PlotKit.Layout.prototype.rectForX=function(x){
return null;
};
PlotKit.Layout.prototype.angleRangeForX=function(x){
return null;
};
PlotKit.Layout.prototype._evaluateLimits=function(){
var map=PlotKit.Base.map;
var _77=PlotKit.Base.items;
var _78=MochiKit.Base.itemgetter;
var _79=PlotKit.Base.collapse;
var _80=MochiKit.Base.listMin;
var _81=MochiKit.Base.listMax;
var _82=MochiKit.Base.isUndefinedOrNull;
var all=_79(map(_78(1),_77(this.datasets)));
if(_82(this.options.xAxis)){
if(this.options.xOriginIsZero){
this.minxval=0;
}else{
this.minxval=_80(map(parseFloat,map(_78(0),all)));
}
this.maxxval=_81(map(parseFloat,map(_78(0),all)));
}else{
this.minxval=this.options.xAxis[0];
this.maxxval=this.options.xAxis[1];
this.xscale=this.maxval-this.minxval;
}
if(_82(this.options.yAxis)){
if(this.options.yOriginIsZero){
this.minyval=0;
}else{
this.minyval=_80(map(parseFloat,map(_78(1),all)));
}
this.maxyval=_81(map(parseFloat,map(_78(1),all)));
}else{
this.minyval=this.options.yAxis[0];
this.maxyval=this.options.yAxis[1];
this.yscale=this.maxyval-this.minyval;
}
};
PlotKit.Layout.prototype._evaluateScales=function(){
var _84=MochiKit.Base.isUndefinedOrNull;
this.xrange=this.maxxval-this.minxval;
if(this.xrange==0){
this.xscale=1;
}else{
this.xscale=1/this.xrange;
}
this.yrange=this.maxyval-this.minyval;
if(this.yrange==0){
this.yscale=1;
}else{
this.yscale=1/this.yrange;
}
};
PlotKit.Layout.prototype._uniqueXValues=function(_85){
var _86=PlotKit.Base.collapse;
var map=PlotKit.Base.map;
var _87=PlotKit.Base.uniq;
var _88=MochiKit.Base.itemgetter;
var _89=PlotKit.Base.items;
var _90=map(parseFloat,map(_88(0),_86(map(_88(1),_89(this.datasets)))));
try{
_90=MochiKit.Base.concat(_90,_85);
}
catch(e){
}
_90.sort(MochiKit.Base.compare);
return _87(_90);
};
PlotKit.Layout.prototype._barChartXDelta=function(){
var _91=(this.xrange==0)?this.maxxval:this.xrange;
var _92=this._uniqueXValues([this.minxval,this.maxxval]);
for(var i=1;i<_92.length;i++){
_91=Math.min(Math.abs(_92[i]-_92[i-1]),_91);
}
this.minxdelta=_91;
this.xscale=1/(this.xrange+this.minxdelta);
};
PlotKit.Layout.prototype._evaluateBarCharts=function(){
var _93=this.datasetNames.length;
var _94=this.minxdelta*this.xscale*this.options.barWidthFillFraction;
var _95=_94/_93;
var _96=(this.minxdelta*this.xscale-_94)/2;
this.bars=new Array();
for(var i=0;i<this.datasetNames.length;i++){
var _97=this.datasetNames[i];
var _98=this.datasets[_97];
if(PlotKit.Base.isFuncLike(_98)){
continue;
}
for(var j=0;j<_98.length;j++){
var item=_98[j];
var rect={x:((parseFloat(item[0])-this.minxval)*this.xscale)+(i*_95)+_96,y:1-((parseFloat(item[1])-this.minyval)*this.yscale),w:_95,h:((parseFloat(item[1])-this.minyval)*this.yscale),xval:parseFloat(item[0]),yval:parseFloat(item[1]),name:_97};
if((rect.x>=0)&&(rect.x<=1)&&(rect.y>=0)&&(rect.y<=1)){
this.bars.push(rect);
}
}
}
};
PlotKit.Layout.prototype._evaluateHorizBarCharts=function(){
var _102=this.datasetNames.length;
var _103=this.minxdelta*this.xscale*this.options.barWidthFillFraction;
var _104=_103/_102;
var _105=(this.minxdelta*this.xscale-_103)/2;
this.bars=new Array();
for(var i=0;i<this.datasetNames.length;i++){
var _106=this.datasetNames[i];
var _107=this.datasets[_106];
if(PlotKit.Base.isFuncLike(_107)){
continue;
}
for(var j=0;j<_107.length;j++){
var item=_107[j];
var rect={y:((parseFloat(item[0])-this.minxval)*this.xscale)+(i*_104)+_105,x:0,h:_104,w:((parseFloat(item[1])-this.minyval)*this.yscale),xval:parseFloat(item[0]),yval:parseFloat(item[1]),name:_106};
if(rect.y<=0){
rect.y=0;
}
if(rect.y>=1){
rect.y=1;
}
if((rect.x>=0)&&(rect.x<=1)){
this.bars.push(rect);
}
}
}
};
PlotKit.Layout.prototype._evaluateLineCharts=function(){
var _108=this.datasetNames.length;
this.points=new Array();
for(var i=0;i<this.datasetNames.length;i++){
var _109=this.datasetNames[i];
var _110=this.datasets[_109];
if(PlotKit.Base.isFuncLike(_110)){
continue;
}
if(this.style!="area"){
_110.sort(function(a,b){
return MochiKit.Base.compare(parseFloat(a[0]),parseFloat(b[0]));
});
}
for(var j=0;j<_110.length;j++){
var item=_110[j];
var _113={x:((parseFloat(item[0])-this.minxval)*this.xscale),y:1-((parseFloat(item[1])-this.minyval)*this.yscale),xval:parseFloat(item[0]),yval:parseFloat(item[1]),name:_109};
if(_113.y<=0){
_113.y=0;
}
if(_113.y>=1){
_113.y=1;
}
if((_113.x>=0)&&(_113.x<=1)){
this.points.push(_113);
}
}
}
};
PlotKit.Layout.prototype._evaluatePieCharts=function(){
var map=MochiKit.Base.map;
var sum=MochiKit.Iter.sum;
var _115=MochiKit.Base.itemgetter;
var _116=this.datasetNames.length;
var _117=this.datasets[this.datasetNames[0]];
var _118=sum(map(_115(1),_117));
this.slices=new Array();
var _119=0;
for(var i=0;i<_117.length;i++){
var _120=_117[i][1]/_118;
var _121=_119*Math.PI*2;
var _122=(_119+_120)*Math.PI*2;
var _123={fraction:_120,xval:_117[i][0],yval:_117[i][1],startAngle:_121,endAngle:_122};
if(_117[i][1]!=0){
this.slices.push(_123);
}
_119+=_120;
}
};
PlotKit.Layout.prototype._getBestScale=function(_124,_125,_126){
var _127=[1,2,3,4,5];
var _128=5;
var _129=8;
if(MochiKit.Base.isArrayLike(_126)){
if(_126.length>=2){
_128=_126[0];
_129=_126[1];
}else{
_126=_126[0];
}
}
if(typeof (_126)=="number"){
_128=_129=_126;
}
if(_125<_124){
var tmp=_125;
_125=_124;
_124=tmp;
}
var _131=_125-_124;
if(_131<1e-10){
_125=_124+1;
_131=1;
}
var _132=null;
for(var _133=_128;_133<=_129;_133++){
for(var _134=0;_134<_127.length;_134++){
var _135=_127[_134]*(_133-1);
while(_135<_131){
_135*=10;
}
while(_135>_131*10){
_135/=10;
}
var _136=_135/(_133-1);
var _137=_136*Math.ceil(_125/_136);
var _138=_136*Math.floor(_124/_136);
var _139=_137-_138;
if(_139>_135){
continue;
}
var _140=_135-_131;
if((_132==null)||(_140<_132.error)){
_132={ticks:_133,spacing:_136,max:_138+_135,min:_138,error:_140};
}
}
}
MochiKit.Logging.log("bestFit");
return _132;
};
PlotKit.Layout.prototype._evaluateLineTicksForXAxis=function(){
var _141=MochiKit.Base.isUndefinedOrNull;
if(this.options.xTicks){
this.xticks=new Array();
var _142=function(tick){
var _144=tick.label;
if(_141(_144)){
_144=tick.v.toString();
}
if(!_141(tick.tooltip)){
_144=MochiKit.DOM.SPAN({title:tick.tooltip},_144);
}
var pos=this.xscale*(tick.v-this.minxval);
if((pos>=0)&&(pos<=1)){
this.xticks.push([pos,_144]);
}
};
MochiKit.Iter.forEach(this.options.xTicks,MochiKit.Base.bind(_142,this));
}else{
if(this.options.xNumberOfTicks){
var prec=this.options.xTickPrecision;
var _147=this._uniqueXValues();
var _148=this.options.xNumberOfTicks;
if(MochiKit.Base.isArrayLike(this.options.xNumberOfTicks)){
_148=this.options.xNumberOfTicks[1];
}
this.xticks=new Array();
if(true){
for(var i=0;i<_147.length;i++){
var pos=this.xscale*(_147[i]-this.minxval);
this.xticks.push([pos,_147[i]]);
}
}else{
var _149=this._getBestScale(this.minxval,this.maxxval,this.options.xNumberOfTicks);
this.minxval=_149.min;
this.maxxval=_149.max;
for(var i=0;i<_149.ticks;i++){
var xval=_149.min+i*_149.spacing;
var pos=i/(_149.ticks-1);
this.xticks.push([pos,MochiKit.Format.roundToFixed(xval,prec)]);
}
}
}
}
};
PlotKit.Layout.prototype._evaluateLineTicksForYAxis=function(){
var _151=MochiKit.Base.isUndefinedOrNull;
if(this.options.yTicks){
this.yticks=new Array();
var _152=function(tick){
var _153=tick.label;
if(_151(_153)){
_153=tick.v.toString();
}
if(!_151(tick.tooltip)){
_153=MochiKit.DOM.SPAN({title:tick.tooltip},_153);
}
var pos=1-(this.yscale*(tick.v-this.minyval));
if((pos>=0)&&(pos<=1)){
this.yticks.push([pos,_153]);
}
};
MochiKit.Iter.forEach(this.options.yTicks,MochiKit.Base.bind(_152,this));
}else{
if(this.options.yNumberOfTicks){
var _154=this._getBestScale(this.minyval,this.maxyval,this.options.yNumberOfTicks);
var prec=this.options.yTickPrecision;
this.minyval=_154.min;
this.maxyval=_154.max;
this.yticks=new Array();
for(var i=0;i<_154.ticks;i++){
var yval=_154.min+i*_154.spacing;
var pos=(_154.ticks-i-1)/(_154.ticks-1);
this.yticks.push([pos,MochiKit.Format.roundToFixed(yval,prec)]);
}
}
}
};
PlotKit.Layout.prototype._evaluateLineTicks=function(){
this._evaluateLineTicksForXAxis();
this._evaluateLineTicksForYAxis();
this._evaluateScales();
};
PlotKit.Layout.prototype._evaluateBarTicks=function(){
this._evaluateLineTicks();
this._barChartXDelta();
var _156=this.maxxval-this.minxval+this.minxdelta;
var _157=0.5*this.minxdelta/_156;
var _158=(this.maxxval-this.minxval)/_156;
var _159=function(tick){
return [_157+tick[0]*_158,tick[1]];
};
this.xticks=MochiKit.Base.map(MochiKit.Base.bind(_159,this),this.xticks);
if(this.options.barOrientation=="horizontal"){
var _160=this.xticks;
this.xticks=this.yticks;
this.yticks=_160;
var _161=function(tick){
return [1-tick[0],tick[1]];
};
this.xticks=MochiKit.Base.map(_161,this.xticks);
}
};
PlotKit.Layout.prototype._evaluatePieTicks=function(){
var _162=MochiKit.Base.isUndefinedOrNull;
var _163=MochiKit.Format.numberFormatter("#%");
this.xticks=new Array();
if(this.options.xTicks){
var _164=new Array();
for(var i=0;i<this.slices.length;i++){
_164[this.slices[i].xval]=this.slices[i];
}
for(var i=0;i<this.options.xTicks.length;i++){
var tick=this.options.xTicks[i];
var _165=_164[tick.v];
var _166=tick.label;
if(_165){
if(_162(_166)){
_166=tick.v.toString();
}
if(this.options.pieValue=="value"){
_166+=" ("+_165.yval+")";
}else{
if(this.options.pieValue!="none"){
_166+=" ("+_163(_165.fraction)+")";
}
}
if(!_162(tick.tooltip)){
_166=MochiKit.DOM.SPAN({title:tick.tooltip},_166);
}
this.xticks.push([tick.v,_166]);
}
}
}else{
for(var i=0;i<this.slices.length;i++){
var _165=this.slices[i];
var _166=_165.xval+" ("+_163(_165.fraction)+")";
this.xticks.push([_165.xval,_166]);
}
}
};
PlotKit.Layout.prototype._regenerateHitTestCache=function(){
this.hitTestCache.xvalues=this._uniqueXValues();
this.hitTestCache.xlookup=new Array();
this.hitTestCache.x2maxy=new Array();
var _167=MochiKit.Base.listMax;
var _168=MochiKit.Base.itemgetter;
var map=MochiKit.Base.map;
var keys=MochiKit.Base.keys;
for(var i=0;i<this.datasetNames.length;i++){
var _170=this.datasets[this.datasetNames[i]];
for(var j=0;j<_170.length;j++){
var xval=_170[j][0];
var yval=_170[j][1];
if(this.hitTestCache.xlookup[xval]){
this.hitTestCache.xlookup[xval].push([yval,this.datasetNames[i]]);
}else{
this.hitTestCache.xlookup[xval]=[[yval,this.datasetNames[i]]];
}
}
}
for(var x in this.hitTestCache.xlookup){
var _171=this.hitTestCache.xlookup[x];
this.hitTestCache.x2maxy[x]=_167(map(_168(0),_171));
}
};
PlotKit.LayoutModule={};
PlotKit.LayoutModule.Layout=PlotKit.Layout;
PlotKit.LayoutModule.EXPORT=["Layout"];
PlotKit.LayoutModule.EXPORT_OK=[];
PlotKit.LayoutModule.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.LayoutModule.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.LayoutModule);
try{
if((typeof (PlotKit.Base)=="undefined")||(typeof (PlotKit.Layout)=="undefined")){
throw "";
}
}
catch(e){
throw "PlotKit.Layout depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.{Base,Layout}";
}
PlotKit.CanvasRenderer=function(_172,_173,_174){
if(arguments.length>0){
this.__init__(_172,_173,_174);
}
};
PlotKit.CanvasRenderer.NAME="PlotKit.CanvasRenderer";
PlotKit.CanvasRenderer.VERSION=PlotKit.VERSION;
PlotKit.CanvasRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.CanvasRenderer.toString=function(){
return this.__repr__();
};
PlotKit.CanvasRenderer.prototype.__init__=function(_175,_176,_177){
var _178=MochiKit.Base.isUndefinedOrNull;
var _179=MochiKit.Color.Color;
this.options={"drawBackground":true,"backgroundColor":_179.whiteColor(),"padding":{left:30,right:30,top:5,bottom:10},"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[0]),"strokeColor":null,"strokeColorTransform":"asStrokeColor","strokeWidth":0.5,"fillColorTransform":null,"shouldFill":true,"shouldStroke":true,"drawXAxis":true,"drawYAxis":true,"axisLineColor":_179.blackColor(),"axisLineWidth":0.5,"axisTickSize":3,"axisLabelColor":_179.blackColor(),"axisLabelFont":"Arial","axisLabelFontSize":9,"axisLabelWidth":50,"pieRadius":0.4,"enableEvents":true};
MochiKit.Base.update(this.options,_177?_177:{});
this.layout=_176;
this.element=MochiKit.DOM.getElement(_175);
this.container=this.element.parentNode;
this.isIE=PlotKit.Base.excanvasSupported();
if(this.isIE&&!_178(G_vmlCanvasManager)){
this.IEDelay=0.5;
this.maxTries=5;
this.renderDelay=null;
this.clearDelay=null;
this.element=G_vmlCanvasManager.initElement(this.element);
}
this.height=MochiKit.DOM.elementDimensions(this.element).h;
this.width=MochiKit.DOM.elementDimensions(this.element).w;
this.element.width=this.width;
this.element.height=this.height;
if(_178(this.element)){
throw "CanvasRenderer() - passed canvas is not found";
}
if(!this.isIE&&!(PlotKit.CanvasRenderer.isSupported(this.element))){
throw "CanvasRenderer() - Canvas is not supported.";
}
if(_178(this.container)||(this.container.nodeName.toLowerCase()!="div")){
throw "CanvasRenderer() - <canvas> needs to be enclosed in <div>";
}
this.xlabels=new Array();
this.ylabels=new Array();
this.isFirstRender=true;
this.area={x:this.options.padding.left,y:this.options.padding.top,w:this.width-this.options.padding.left-this.options.padding.right,h:this.height-this.options.padding.top-this.options.padding.bottom};
MochiKit.DOM.updateNodeAttributes(this.container,{"style":{"position":"relative","width":this.width+"px"}});
try{
this.event_isinside=null;
if(MochiKit.Signal&&this.options.enableEvents){
this._initialiseEvents();
}
}
catch(e){
}
};
PlotKit.CanvasRenderer.prototype.render=function(){
if(this.isIE){
try{
if(this.renderDelay){
this.renderDelay.cancel();
this.renderDelay=null;
}
var _180=this.element.getContext("2d");
}
catch(e){
this.isFirstRender=false;
if(this.maxTries-->0){
this.renderDelay=MochiKit.Async.wait(this.IEDelay);
this.renderDelay.addCallback(MochiKit.Base.bind(this.render,this));
}
return;
}
}
if(this.options.drawBackground){
this._renderBackground();
}
if(this.layout.style=="bar"){
this._renderBarChart();
this._renderBarAxis();
}else{
if(this.layout.style=="pie"){
this._renderPieChart();
this._renderPieAxis();
}else{
if(this.layout.style=="line"){
this._renderLineChart();
this._renderLineAxis();
}else{
if(this.layout.style=="point"){
this._renderLineAxis();
this._renderPointChart();
}else{
if(this.layout.style=="area"){
this._renderLineAxis();
this._renderAreaChart();
}
}
}
}
}
};
PlotKit.CanvasRenderer.prototype._renderBarChartWrap=function(data,_182){
var _183=this.element.getContext("2d");
var _184=this.options.colorScheme.length;
var _185=this.options.colorScheme;
var _186=this.layout.datasetNames;
var _187=_186.length;
for(var i=0;i<_187;i++){
var _188=_186[i];
var _189=_185[i%_184];
_183.save();
_183.fillStyle=this._fillColor(_189);
_183.strokeStyle=this._strokeColor(_189);
_183.lineWidth=this.options.strokeWidth;
var _190=function(obj){
if(obj.name==_188){
_182(_183,obj);
}
};
MochiKit.Iter.forEach(data,MochiKit.Base.bind(_190,this));
_183.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _192=function(_193,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
if((w<1)||(h<1)){
return;
}
if(this.options.shouldFill){
_193.fillRect(x,y,w,h);
}
if(this.options.shouldStroke){
_193.strokeRect(x,y,w,h);
}
};
this._renderBarChartWrap(this.layout.bars,bind(_192,this));
};
PlotKit.CanvasRenderer.prototype._renderLineChart=function(){
var _196=this.element.getContext("2d");
var _197=this.options.colorScheme.length;
var _198=this.options.colorScheme;
var _199=this.layout.datasetNames;
var _200=_199.length;
var bind=MochiKit.Base.bind;
var _201=MochiKit.Base.partial;
for(var i=0;i<_200;i++){
var _202=_199[i];
var _203=_198[i%_197];
_196.save();
_196.fillStyle=this._fillColor(_203);
_196.strokeStyle=this._strokeColor(_203);
_196.lineWidth=this.options.strokeWidth;
var _204=function(ctx){
ctx.beginPath();
ctx.moveTo(this.area.x,this.area.y+this.area.h);
var _206=function(ctx_,_208){
if(_208.name==_202){
ctx_.lineTo(this.area.w*_208.x+this.area.x,this.area.h*_208.y+this.area.y);
}
};
MochiKit.Iter.forEach(this.layout.points,_201(_206,ctx),this);
};
if(!this.options.shouldFill){
_204=function(ctx){
ctx.beginPath();
var _209=null;
var _210=null;
var _211=function(ctx_,_212){
if(_212.name==_202){
var x=this.area.w*_212.x+this.area.x;
var y=this.area.h*_212.y+this.area.y;
if(_209==null){
ctx_.moveTo(x,y);
_209=x;
_210=y;
}else{
ctx_.lineTo(x,y);
}
}
};
MochiKit.Iter.forEach(this.layout.points,_201(_211,ctx),this);
ctx.moveTo(_209,_210);
ctx.closePath();
};
}
if(this.options.shouldFill){
bind(_204,this)(_196);
_196.lineTo(this.area.w+this.area.x,this.area.h+this.area.y);
_196.lineTo(this.area.x,this.area.y+this.area.h);
_196.closePath();
_196.fill();
}
if(this.options.shouldStroke){
bind(_204,this)(_196);
_196.stroke();
}
_196.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderPieChart=function(){
var _213=this.element.getContext("2d");
var _214=this.options.colorScheme.length;
var _215=this.layout.slices;
var _216=this.area.x+this.area.w*0.5;
var _217=this.area.y+this.area.h*0.5;
var _218=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
if(this.isIE){
_216=parseInt(_216);
_217=parseInt(_217);
_218=parseInt(_218);
}
for(var i=0;i<_215.length;i++){
var _219=this.options.colorScheme[i%_214];
_213.save();
_213.fillStyle=this._fillColor(_219);
var _220=function(){
_213.beginPath();
_213.moveTo(_216,_217);
_213.arc(_216,_217,_218,_215[i].startAngle-Math.PI/2,_215[i].endAngle-Math.PI/2,_215[i].fraction==1);
_213.lineTo(_216,_217);
_213.closePath();
};
if(Math.abs(_215[i].startAngle-_215[i].endAngle)>0.001){
if(this.options.shouldFill){
_220();
_213.fill();
}
if(this.options.shouldStroke){
_220();
_213.lineWidth=this.options.strokeWidth;
_213.strokeStyle=this._strokeColor(_219);
_213.stroke();
}
}
_213.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderPointChart=function(){
var _221=this.element.getContext("2d");
var _222=this.options.colorScheme.length;
var _223=this.options.colorScheme;
var _224=MochiKit.Base.keys(this.layout.datasets);
var _225=_224.length;
var bind=MochiKit.Base.bind;
for(var i=0;i<_225;i++){
var _226=_224[i];
var _227=_223[i%_222];
_221.save();
_221.fillStyle=this._fillColor(_227);
_221.lineWidth=this.options.strokeWidth;
var _228=function(ctx,_229){
if(_229.name==_226){
ctx.beginPath();
ctx.arc(this.area.w*_229.x+this.area.x,this.area.h*_229.y+this.area.y,this.options.strokeWidth*5,0,2*Math.PI,false);
ctx.closePath();
ctx.fill();
}
};
MochiKit.Iter.forEach(this.layout.points,bind(_228,this,_221));
_221.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderAreaChart=function(){
var _230=this.element.getContext("2d");
var _231=this.options.colorScheme.length;
var _232=this.options.colorScheme;
var _233=MochiKit.Base.keys(this.layout.datasets);
var _234=_233.length;
var bind=MochiKit.Base.bind;
var _235=MochiKit.Base.partial;
for(var i=0;i<_234;i++){
var _236=_233[i];
var _237=_232[i%_231];
_230.save();
_230.fillStyle=this._fillColor(_237);
_230.strokeStyle=this._strokeColor(_237);
_230.lineWidth=this.options.strokeWidth;
var _238=function(ctx){
ctx.beginPath();
var _239=null;
var _240=null;
var _241=function(ctx_,_242){
if(_242.name==_236){
var x=this.area.w*_242.x+this.area.x;
var y=this.area.h*_242.y+this.area.y;
if(_239==null){
ctx_.moveTo(x,y);
_239=x;
_240=y;
}else{
ctx_.lineTo(x,y);
}
}
};
MochiKit.Iter.forEach(this.layout.points,_235(_241,ctx),this);
ctx.lineTo(_239,_240);
ctx.closePath();
};
if(this.options.shouldFill){
bind(_238,this)(_230);
_230.fill();
}
if(this.options.shouldStroke){
bind(_238,this)(_230);
_230.stroke();
}
_230.restore();
}
};
PlotKit.CanvasRenderer.prototype._renderBarAxis=function(){
this._renderAxis();
};
PlotKit.CanvasRenderer.prototype._renderLineAxis=function(){
this._renderAxis();
};
PlotKit.CanvasRenderer.prototype._renderAxis=function(){
if(!this.options.drawXAxis&&!this.options.drawYAxis){
return;
}
var DIV=MochiKit.DOM.DIV;
var _244=this.element.getContext("2d");
var _245={"style":{"position":"absolute","fontSize":this.options.axisLabelFontSize+"px","zIndex":10,"color":this.options.axisLabelColor.toRGBString(),"width":this.options.axisLabelWidth+"px","overflow":"visible"}};
_244.save();
_244.strokeStyle=this.options.axisLineColor.toRGBString();
_244.lineWidth=this.options.axisLineWidth;
if(this.options.drawYAxis){
if(this.layout.yticks){
var _246=function(tick){
if(typeof (tick)=="function"){
return;
}
var x=this.area.x;
var y=this.area.y+tick[0]*this.area.h;
_244.beginPath();
_244.moveTo(x,y);
_244.lineTo(x-this.options.axisTickSize,y);
_244.closePath();
_244.stroke();
var _247=MochiKit.DOM.DIV(_245,tick[1]);
_247.style.top=(y-this.options.axisLabelFontSize)+"px";
_247.style.left=(x-this.options.padding.left-this.options.axisTickSize)+"px";
_247.style.textAlign="right";
_247.style.width=(this.options.padding.left-this.options.axisTickSize*2)+"px";
MochiKit.DOM.appendChildNodes(this.container,_247);
this.ylabels.push(_247);
};
MochiKit.Iter.forEach(this.layout.yticks,MochiKit.Base.bind(_246,this));
}
_244.beginPath();
_244.moveTo(this.area.x,this.area.y);
_244.lineTo(this.area.x,this.area.y+this.area.h);
_244.closePath();
_244.stroke();
}
if(this.options.drawXAxis){
if(this.layout.xticks){
var _246=function(tick){
if(typeof (dataset)=="function"){
return;
}
var x=this.area.x+tick[0]*this.area.w;
var y=this.area.y+this.area.h;
_244.beginPath();
_244.moveTo(x,y);
_244.lineTo(x,y+this.options.axisTickSize);
_244.closePath();
_244.stroke();
var _248=MochiKit.DOM.DIV(_245,tick[1]);
_248.style.top=(y+this.options.axisTickSize)+"px";
_248.style.left=(x-this.options.axisLabelWidth/2)+"px";
_248.style.textAlign="center";
_248.style.width=this.options.axisLabelWidth+"px";
MochiKit.DOM.appendChildNodes(this.container,_248);
this.xlabels.push(_248);
};
MochiKit.Iter.forEach(this.layout.xticks,MochiKit.Base.bind(_246,this));
}
_244.beginPath();
_244.moveTo(this.area.x,this.area.y+this.area.h);
_244.lineTo(this.area.x+this.area.w,this.area.y+this.area.h);
_244.closePath();
_244.stroke();
}
_244.restore();
};
PlotKit.CanvasRenderer.prototype._renderPieAxis=function(){
if(!this.options.drawXAxis){
return;
}
if(this.layout.xticks){
var _249=new Array();
for(var i=0;i<this.layout.slices.length;i++){
_249[this.layout.slices[i].xval]=this.layout.slices[i];
}
var _250=this.area.x+this.area.w*0.5;
var _251=this.area.y+this.area.h*0.5;
var _252=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
var _253=this.options.axisLabelWidth;
for(var i=0;i<this.layout.xticks.length;i++){
var _254=_249[this.layout.xticks[i][0]];
if(MochiKit.Base.isUndefinedOrNull(_254)){
continue;
}
var _255=(_254.startAngle+_254.endAngle)/2;
var _256=_255;
if(_256>Math.PI*2){
_256=_256-Math.PI*2;
}else{
if(_256<0){
_256=_256+Math.PI*2;
}
}
var _257=_250+Math.sin(_256)*(_252+10);
var _258=_251-Math.cos(_256)*(_252+10);
var _259={"position":"absolute","zIndex":11,"width":_253+"px","fontSize":this.options.axisLabelFontSize+"px","overflow":"visible","color":this.options.axisLabelColor.toHexString()};
if(_256<=Math.PI*0.5){
_259["textAlign"]="left";
_259["verticalAlign"]="top";
_259["left"]=_257+"px";
_259["top"]=(_258-this.options.axisLabelFontSize)+"px";
}else{
if((_256>Math.PI*0.5)&&(_256<=Math.PI)){
_259["textAlign"]="left";
_259["verticalAlign"]="bottom";
_259["left"]=_257+"px";
_259["top"]=_258+"px";
}else{
if((_256>Math.PI)&&(_256<=Math.PI*1.5)){
_259["textAlign"]="right";
_259["verticalAlign"]="bottom";
_259["left"]=(_257-_253)+"px";
_259["top"]=_258+"px";
}else{
_259["textAlign"]="right";
_259["verticalAlign"]="bottom";
_259["left"]=(_257-_253)+"px";
_259["top"]=(_258-this.options.axisLabelFontSize)+"px";
}
}
}
var _260=MochiKit.DOM.DIV({"style":_259},this.layout.xticks[i][1]);
this.xlabels.push(_260);
MochiKit.DOM.appendChildNodes(this.container,_260);
}
}
};
PlotKit.CanvasRenderer.prototype._renderBackground=function(){
var _261=this.element.getContext("2d");
_261.save();
_261.fillStyle=this.options.backgroundColor.toRGBString();
_261.fillRect(0,0,this.width,this.height);
_261.restore();
};
PlotKit.CanvasRenderer.prototype.clear=function(){
if(this.isIE){
try{
if(this.clearDelay){
this.clearDelay.cancel();
this.clearDelay=null;
}
var _262=this.element.getContext("2d");
}
catch(e){
this.isFirstRender=false;
this.clearDelay=MochiKit.Async.wait(this.IEDelay);
this.clearDelay.addCallback(MochiKit.Base.bind(this.clear,this));
return;
}
}
var _262=this.element.getContext("2d");
_262.clearRect(0,0,this.width,this.height);
MochiKit.Iter.forEach(this.xlabels,MochiKit.DOM.removeElement);
MochiKit.Iter.forEach(this.ylabels,MochiKit.DOM.removeElement);
this.xlabels=new Array();
this.ylabels=new Array();
};
PlotKit.CanvasRenderer.prototype._strokeColor=function(_263){
var opts=this.options;
if(opts.strokeColor){
_263=opts.strokeColor;
}else{
if(typeof (opts.strokeColorTransform)=="string"){
_263=_263[opts.strokeColorTransform]();
}else{
if(typeof (opts.strokeColorTransform)=="function"){
_263=opts.strokeColorTransform(_263);
}
}
}
return _263.toRGBString();
};
PlotKit.CanvasRenderer.prototype._fillColor=function(_265){
var opts=this.options;
if(opts.fillColor){
_265=opts.fillColor;
}else{
if(typeof (opts.fillColorTransform)=="string"){
_265=_265[opts.fillColorTransform]();
}else{
if(typeof (opts.fillColorTransform)=="function"){
_265=opts.fillColorTransform(_265);
}
}
}
return _265.toRGBString();
};
PlotKit.CanvasRenderer.prototype._initialiseEvents=function(){
var _266=MochiKit.Signal.connect;
var bind=MochiKit.Base.bind;
_266(this.element,"onclick",bind(this.onclick,this));
};
PlotKit.CanvasRenderer.prototype._resolveObject=function(e){
var x=(e.mouse().page.x-PlotKit.Base.findPosX(this.element)-this.area.x)/this.area.w;
var y=(e.mouse().page.y-PlotKit.Base.findPosY(this.element)-this.area.y)/this.area.h;
var _268=this.layout.hitTest(x,y);
if(_268){
return _268;
}
return null;
};
PlotKit.CanvasRenderer.prototype._createEventObject=function(_269,e){
if(_269==null){
return null;
}
e.chart=_269;
return e;
};
PlotKit.CanvasRenderer.prototype.onclick=function(e){
var _270=this._resolveObject(e);
var _271=this._createEventObject(_270,e);
if(_271!=null){
MochiKit.Signal.signal(this,"onclick",_271);
}
};
PlotKit.CanvasRenderer.prototype.onmouseover=function(e){
var _272=this._resolveObject(e);
var _273=this._createEventObject(_272,e);
if(_273!=null){
MochiKit.Signal.signal(this,"onmouseover",_273);
}
};
PlotKit.CanvasRenderer.prototype.onmouseout=function(e){
var _274=this._resolveObject(e);
var _275=this._createEventObject(_274,e);
if(_275==null){
MochiKit.Signal.signal(this,"onmouseout",e);
}else{
MochiKit.Signal.signal(this,"onmouseout",_275);
}
};
PlotKit.CanvasRenderer.prototype.onmousemove=function(e){
var _276=this._resolveObject(e);
var _277=this._createEventObject(_276,e);
if((_276==null)&&(this.event_isinside==null)){
return;
}
if((_276!=null)&&(this.event_isinside==null)){
MochiKit.Signal.signal(this,"onmouseover",_277);
}
if((_276==null)&&(this.event_isinside!=null)){
MochiKit.Signal.signal(this,"onmouseout",_277);
}
if((_276!=null)&&(this.event_isinside!=null)){
MochiKit.Signal.signal(this,"onmousemove",_277);
}
this.event_isinside=_276;
};
PlotKit.CanvasRenderer.isSupported=function(_278){
var _279=null;
try{
if(MochiKit.Base.isUndefinedOrNull(_278)){
_279=MochiKit.DOM.CANVAS({});
}else{
_279=MochiKit.DOM.getElement(_278);
}
var _280=_279.getContext("2d");
}
catch(e){
var ie=navigator.appVersion.match(/MSIE (\d\.\d)/);
var _282=(navigator.userAgent.toLowerCase().indexOf("opera")!=-1);
if((!ie)||(ie[1]<6)||(_282)){
return false;
}
return true;
}
return true;
};
PlotKit.Canvas={};
PlotKit.Canvas.CanvasRenderer=PlotKit.CanvasRenderer;
PlotKit.Canvas.EXPORT=["CanvasRenderer"];
PlotKit.Canvas.EXPORT_OK=["CanvasRenderer"];
PlotKit.Canvas.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.Canvas.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.Canvas);
try{
if(typeof (PlotKit.Layout)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.Layout";
}
PlotKit.SVGRenderer=function(_283,_284,_285){
if(arguments.length>0){
this.__init__(_283,_284,_285);
}
};
PlotKit.SVGRenderer.NAME="PlotKit.SVGRenderer";
PlotKit.SVGRenderer.VERSION=PlotKit.VERSION;
PlotKit.SVGRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.SVGRenderer.toString=function(){
return this.__repr__();
};
PlotKit.SVGRenderer.SVGNS="http://www.w3.org/2000/svg";
PlotKit.SVGRenderer.prototype.__init__=function(_286,_287,_288){
var _289=MochiKit.Base.isUndefinedOrNull;
var _290=MochiKit.Color.Color;
this.options={"drawBackground":true,"backgroundColor":MochiKit.Color.Color.whiteColor(),"padding":{left:30,right:30,top:5,bottom:10},"colorScheme":PlotKit.Base.palette(PlotKit.Base.baseColors()[1]),"strokeColor":MochiKit.Color.Color.whiteColor(),"strokeColorTransform":"asStrokeColor","strokeWidth":0.5,"shouldFill":true,"shouldStroke":true,"drawXAxis":true,"drawYAxis":true,"axisLineColor":MochiKit.Color.Color.blackColor(),"axisLineWidth":0.5,"axisTickSize":3,"axisLabelColor":MochiKit.Color.Color.blackColor(),"axisLabelFont":"Arial","axisLabelFontSize":9,"axisLabelWidth":50,"axisLabelUseDiv":true,"pieRadius":0.4,"enableEvents":true};
MochiKit.Base.update(this.options,_288?_288:{});
this.layout=_287;
this.element=MochiKit.DOM.getElement(_286);
this.container=this.element.parentNode;
this.height=parseInt(this.element.getAttribute("height"));
this.width=parseInt(this.element.getAttribute("width"));
this.document=document;
this.root=this.element;
try{
this.document=this.element.getSVGDocument();
this.root=_289(this.document.documentElement)?this.element:this.document.documentElement;
}
catch(e){
}
this.element.style.zIndex=1;
if(_289(this.element)){
throw "SVGRenderer() - passed SVG object is not found";
}
if(_289(this.container)||this.container.nodeName.toLowerCase()!="div"){
throw "SVGRenderer() - No DIV's around the SVG.";
}
this.xlabels=new Array();
this.ylabels=new Array();
this.defs=this.createSVGElement("defs");
this.area={x:this.options.padding.left,y:this.options.padding.top,w:this.width-this.options.padding.left-this.options.padding.right,h:this.height-this.options.padding.top-this.options.padding.bottom};
MochiKit.DOM.updateNodeAttributes(this.container,{"style":{"position":"relative","width":this.width+"px"}});
};
PlotKit.SVGRenderer.prototype.render=function(){
if(this.options.drawBackground){
this._renderBackground();
}
if(this.layout.style=="bar"){
this._renderBarChart();
this._renderBarAxis();
}else{
if(this.layout.style=="pie"){
this._renderPieChart();
this._renderPieAxis();
}else{
if(this.layout.style=="line"){
this._renderLineChart();
this._renderLineAxis();
}
}
}
};
PlotKit.SVGRenderer.prototype._renderBarOrLine=function(data,_291,_292,_293){
var _294=this.options.colorScheme.length;
var _295=this.options.colorScheme;
var _296=this.layout.datasetNames;
var _297=_296.length;
for(var i=0;i<_297;i++){
var _298=_296[i];
var _299=new Array();
var _300=_295[i%_294];
if(this.options.shouldFill){
_299["fill"]=_300.toRGBString();
}else{
_299["fill"]="none";
}
if(this.options.shouldStroke&&(this.options.strokeColor||this.options.strokeColorTransform)){
if(this.options.strokeColor){
_299["stroke"]=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_299["stroke"]=_300[this.options.strokeColorTransform]().toRGBString();
}
}
_299["strokeWidth"]=this.options.strokeWidth;
}
if(_292){
_292(_299);
}
var _301=function(obj){
if(obj.name==_298){
_291(_299,obj);
}
};
MochiKit.Iter.forEach(data,MochiKit.Base.bind(_301,this));
if(_293){
_293(_299);
}
}
};
PlotKit.SVGRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _302=function(_303,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
this._drawRect(x,y,w,h,_303);
};
this._renderBarOrLine(this.layout.bars,bind(_302,this));
};
PlotKit.SVGRenderer.prototype._renderLineChart=function(){
var bind=MochiKit.Base.bind;
var _304=function(_305,_306){
this._tempPointsBuffer+=(this.area.w*_306.x+this.area.x)+","+(this.area.h*_306.y+this.area.y)+" ";
};
var _307=function(_308){
this._tempPointsBuffer="";
this._tempPointsBuffer+=(this.area.x)+","+(this.area.y+this.area.h)+" ";
};
var _309=function(_310){
this._tempPointsBuffer+=(this.area.w+this.area.x)+","+(this.area.h+this.area.y);
_310["points"]=this._tempPointsBuffer;
var elem=this.createSVGElement("polygon",_310);
this.root.appendChild(elem);
};
this._renderBarOrLine(this.layout.points,bind(_304,this),bind(_307,this),bind(_309,this));
};
PlotKit.SVGRenderer.prototype._renderPieChart=function(){
var _312=this.options.colorScheme.length;
var _313=this.layout.slices;
var _314=this.area.x+this.area.w*0.5;
var _315=this.area.y+this.area.h*0.5;
var _316=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
if(_313.length==1&&(Math.abs(_313[0].startAngle)-Math.abs(_313[0].endAngle)<0.1)){
var _317={"cx":_314,"cy":_315,"r":_316};
var _318=this.options.colorScheme[0];
if(this.options.shouldFill){
_317["fill"]=_318.toRGBString();
}else{
_317["fill"]="none";
}
if(this.options.shouldStroke&&(this.options.strokeColor||this.options.strokeColorTransform)){
if(this.options.strokeColor){
_317["stroke"]=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_317["stroke"]=_318[this.options.strokeColorTransform]().toRGBString();
}
}
_317["style"]="stroke-width: "+this.options.strokeWidth;
}
this.root.appendChild(this.createSVGElement("circle",_317));
return;
}
for(var i=0;i<_313.length;i++){
var _317=new Array();
var _318=this.options.colorScheme[i%_312];
if(this.options.shouldFill){
_317["fill"]=_318.toRGBString();
}else{
_317["fill"]="none";
}
if(this.options.shouldStroke&&(this.options.strokeColor||this.options.strokeColorTransform)){
if(this.options.strokeColor){
_317["stroke"]=this.options.strokeColor.toRGBString();
}else{
if(this.options.strokeColorTransform){
_317["stroke"]=_318[this.options.strokeColorTransform]().toRGBString();
}
}
_317["style"]="stroke-width:"+this.options.strokeWidth;
}
var _319=0;
if(Math.abs(_313[i].endAngle-_313[i].startAngle)>Math.PI){
_319=1;
}
var x1=Math.cos(_313[i].startAngle-Math.PI/2)*_316;
var y1=Math.sin(_313[i].startAngle-Math.PI/2)*_316;
var x2=Math.cos(_313[i].endAngle-Math.PI/2)*_316;
var y2=Math.sin(_313[i].endAngle-Math.PI/2)*_316;
var rx=x2-x1;
var ry=y2-y1;
var _326="M"+_314+","+_315+" ";
_326+="l"+x1+","+y1+" ";
_326+="a"+_316+","+_316+" 0 "+_319+",1 "+rx+","+ry+" z";
_317["d"]=_326;
var elem=this.createSVGElement("path",_317);
this.root.appendChild(elem);
}
};
PlotKit.SVGRenderer.prototype._renderBarAxis=function(){
this._renderAxis();
};
PlotKit.SVGRenderer.prototype._renderLineAxis=function(){
this._renderAxis();
};
PlotKit.SVGRenderer.prototype._renderAxis=function(){
if(!this.options.drawXAxis&&!this.options.drawYAxis){
return;
}
var _327={"style":{"position":"absolute","textAlign":"center","fontSize":this.options.axisLabelFontSize+"px","zIndex":10,"color":this.options.axisLabelColor.toRGBString(),"width":this.options.axisLabelWidth+"px","overflow":"hidden"}};
var _328={"stroke":this.options.axisLineColor.toRGBString(),"strokeWidth":this.options.axisLineWidth};
if(this.options.drawYAxis){
if(this.layout.yticks){
var _329=function(tick){
var x=this.area.x;
var y=this.area.y+tick[0]*this.area.h;
this._drawLine(x,y,x-3,y,_328);
if(this.options.axisLabelUseDiv){
var _330=MochiKit.DOM.DIV(_327,tick[1]);
_330.style.top=(y-this.options.axisLabelFontSize)+"px";
_330.style.left=(x-this.options.padding.left+this.options.axisTickSize)+"px";
_330.style.textAlign="left";
_330.style.width=(this.options.padding.left-3)+"px";
MochiKit.DOM.appendChildNodes(this.container,_330);
this.ylabels.push(_330);
}else{
var _331={y:y+3,x:(x-this.options.padding.left+3),width:(this.options.padding.left-this.options.axisTickSize)+"px",height:(this.options.axisLabelFontSize+3)+"px",fontFamily:"Arial",fontSize:this.options.axisLabelFontSize+"px",fill:this.options.axisLabelColor.toRGBString()};
var _330=this.createSVGElement("text",_331);
_330.appendChild(this.document.createTextNode(tick[1]));
this.root.appendChild(_330);
}
};
MochiKit.Iter.forEach(this.layout.yticks,MochiKit.Base.bind(_329,this));
}
this._drawLine(this.area.x,this.area.y,this.area.x,this.area.y+this.area.h,_328);
}
if(this.options.drawXAxis){
if(this.layout.xticks){
var _329=function(tick){
var x=this.area.x+tick[0]*this.area.w;
var y=this.area.y+this.area.h;
this._drawLine(x,y,x,y+this.options.axisTickSize,_328);
if(this.options.axisLabelUseDiv){
var _332=MochiKit.DOM.DIV(_327,tick[1]);
_332.style.top=(y+this.options.axisTickSize)+"px";
_332.style.left=(x-this.options.axisLabelWidth/2)+"px";
_332.style.textAlign="center";
_332.style.width=this.options.axisLabelWidth+"px";
MochiKit.DOM.appendChildNodes(this.container,_332);
this.xlabels.push(_332);
}else{
var _333={y:(y+this.options.axisTickSize+this.options.axisLabelFontSize),x:x-3,width:this.options.axisLabelWidth+"px",height:(this.options.axisLabelFontSize+3)+"px",fontFamily:"Arial",fontSize:this.options.axisLabelFontSize+"px",fill:this.options.axisLabelColor.toRGBString(),textAnchor:"middle"};
var _332=this.createSVGElement("text",_333);
_332.appendChild(this.document.createTextNode(tick[1]));
this.root.appendChild(_332);
}
};
MochiKit.Iter.forEach(this.layout.xticks,MochiKit.Base.bind(_329,this));
}
this._drawLine(this.area.x,this.area.y+this.area.h,this.area.x+this.area.w,this.area.y+this.area.h,_328);
}
};
PlotKit.SVGRenderer.prototype._renderPieAxis=function(){
if(this.layout.xticks){
var _334=new Array();
for(var i=0;i<this.layout.slices.length;i++){
_334[this.layout.slices[i].xval]=this.layout.slices[i];
}
var _335=this.area.x+this.area.w*0.5;
var _336=this.area.y+this.area.h*0.5;
var _337=Math.min(this.area.w*this.options.pieRadius+10,this.area.h*this.options.pieRadius+10);
var _338=this.options.axisLabelWidth;
for(var i=0;i<this.layout.xticks.length;i++){
var _339=_334[this.layout.xticks[i][0]];
if(MochiKit.Base.isUndefinedOrNull(_339)){
continue;
}
var _340=(_339.startAngle+_339.endAngle)/2;
var _341=_340;
if(_341>Math.PI*2){
_341=_341-Math.PI*2;
}else{
if(_341<0){
_341=_341+Math.PI*2;
}
}
var _342=_335+Math.sin(_341)*(_337+10);
var _343=_336-Math.cos(_341)*(_337+10);
var _344={"position":"absolute","zIndex":11,"width":_338+"px","fontSize":this.options.axisLabelFontSize+"px","overflow":"hidden","color":this.options.axisLabelColor.toHexString()};
var _345={"width":_338+"px","fontSize":this.options.axisLabelFontSize+"px","height":(this.options.axisLabelFontSize+3)+"px","fill":this.options.axisLabelColor.toRGBString()};
if(_341<=Math.PI*0.5){
MochiKit.Base.update(_344,{"textAlign":"left","verticalAlign":"top","left":_342+"px","top":(_343-this.options.axisLabelFontSize)+"px"});
MochiKit.Base.update(_345,{"x":_342,"y":(_343-this.options.axisLabelFontSize),"textAnchor":"left"});
}else{
if((_341>Math.PI*0.5)&&(_341<=Math.PI)){
MochiKit.Base.update(_344,{"textAlign":"left","verticalAlign":"bottom","left":_342+"px","top":_343+"px"});
MochiKit.Base.update(_345,{"textAnchor":"left","x":_342,"y":_343});
}else{
if((_341>Math.PI)&&(_341<=Math.PI*1.5)){
MochiKit.Base.update(_344,{"textAlign":"right","verticalAlign":"bottom","left":_342+"px","top":_343+"px"});
MochiKit.Base.update(_345,{"textAnchor":"right","x":_342-_338,"y":_343});
}else{
MochiKit.Base.update(_344,{"textAlign":"left","verticalAlign":"bottom","left":_342+"px","top":_343+"px"});
MochiKit.Base.update(_345,{"textAnchor":"left","x":_342-_338,"y":_343-this.options.axisLabelFontSize});
}
}
}
if(this.options.axisLabelUseDiv){
var _346=MochiKit.DOM.DIV({"style":_344},this.layout.xticks[i][1]);
this.xlabels.push(_346);
MochiKit.DOM.appendChildNodes(this.container,_346);
}else{
var _346=this.createSVGElement("text",_345);
_346.appendChild(this.document.createTextNode(this.layout.xticks[i][1]));
this.root.appendChild(_346);
}
}
}
};
PlotKit.SVGRenderer.prototype._renderBackground=function(){
var opts={"stroke":"none","fill":this.options.backgroundColor.toRGBString()};
this._drawRect(0,0,this.width,this.height,opts);
};
PlotKit.SVGRenderer.prototype._drawRect=function(x,y,w,h,_347){
var _348={x:x+"px",y:y+"px",width:w+"px",height:h+"px"};
if(_347){
MochiKit.Base.update(_348,_347);
}
var elem=this.createSVGElement("rect",_348);
this.root.appendChild(elem);
};
PlotKit.SVGRenderer.prototype._drawLine=function(x1,y1,x2,y2,_349){
var _350={x1:x1+"px",y1:y1+"px",x2:x2+"px",y2:y2+"px"};
if(_349){
MochiKit.Base.update(_350,_349);
}
var elem=this.createSVGElement("line",_350);
this.root.appendChild(elem);
};
PlotKit.SVGRenderer.prototype.clear=function(){
while(this.element.firstChild){
this.element.removeChild(this.element.firstChild);
}
if(this.options.axisLabelUseDiv){
for(var i=0;i<this.xlabels.length;i++){
MochiKit.DOM.removeElement(this.xlabels[i]);
}
for(var i=0;i<this.ylabels.length;i++){
MochiKit.DOM.removeElement(this.ylabels[i]);
}
}
this.xlabels=new Array();
this.ylabels=new Array();
};
PlotKit.SVGRenderer.prototype.createSVGElement=function(name,_352){
var _353=MochiKit.Base.isUndefinedOrNull;
var elem;
var doc=_353(this.document)?document:this.document;
try{
elem=doc.createElementNS(PlotKit.SVGRenderer.SVGNS,name);
}
catch(e){
elem=doc.createElement(name);
elem.setAttribute("xmlns",PlotKit.SVGRenderer.SVGNS);
}
if(_352){
MochiKit.DOM.updateNodeAttributes(elem,_352);
}
return elem;
};
PlotKit.SVGRenderer.SVG=function(_355){
var ie=navigator.appVersion.match(/MSIE (\d\.\d)/);
var _356=(navigator.userAgent.toLowerCase().indexOf("opera")!=-1);
if(ie&&(ie[1]>=6)&&(!_356)){
var _357=_355["width"]?_355["width"]:"100";
var _358=_355["height"]?_355["height"]:"100";
var eid=_355["id"]?_355["id"]:"notunique";
var html="<svg:svg width=\""+_357+"\" height=\""+_358+"\" ";
html+="id=\""+eid+"\" version=\"1.1\" baseProfile=\"full\" />";
var _361=document.createElement(html);
var _362=_361.getSVGDocument().createElementNS(PlotKit.SVGRenderer.SVGNS,"svg");
_362.setAttribute("width",_357);
_362.setAttribute("height",_358);
_361.getSVGDocument().appendChild(_362);
return _361;
}else{
return PlotKit.SVGRenderer.prototype.createSVGElement("svg",_355);
}
};
PlotKit.SVGRenderer.isSupported=function(){
var _363=(navigator.userAgent.toLowerCase().indexOf("opera")!=-1);
var _364=navigator.appVersion.match(/MSIE (\d\.\d)/);
var _365=navigator.userAgent.match(/AppleWebKit\/(\d+)/);
var _366=navigator.userAgent.match(/Opera\/(\d*\.\d*)/);
var _367=navigator.userAgent.match(/rv:(\d*\.\d*).*Gecko/);
var _368="http://www.w3.org/TR/SVG11/feature#SVG";
if(_364&&(_364[1]>=6)&&!_363){
return document.implementation.hasFeature(_368,"1.1");
}
if(_366&&(_366[1]>8.9)){
return true;
}
if(_367&&(_367>1.7)){
return true;
}
return false;
};
PlotKit.SVG={};
PlotKit.SVG.SVGRenderer=PlotKit.SVGRenderer;
PlotKit.SVG.EXPORT=["SVGRenderer"];
PlotKit.SVG.EXPORT_OK=["SVGRenderer"];
PlotKit.SVG.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.SVG.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.SVG);
try{
if(typeof (PlotKit.CanvasRenderer)=="undefined"){
throw "";
}
}
catch(e){
throw "SweetCanvas depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.{Layout, Canvas}";
}
PlotKit.SweetCanvasRenderer=function(_369,_370,_371){
if(arguments.length>0){
this.__init__(_369,_370,_371);
}
};
PlotKit.SweetCanvasRenderer.NAME="PlotKit.SweetCanvasRenderer";
PlotKit.SweetCanvasRenderer.VERSION=PlotKit.VERSION;
PlotKit.SweetCanvasRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.SweetCanvasRenderer.toString=function(){
return this.__repr__();
};
PlotKit.SweetCanvasRenderer.prototype=new PlotKit.CanvasRenderer();
PlotKit.SweetCanvasRenderer.prototype.constructor=PlotKit.SweetCanvasRenderer;
PlotKit.SweetCanvasRenderer.__super__=PlotKit.CanvasRenderer.prototype;
PlotKit.SweetCanvasRenderer.prototype.__init__=function(el,_373,opts){
var _374=PlotKit.Base.officeBlue();
MochiKit.Base.update(_374,opts);
PlotKit.SweetCanvasRenderer.__super__.__init__.call(this,el,_373,_374);
};
PlotKit.SweetCanvasRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _375=MochiKit.Color.Color.blackColor().colorWithAlpha(0.1).toRGBString();
var _376=function(_377,x,y,w,h){
_377.fillStyle=_375;
_377.fillRect(x-2,y-2,w+4,h+2);
_377.fillStyle=_375;
_377.fillRect(x-1,y-1,w+2,h+1);
};
var _378=this.options.colorScheme.length;
var _379=this.options.colorScheme;
var _380=this.layout.datasetNames;
var _381=_380.length;
var _382=function(name){
for(var i=0;i<_381;i++){
if(name==_380[i]){
return _379[i%_378];
}
}
return _379[0];
};
var _383=function(_384,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
if((w<1)||(h<1)){
return;
}
_384.save();
_384.shadowBlur=5;
_384.shadowColor=MochiKit.Color.Color.fromHexString("#888888").toRGBString();
if(this.isIE){
_384.save();
_384.fillStyle="#cccccc";
_384.fillRect(x-2,y-2,w+4,h+2);
_384.restore();
}else{
_376(_384,x,y,w,h);
}
if(this.options.shouldFill){
_384.fillStyle=this._fillColor(_382(bar.name));
_384.fillRect(x,y,w,h);
}
_384.shadowBlur=0;
_384.strokeStyle=MochiKit.Color.Color.whiteColor().toRGBString();
_384.lineWidth=2;
if(this.options.shouldStroke){
_384.strokeRect(x,y,w,h);
}
_384.restore();
};
this._renderBarChartWrap(this.layout.bars,bind(_383,this));
};
PlotKit.SweetCanvasRenderer.prototype._renderLineChart=function(){
var _385=MochiKit.Color.Color;
var _386=this.element.getContext("2d");
var _387=this.options.colorScheme.length;
var _388=this.options.colorScheme;
var _389=this.layout.datasetNames;
var _390=_389.length;
var bind=MochiKit.Base.bind;
var _391=MochiKit.Base.partial;
for(var i=0;i<_390;i++){
var _392=_389[i];
var _393=_388[i%_387];
var _394=this.options.strokeColorTransform;
_386.save();
var _395=function(ctx){
ctx.beginPath();
ctx.moveTo(this.area.x,this.area.y+this.area.h);
var _396=function(ctx_,_397){
if(_397.name==_392){
ctx_.lineTo(this.area.w*_397.x+this.area.x,this.area.h*_397.y+this.area.y);
}
};
MochiKit.Iter.forEach(this.layout.points,_391(_396,ctx),this);
ctx.lineTo(this.area.x+this.area.w,this.area.y+this.area.h);
ctx.lineTo(this.area.x,this.area.y+this.area.h);
ctx.closePath();
};
if(!this.options.shouldFill){
_395=function(ctx){
ctx.beginPath();
var _398=null;
var _399=null;
var _400=function(ctx_,_401){
if(_401.name==_392){
var x=this.area.w*_401.x+this.area.x;
var y=this.area.h*_401.y+this.area.y;
if(_398==null){
ctx_.moveTo(x,y);
_398=x;
_399=y;
}else{
ctx_.lineTo(x,y);
}
}
};
MochiKit.Iter.forEach(this.layout.points,_391(_400,ctx),this);
ctx.moveTo(_398,_399);
ctx.closePath();
};
}
if(this.options.shouldFill){
_386.save();
if(this.isIE){
_386.fillStyle="#cccccc";
}else{
_386.fillStyle=MochiKit.Color.Color.blackColor().colorWithAlpha(0.2).toRGBString();
}
_386.translate(-1,-2);
bind(_395,this)(_386);
if(this.options.shouldFill){
_386.fill();
}
_386.restore();
}
_386.shadowBlur=5;
_386.shadowColor=MochiKit.Color.Color.fromHexString("#888888").toRGBString();
_386.fillStyle=this._fillColor(_393);
_386.lineWidth=2;
_386.strokeStyle=MochiKit.Color.Color.whiteColor().toRGBString();
if(this.options.shouldFill){
bind(_395,this)(_386);
_386.fill();
}
if(this.options.shouldStroke){
if(!this.options.shouldFill){
_386.save();
_386.lineWidth=6;
_386.lineCap="round";
bind(_395,this)(_386);
_386.stroke();
_386.restore();
_386.strokeStyle=this._strokeColor(_393);
}
bind(_395,this)(_386);
_386.stroke();
}
_386.restore();
}
};
PlotKit.SweetCanvasRenderer.prototype._renderPieChart=function(){
var _402=MochiKit.Color.Color;
var _403=this.element.getContext("2d");
var _404=this.options.colorScheme.length;
var _405=this.layout.slices;
var _406=this.area.x+this.area.w*0.5;
var _407=this.area.y+this.area.h*0.5;
var _408=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
if(this.isIE){
_406=parseInt(_406);
_407=parseInt(_407);
_408=parseInt(_408);
}
if(!this.isIE){
_403.save();
var _409=MochiKit.Color.Color.blackColor().colorWithAlpha(0.2);
_403.fillStyle=_409.toRGBString();
_403.shadowBlur=5;
_403.shadowColor=MochiKit.Color.Color.fromHexString("#888888").toRGBString();
_403.translate(1,1);
_403.beginPath();
_403.moveTo(_406,_407);
_403.arc(_406,_407,_408+2,0,Math.PI*2,false);
_403.closePath();
_403.fill();
_403.restore();
}
_403.save();
_403.strokeStyle=MochiKit.Color.Color.whiteColor().toRGBString();
_403.lineWidth=2;
for(var i=0;i<_405.length;i++){
var _410=this.options.colorScheme[i%_404];
_403.fillStyle=this._fillColor(_410);
var _411=function(){
_403.beginPath();
_403.moveTo(_406,_407);
_403.arc(_406,_407,_408,_405[i].startAngle-Math.PI/2,_405[i].endAngle-Math.PI/2,_405[i].fraction==1);
_403.lineTo(_406,_407);
_403.closePath();
};
if(Math.abs(_405[i].startAngle-_405[i].endAngle)>0.0001){
if(this.options.shouldFill){
_411();
_403.fill();
}
if(this.options.shouldStroke){
_411();
_403.stroke();
}
}
}
_403.restore();
};
PlotKit.SweetCanvasRenderer.prototype._renderPointChart=function(){
var _412=this.element.getContext("2d");
var _413=this.options.colorScheme.length;
var _414=this.options.colorScheme;
var _415=MochiKit.Base.keys(this.layout.datasets);
var _416=_415.length;
var bind=MochiKit.Base.bind;
var _417=MochiKit.Base.partial;
for(var i=0;i<_416;i++){
var _418=_415[i];
var _419=_414[i%_413];
_412.save();
_412.fillStyle=this._fillColor(_419);
_412.strokeStyle=MochiKit.Color.Color.whiteColor().toRGBString();
_412.lineWidth=2;
var _420=function(ctx,_421){
if(_421.name==_418){
ctx.beginPath();
ctx.arc(this.area.w*_421.x+this.area.x,this.area.h*_421.y+this.area.y,this.options.strokeWidth*8,0,2*Math.PI,false);
ctx.closePath();
ctx.fill();
ctx.stroke();
}
};
_412.save();
_412.lineWidth=0;
if(this.isIE){
_412.fillStyle="#cccccc";
}else{
_412.fillStyle=MochiKit.Color.Color.blackColor().colorWithAlpha(0.2).toRGBString();
}
_412.translate(3,4);
MochiKit.Iter.forEach(this.layout.points,bind(_420,this,_412));
_412.restore();
_412.shadowBlur=5;
_412.shadowColor=MochiKit.Color.Color.fromHexString("#888888").toRGBString();
MochiKit.Iter.forEach(this.layout.points,bind(_420,this,_412));
_412.restore();
}
};
PlotKit.SweetCanvasRenderer.prototype._renderAreaChart=function(){
var _422=this.element.getContext("2d");
var _423=this.options.colorScheme.length;
var _424=this.options.colorScheme;
var _425=MochiKit.Base.keys(this.layout.datasets);
var _426=_425.length;
var bind=MochiKit.Base.bind;
var _427=MochiKit.Base.partial;
for(var i=0;i<_426;i++){
var _428=_425[i];
var _429=_424[i%_423];
_422.save();
_422.fillStyle=this._fillColor(_429.colorWithAlpha(0.6));
_422.lineWidth=2;
_422.strokeStyle=this._strokeColor(_429);
var _430=function(ctx){
ctx.beginPath();
var _431=null;
var _432=null;
var _433=function(ctx_,_434){
if(_434.name==_428){
var x=this.area.w*_434.x+this.area.x;
var y=this.area.h*_434.y+this.area.y;
if(_431==null){
ctx_.moveTo(x,y);
_431=x;
_432=y;
}else{
ctx_.lineTo(x,y);
}
}
};
MochiKit.Iter.forEach(this.layout.points,_427(_433,ctx),this);
ctx.lineTo(_431,_432);
ctx.closePath();
};
_422.save();
_422.strokeStyle=MochiKit.Color.Color.whiteColor().toRGBString();
_422.lineWidth=4;
_422.lineCap="round";
bind(_430,this)(_422);
_422.stroke();
_422.restore();
if(this.options.shouldFill){
bind(_430,this)(_422);
_422.fill();
}
if(this.options.shouldStroke){
bind(_430,this)(_422);
_422.stroke();
}
_422.restore();
}
};
PlotKit.SweetCanvasRenderer.prototype._renderBackground=function(){
var _435=this.element.getContext("2d");
if(this.layout.style=="bar"||this.layout.style=="line"||this.layout.style=="point"){
_435.save();
_435.fillStyle=this.options.backgroundColor.toRGBString();
_435.fillRect(this.area.x,this.area.y,this.area.w,this.area.h);
_435.strokeStyle=this.options.axisLineColor.toRGBString();
_435.lineWidth=1;
var _436=this.layout.yticks;
var _437=false;
if(this.layout.style=="bar"&&this.layout.options.barOrientation=="horizontal"){
_436=this.layout.xticks;
_437=true;
}
for(var i=0;i<_436.length;i++){
var x1=0;
var y1=0;
var x2=0;
var y2=0;
if(_437){
x1=_436[i][0]*this.area.w+this.area.x;
y1=this.area.y;
x2=x1;
y2=y1+this.area.h;
}else{
x1=this.area.x;
y1=_436[i][0]*this.area.h+this.area.y;
x2=x1+this.area.w;
y2=y1;
}
_435.beginPath();
_435.moveTo(x1,y1);
_435.lineTo(x2,y2);
_435.closePath();
_435.stroke();
}
_435.restore();
}else{
PlotKit.SweetCanvasRenderer.__super__._renderBackground.call(this);
}
};
PlotKit.SweetCanvas={};
PlotKit.SweetCanvas.SweetCanvasRenderer=PlotKit.SweetCanvasRenderer;
PlotKit.SweetCanvas.EXPORT=["SweetCanvasRenderer"];
PlotKit.SweetCanvas.EXPORT_OK=["SweetCanvasRenderer"];
PlotKit.SweetCanvas.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.SweetCanvas.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.SweetCanvas);
try{
if(typeof (PlotKit.SVGRenderer)=="undefined"){
throw "";
}
}
catch(e){
throw "SweetSVG depends on MochiKit.{Base,Color,DOM,Format} and PlotKit.{Layout, SVG}";
}
PlotKit.SweetSVGRenderer=function(_438,_439,_440){
if(arguments.length>0){
this.__init__(_438,_439,_440);
}
};
PlotKit.SweetSVGRenderer.NAME="PlotKit.SweetSVGRenderer";
PlotKit.SweetSVGRenderer.VERSION=PlotKit.VERSION;
PlotKit.SweetSVGRenderer.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.SweetSVGRenderer.toString=function(){
return this.__repr__();
};
PlotKit.SweetSVGRenderer.prototype=new PlotKit.SVGRenderer();
PlotKit.SweetSVGRenderer.prototype.constructor=PlotKit.SweetSVGRenderer;
PlotKit.SweetSVGRenderer.__super__=PlotKit.SVGRenderer.prototype;
PlotKit.SweetSVGRenderer.prototype.__init__=function(_441,_442,_443){
var _444=PlotKit.Base.officeBlue();
MochiKit.Base.update(_444,_443);
PlotKit.SweetSVGRenderer.__super__.__init__.call(this,_441,_442,_444);
};
PlotKit.SweetSVGRenderer.prototype._addDropShadowFilter=function(){
var _445=this.createSVGElement("filter",{x:0,y:0,"id":"dropShadow"});
var _446=this.createSVGElement("feOffset",{"in":"SourceGraphic","dx":0,"dy":0,"result":"topCopy"});
var blur=this.createSVGElement("feGaussianBlur",{"in":"SourceAlpha","StdDeviation":2,"result":"shadow"});
var _448=this.createSVGElement("feOffset",{"in":"shadow","dx":-1,"dy":-2,"result":"movedShadow"});
var _449=this.createSVGElement("feMerge");
var _450=this.createSVGElement("feMergeNode",{"in":"topCopy"});
var _451=this.createSVGElement("feMergeNode",{"in":"movedShadow"});
_449.appendChild(_450);
_449.appendChild(_451);
_445.appendChild(_446);
_445.appendChild(blur);
_445.appendChild(_448);
_445.appendChild(_449);
this.defs.appendChild(_445);
};
PlotKit.SweetSVGRenderer.prototype._renderBarChart=function(){
var bind=MochiKit.Base.bind;
var _452=MochiKit.Color.Color.blackColor().toRGBString();
var _453="fill:"+_452+";fill-opacity:0.15";
var _454="stroke-width: 2.0; stroke:"+MochiKit.Color.Color.whiteColor().toRGBString();
var _455=function(_456,bar){
var x=this.area.w*bar.x+this.area.x;
var y=this.area.h*bar.y+this.area.y;
var w=this.area.w*bar.w;
var h=this.area.h*bar.h;
if((w<1)||(h<1)){
return;
}
_456["style"]=_454;
this._drawRect(x-2,y-1,w+4,h+2,{"style":_453});
this._drawRect(x,y,w,h,_456);
};
this._renderBarOrLine(this.layout.bars,bind(_455,this));
};
PlotKit.SweetSVGRenderer.prototype._renderLineChart=function(){
var bind=MochiKit.Base.bind;
var _457=MochiKit.Color.Color.blackColor().toRGBString();
var _458="fill:"+_457+";fill-opacity:0.15";
var _459="stroke-width: 2.0; stroke:"+MochiKit.Color.Color.whiteColor().toRGBString();
var _460=function(_461,_462){
this._tempPointsBuffer+=(this.area.w*_462.x+this.area.x)+","+(this.area.h*_462.y+this.area.y)+" ";
};
var _463=function(_464){
this._tempPointsBuffer="";
this._tempPointsBuffer+=(this.area.x)+","+(this.area.y+this.area.h)+" ";
};
var _465=function(_466){
this._tempPointsBuffer+=(this.area.w+this.area.x)+","+(this.area.h+this.area.y);
_466["points"]=this._tempPointsBuffer;
_466["stroke"]="none";
_466["transform"]="translate(-2, -1)";
_466["style"]=_458;
var _467=this.createSVGElement("polygon",_466);
this.root.appendChild(_467);
_466["transform"]="";
_466["style"]=_459;
var elem=this.createSVGElement("polygon",_466);
this.root.appendChild(elem);
};
this._renderBarOrLine(this.layout.points,bind(_460,this),bind(_463,this),bind(_465,this));
};
PlotKit.SweetSVGRenderer.prototype._renderPieChart=function(){
var _468=this.area.x+this.area.w*0.5;
var _469=this.area.y+this.area.h*0.5;
var _470=MochiKit.Color.Color.blackColor().toRGBString();
var _471=Math.min(this.area.w*this.options.pieRadius,this.area.h*this.options.pieRadius);
var _472="fill:"+_470+";fill-opacity:0.15";
var _473=this.createSVGElement("circle",{"style":_472,"cx":_468+1,"cy":_469+1,"r":_471+1});
this.root.appendChild(_473);
PlotKit.SweetSVGRenderer.__super__._renderPieChart.call(this);
};
PlotKit.SweetSVGRenderer.prototype._renderBackground=function(){
var _474={"fill":this.options.backgroundColor.toRGBString(),"stroke":"none"};
if(this.layout.style=="bar"||this.layout.style=="line"){
this._drawRect(this.area.x,this.area.y,this.area.w,this.area.h,_474);
var _475=this.layout.yticks;
var _476=false;
if(this.layout.style=="bar"&&this.layout.options.barOrientation=="horizontal"){
_475=this.layout.xticks;
_476=true;
}
for(var i=0;i<_475.length;i++){
var x=0;
var y=0;
var w=0;
var h=0;
if(_476){
x=_475[i][0]*this.area.w+this.area.x;
y=this.area.y;
w=1;
h=this.area.h;
}else{
x=this.area.x;
y=_475[i][0]*this.area.h+this.area.y;
w=this.area.w;
h=1;
}
this._drawRect(x,y,w,h,{"fill":this.options.axisLineColor.toRGBString()});
}
}else{
PlotKit.SweetSVGRenderer.__super__._renderBackground.call(this);
}
};
PlotKit.SweetSVG={};
PlotKit.SweetSVG.SweetSVGRenderer=PlotKit.SweetSVGRenderer;
PlotKit.SweetSVG.EXPORT=["SweetSVGRenderer"];
PlotKit.SweetSVG.EXPORT_OK=["SweetSVGRenderer"];
PlotKit.SweetSVG.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.SweetSVG.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.SweetSVG);
try{
if(typeof (PlotKit.CanvasRenderer)=="undefined"){
throw "";
}
}
catch(e){
throw "PlotKit.EasyPlot depends on all of PlotKit's components";
}
PlotKit.EasyPlot=function(_477,_478,_479,_480){
this.layout=new PlotKit.Layout(_477,_478);
this.divElem=_479;
this.width=parseInt(_479.getAttribute("width"));
this.height=parseInt(_479.getAttribute("height"));
this.deferredCount=0;
if(this.width<1){
this.width=this.divElem.width?this.divElem.width:300;
}
if(this.height<1){
this.height=this.divElem.height?this.divElem.height:300;
}
if(MochiKit.Base.isArrayLike(_480)){
for(var i=0;i<_480.length;i++){
if(typeof (_480[i])=="string"){
this.deferredCount++;
var d=MochiKit.Async.doSimpleXMLHttpRequest(_480[i]);
d.addCallback(MochiKit.Base.bind(PlotKit.EasyPlot.onDataLoaded,this));
}else{
if(MochiKit.Base.isArrayLike(_480[i])){
this.layout.addDataset("data-"+i,_480[i]);
}
}
}
}else{
if(!MochiKit.Base.isUndefinedOrNull(_480)){
throw "Passed datasources are not Array like";
}
}
if(CanvasRenderer.isSupported()){
this.element=MochiKit.DOM.CANVAS({"id":this.divElem.getAttribute("id")+"-canvas","width":this.width,"height":this.height},"");
this.divElem.appendChild(this.element);
this.renderer=new SweetCanvasRenderer(this.element,this.layout,_478);
}else{
if(SVGRenderer.isSupported()){
this.element=SVGRenderer.SVG({"id":this.divElem.getAttribute("id")+"-svg","width":this.width,"height":this.height,"version":"1.1","baseProfile":"full"},"");
this.divElem.appendChild(this.element);
this.renderer=new SweetSVGRenderer(this.element,this.layout,_478);
}
}
if((this.deferredCount==0)&&(this.layout.datasetNames.length>0)){
this.layout.evaluate();
this.renderer.clear();
this.renderer.render();
}
};
PlotKit.EasyPlot.NAME="PlotKit.EasyPlot";
PlotKit.EasyPlot.VERSION=PlotKit.VERSION;
PlotKit.EasyPlot.__repr__=function(){
return "["+this.NAME+" "+this.VERSION+"]";
};
PlotKit.EasyPlot.toString=function(){
return this.__repr__();
};
PlotKit.EasyPlot.onDataLoaded=function(_482){
var _483=new Array();
var _484=_482.responseText.split("\n");
for(var i=0;i<_484.length;i++){
var _485=MochiKit.Format.strip(_484[i]);
if((_485.length>1)&&(_485.charAt(0)!="#")){
_483.push(_485.split(","));
}
}
this.layout.addDataset("data-ajax-"+this.deferredCount,_483);
this.deferredCount--;
if((this.deferredCount==0)&&(this.layout.datasetNames.length>0)){
this.layout.evaluate();
this.renderer.clear();
this.renderer.render();
}
};
PlotKit.EasyPlot.prototype.reload=function(){
this.layout.evaluate();
this.renderer.clear();
this.renderer.render();
};
PlotKit.EasyPlotModule={};
PlotKit.EasyPlotModule.EasyPlot=PlotKit.EasyPlot;
PlotKit.EasyPlotModule.EXPORT=["EasyPlot"];
PlotKit.EasyPlotModule.EXPORT_OK=[];
PlotKit.EasyPlotModule.__new__=function(){
var m=MochiKit.Base;
m.nameFunctions(this);
this.EXPORT_TAGS={":common":this.EXPORT,":all":m.concat(this.EXPORT,this.EXPORT_OK)};
};
PlotKit.EasyPlotModule.__new__();
MochiKit.Base._exportSymbols(this,PlotKit.EasyPlotModule);


